import type { ColeccionRef } from './tipos'

export const estadisticaRef: ColeccionRef = {
  id: 'estadistica',
  titulo: 'Estadística (scipy y statsmodels)',
  descripcion: 'Pruebas de hipótesis, correlaciones, distribuciones y regresión con scipy.stats y statsmodels.',
  icono: '📐',
  lenguaje: 'python',
  nota: 'scipy se importa con from scipy import stats; statsmodels con import statsmodels.api as sm. Un valor-p menor a 0.05 suele considerarse "estadísticamente significativo", pero depende del contexto.',
  entradas: [
    // ───────────────────────── Pruebas de hipótesis ─────────────────────────
    {
      id: 'estadistica-ttest-ind',
      nombre: 'stats.ttest_ind()',
      grupo: 'Pruebas de hipótesis',
      firma: 'stats.ttest_ind(a, b, equal_var=True, alternative="two-sided")',
      resumen: 'Prueba t para dos grupos independientes: ¿difieren sus medias más de lo que explicaría el azar?',
      parametros: [
        { nombre: 'a, b', descripcion: 'Las dos muestras (listas o columnas).' },
        { nombre: 'equal_var', descripcion: 'False aplica la prueba de Welch, que no supone varianzas iguales (más segura).', porDefecto: 'True' },
        { nombre: 'alternative', descripcion: '"two-sided" (≠), "less" (a < b) o "greater" (a > b).', porDefecto: '"two-sided"' },
      ],
      ejemplo: `from scipy import stats\n\nantes = [100, 105, 98, 102, 101, 99]\ndespues = [130, 135, 128, 140, 133, 138]\nt, p = stats.ttest_ind(antes, despues)\nprint(p < 0.05)\nprint("t negativo:", t < 0)`,
      salida: 'True\nt negativo: True',
      notas: ['Hipótesis nula: las medias son iguales. Un p-value pequeño es evidencia contra ella; no mide la importancia práctica de la diferencia.', 'No uses prueba t para comparar un mismo grupo antes y después: eso es ttest_rel.'],
      relacionadas: ['estadistica-ttest-rel'],
      lecciones: ['m10-l5'],
    },
    {
      id: 'estadistica-ttest-rel',
      nombre: 'stats.ttest_rel()',
      grupo: 'Pruebas de hipótesis',
      firma: 'stats.ttest_rel(antes, despues)',
      resumen: 'Prueba t para datos pareados: las mismas personas o unidades medidas dos veces.',
      ejemplo: `from scipy import stats\n\nantes = [10, 12, 9, 11, 13]\ndespues = [12, 14, 10, 13, 15]\nt, p = stats.ttest_rel(antes, despues)\nprint(p < 0.05)`,
      salida: 'True',
      lecciones: ['m10-l5'],
    },
    {
      id: 'estadistica-ttest-1samp',
      nombre: 'stats.ttest_1samp()',
      grupo: 'Pruebas de hipótesis',
      firma: 'stats.ttest_1samp(muestra, media_poblacional)',
      resumen: 'Compara la media de una muestra con un valor de referencia.',
      ejemplo: `from scipy import stats\n\ntiempos = [28, 31, 35, 30, 33, 29, 34]\nt, p = stats.ttest_1samp(tiempos, 25)\nprint(p < 0.05)`,
      salida: 'True',
      lecciones: ['m10-l5'],
    },
    {
      id: 'estadistica-chi2',
      nombre: 'stats.chi2_contingency()',
      grupo: 'Pruebas de hipótesis',
      firma: 'chi2, p, gl, esperados = stats.chi2_contingency(tabla)',
      resumen: 'Prueba chi-cuadrado: ¿dos variables categóricas están relacionadas o son independientes?',
      ejemplo: `import pandas as pd\nfrom scipy import stats\n\ntabla = pd.DataFrame({"compra": [30, 10], "no_compra": [20, 40]}, index=["campaña A", "campaña B"])\nchi2, p, gl, esperados = stats.chi2_contingency(tabla)\nprint(p < 0.05)\nprint(gl)`,
      salida: 'True\n1',
      notas: ['Recibe una tabla de contingencia (conteos), por ejemplo la de pd.crosstab.'],
      relacionadas: ['pandas-crosstab'],
      lecciones: ['m10-l5'],
    },
    {
      id: 'estadistica-mannwhitney',
      nombre: 'stats.mannwhitneyu() / stats.shapiro()',
      grupo: 'Pruebas de hipótesis',
      firma: 'stats.mannwhitneyu(a, b) · stats.shapiro(datos)',
      resumen: 'Mann-Whitney: alternativa a la prueba t que no supone normalidad. Shapiro-Wilk: contrasta si unos datos parecen normales.',
      ejemplo: `from scipy import stats\n\na = [1, 2, 3, 4, 5]\nb = [6, 7, 8, 9, 10]\nu, p = stats.mannwhitneyu(a, b)\nprint(p < 0.05)\nstat, p_norm = stats.shapiro([2.1, 2.3, 2.2, 2.4, 2.5, 2.2, 2.3])\nprint(p_norm > 0.05)`,
      salida: 'True\nTrue',
      notas: ['En Shapiro-Wilk, un p-value alto significa que no hay evidencia contra la normalidad.'],
      lecciones: ['m10-l5'],
    },
    {
      id: 'estadistica-anova',
      nombre: 'stats.f_oneway()',
      grupo: 'Pruebas de hipótesis',
      firma: 'stats.f_oneway(grupo1, grupo2, grupo3, ...)',
      resumen: 'ANOVA de un factor: compara las medias de tres o más grupos.',
      ejemplo: `from scipy import stats\n\nA = [20, 22, 19, 24]\nB = [28, 30, 27, 31]\nC = [21, 23, 22, 20]\nf, p = stats.f_oneway(A, B, C)\nprint(p < 0.05)`,
      salida: 'True',
      notas: ['Un resultado significativo dice que algún grupo difiere, no cuál; hacen falta pruebas posteriores.'],
      lecciones: ['m10-l5'],
    },

    // ───────────────────────── Correlación y distribuciones ─────────────────────────
    {
      id: 'estadistica-pearsonr',
      nombre: 'stats.pearsonr() / spearmanr()',
      grupo: 'Correlación y distribuciones',
      firma: 'r, p = stats.pearsonr(x, y) · rho, p = stats.spearmanr(x, y)',
      resumen: 'Correlación (lineal con Pearson, por rangos con Spearman) junto con su valor-p.',
      ejemplo: `from scipy import stats\n\nhoras = [1, 2, 3, 4, 5, 6]\nnota = [2.0, 2.8, 3.2, 3.9, 4.3, 4.8]\nr, p = stats.pearsonr(horas, nota)\nprint(round(r, 3), p < 0.05)\nrho, _ = stats.spearmanr(horas, nota)\nprint(rho)`,
      salida: '0.995 True\n1.0',
      notas: ['Spearman es más robusto a outliers y detecta relaciones monótonas aunque no sean rectas.'],
      relacionadas: ['pandas-corr'],
      lecciones: ['m10-l3'],
    },
    {
      id: 'estadistica-norm',
      nombre: 'stats.norm (pdf, cdf, ppf)',
      grupo: 'Correlación y distribuciones',
      firma: 'stats.norm.cdf(x, loc=0, scale=1) · stats.norm.ppf(q) · stats.norm.pdf(x)',
      resumen: 'Distribución normal: cdf da la probabilidad acumulada hasta x; ppf hace lo inverso (el valor para una probabilidad).',
      parametros: [
        { nombre: 'loc', descripcion: 'Media de la distribución.', porDefecto: '0' },
        { nombre: 'scale', descripcion: 'Desviación estándar.', porDefecto: '1' },
      ],
      ejemplo: `from scipy import stats\n\nprint(round(stats.norm.cdf(1.96), 4))\nprint(round(stats.norm.ppf(0.975), 2))\nprint(round(stats.norm.cdf(130, loc=100, scale=15), 4))`,
      salida: '0.975\n1.96\n0.9772',
      notas: ['La probabilidad de estar a menos de 2 desviaciones estándar de la media es de ~95%.'],
      lecciones: ['m10-l4'],
    },
    {
      id: 'estadistica-zscore',
      nombre: 'stats.zscore()',
      grupo: 'Correlación y distribuciones',
      firma: 'stats.zscore(datos, ddof=0)',
      resumen: 'Estandariza: cuántas desviaciones estándar se aleja cada dato de la media. Útil para detectar outliers.',
      ejemplo: `from scipy import stats\n\ndatos = [10, 12, 11, 13, 12, 11, 60]\nz = stats.zscore(datos)\nprint([round(v, 1) for v in z][-1])\nprint([d for d, v in zip(datos, z) if abs(v) > 2])`,
      salida: '2.4\n[60]',
      notas: ['Una regla común: |z| > 3 (o > 2) marca un posible atípico.'],
      relacionadas: ['sklearn-standardscaler'],
      lecciones: ['m10-l2'],
    },
    {
      id: 'estadistica-describe',
      nombre: 'stats.describe() / stats.skew() / stats.kurtosis()',
      grupo: 'Correlación y distribuciones',
      firma: 'stats.describe(datos) · stats.skew(datos) · stats.kurtosis(datos)',
      resumen: 'Resumen estadístico; skew mide la asimetría y kurtosis el peso de las colas.',
      ejemplo: `from scipy import stats\n\nsimetrico = [1, 2, 3, 4, 5]\nasimetrico = [1, 1, 1, 2, 2, 3, 20]\nprint(stats.skew(simetrico))\nprint(stats.skew(asimetrico) > 1)`,
      salida: '0.0\nTrue',
      notas: ['Asimetría positiva (cola larga a la derecha): la media supera a la mediana.'],
      lecciones: ['m10-l4'],
    },

    // ───────────────────────── Regresión con statsmodels ─────────────────────────
    {
      id: 'estadistica-ols',
      nombre: 'sm.OLS()',
      grupo: 'Regresión con statsmodels',
      firma: 'modelo = sm.OLS(y, sm.add_constant(X)).fit() · modelo.params · modelo.rsquared · modelo.summary()',
      resumen: 'Regresión lineal por mínimos cuadrados con informe estadístico completo (coeficientes, p-values, R²).',
      parametros: [
        { nombre: 'y', descripcion: 'Variable objetivo.' },
        { nombre: 'X', descripcion: 'Variables explicativas. Hay que agregarle la constante (intercepto) con sm.add_constant.' },
      ],
      ejemplo: `import numpy as np\nimport statsmodels.api as sm\n\nx = np.array([1, 2, 3, 4, 5, 6])\ny = np.array([3.1, 4.9, 7.2, 8.8, 11.1, 13.0])\nmodelo = sm.OLS(y, sm.add_constant(x)).fit()\nprint(modelo.params.round(2))\nprint(round(modelo.rsquared, 3))`,
      salida: '[1.05 1.99]\n0.998',
      notas: ['params[0] es el intercepto y params[1] la pendiente. summary() imprime una tabla con errores estándar y p-values por coeficiente.', 'Si no agregas la constante, la recta se fuerza a pasar por el origen.'],
      relacionadas: ['sklearn-linearregression'],
      lecciones: ['m12-l2'],
    },
  ],
}
