import type { ColeccionRef } from './tipos'

export const matplotlibRef: ColeccionRef = {
  id: 'matplotlib',
  titulo: 'matplotlib',
  descripcion: 'Gráficos: líneas, barras, histogramas, dispersión y cómo darles título, etiquetas, leyenda y estilo.',
  icono: '📊',
  lenguaje: 'python',
  nota: 'Se importa con import matplotlib.pyplot as plt. Al ejecutar un ejemplo, el gráfico aparece debajo del código. En un script local se agrega plt.show() al final.',
  entradas: [
    // ───────────────────────── Tipos de gráfico ─────────────────────────
    {
      id: 'matplotlib-plot',
      nombre: 'plt.plot()',
      grupo: 'Tipos de gráfico',
      firma: 'plt.plot(x, y, color=None, linestyle="-", marker=None, linewidth=1.5, label=None)',
      resumen: 'Gráfico de líneas: ideal para ver cómo cambia algo en el tiempo.',
      parametros: [
        { nombre: 'x, y', descripcion: 'Valores de los ejes horizontal y vertical (si pasas solo uno, se usa como y).' },
        { nombre: 'color', descripcion: 'Nombre ("red"), código corto ("r") o hexadecimal ("#346dff").', porDefecto: 'ciclo de colores' },
        { nombre: 'linestyle', descripcion: '"-" continua, "--" guiones, ":" puntos, "-." mixta.', porDefecto: '"-"' },
        { nombre: 'marker', descripcion: 'Marca en cada punto: "o" círculo, "s" cuadrado, "^" triángulo.', porDefecto: 'None' },
        { nombre: 'linewidth', descripcion: 'Grosor de la línea.', porDefecto: '1.5' },
        { nombre: 'label', descripcion: 'Nombre de la serie para la leyenda (se muestra con plt.legend()).', porDefecto: 'None' },
      ],
      ejemplo: `import matplotlib.pyplot as plt\n\nmeses = ["Ene", "Feb", "Mar", "Abr"]\nventas = [100, 120, 90, 150]\nplt.plot(meses, ventas, marker="o", color="#346dff", label="Ventas")\nplt.title("Ventas por mes")\nplt.legend()\nprint("gráfico creado")`,
      salida: 'gráfico creado',
      lecciones: ['m9-l1'],
    },
    {
      id: 'matplotlib-bar',
      nombre: 'plt.bar() / plt.barh()',
      grupo: 'Tipos de gráfico',
      firma: 'plt.bar(x, alturas, color=None, width=0.8) · plt.barh(y, anchos)',
      resumen: 'Gráfico de barras para comparar categorías; barh las dibuja en horizontal (mejor con nombres largos).',
      ejemplo: `import matplotlib.pyplot as plt\n\ncategorias = ["Accesorios", "Electrónica", "Hogar"]\ningresos = [165, 1300, 420]\nplt.bar(categorias, ingresos, color="#4C78A8")\nplt.title("Ingresos por categoría")\nplt.ylabel("USD")\nprint("gráfico creado")`,
      salida: 'gráfico creado',
      notas: ['Las barras deben empezar en 0: recortar el eje exagera las diferencias.'],
      lecciones: ['m9-l1'],
    },
    {
      id: 'matplotlib-hist',
      nombre: 'plt.hist()',
      grupo: 'Tipos de gráfico',
      firma: 'plt.hist(datos, bins=10, color=None, edgecolor=None, density=False)',
      resumen: 'Histograma: muestra cómo se distribuye una variable numérica agrupando los datos en intervalos.',
      parametros: [
        { nombre: 'bins', descripcion: 'Número de intervalos (o lista con sus bordes).', porDefecto: '10' },
        { nombre: 'edgecolor', descripcion: 'Color del borde de las barras (ayuda a distinguirlas).', porDefecto: 'None' },
        { nombre: 'density', descripcion: 'Si es True, la altura representa densidad en lugar de conteo.', porDefecto: 'False' },
      ],
      ejemplo: `import matplotlib.pyplot as plt\n\ndatos = [5, 7, 8, 6, 9, 7, 5, 8, 10, 6, 7, 7]\nplt.hist(datos, bins=5, color="#4C78A8", edgecolor="white")\nplt.title("Distribución")\nplt.xlabel("Valor")\nplt.ylabel("Frecuencia")\nprint("gráfico creado")`,
      salida: 'gráfico creado',
      lecciones: ['m9-l2'],
    },
    {
      id: 'matplotlib-scatter',
      nombre: 'plt.scatter()',
      grupo: 'Tipos de gráfico',
      firma: 'plt.scatter(x, y, s=None, c=None, alpha=1.0, marker="o")',
      resumen: 'Gráfico de dispersión: cada punto es una observación; muestra la relación entre dos variables.',
      parametros: [
        { nombre: 's', descripcion: 'Tamaño de los puntos (puede ser un valor por punto).', porDefecto: 'None' },
        { nombre: 'c', descripcion: 'Color de los puntos (o valores numéricos para colorear por escala).', porDefecto: 'None' },
        { nombre: 'alpha', descripcion: 'Transparencia de 0 a 1; útil cuando hay muchos puntos superpuestos.', porDefecto: '1.0' },
      ],
      ejemplo: `import matplotlib.pyplot as plt\n\nhoras = [1, 2, 3, 4, 5, 6]\nnota = [2.1, 2.9, 3.0, 3.8, 4.4, 4.7]\nplt.scatter(horas, nota, s=60, alpha=0.8)\nplt.title("Horas de estudio vs nota")\nplt.xlabel("Horas")\nplt.ylabel("Nota")\nprint("gráfico creado")`,
      salida: 'gráfico creado',
      lecciones: ['m9-l3'],
    },
    {
      id: 'matplotlib-boxplot',
      nombre: 'plt.boxplot()',
      grupo: 'Tipos de gráfico',
      firma: 'plt.boxplot(datos, labels=None, vert=True)',
      resumen: 'Diagrama de caja: mediana, cuartiles y valores atípicos de uno o varios grupos.',
      ejemplo: `import matplotlib.pyplot as plt\n\ngrupo_a = [5, 6, 5, 7, 6, 5, 6]\ngrupo_b = [4, 8, 9, 5, 12, 6, 30]\nplt.boxplot([grupo_a, grupo_b], labels=["A", "B"])\nplt.title("Comparación de grupos")\nprint("gráfico creado")`,
      salida: 'gráfico creado',
      notas: ['Los puntos sueltos fuera de los "bigotes" son posibles outliers.'],
      lecciones: ['m9-l2', 'm10-l2'],
    },
    {
      id: 'matplotlib-pie',
      nombre: 'plt.pie()',
      grupo: 'Tipos de gráfico',
      firma: 'plt.pie(valores, labels=None, autopct=None)',
      resumen: 'Gráfico de pastel: partes de un total. Úsalo solo con pocas categorías (2–4).',
      ejemplo: `import matplotlib.pyplot as plt\n\nplt.pie([60, 30, 10], labels=["Web", "Tienda", "Otros"], autopct="%1.0f%%")\nplt.title("Ventas por canal")\nprint("gráfico creado")`,
      salida: 'gráfico creado',
      notas: ['Si hay más de 4 categorías, un gráfico de barras se lee mejor.'],
      lecciones: ['m9-l4'],
    },
    {
      id: 'matplotlib-fill-between',
      nombre: 'plt.fill_between()',
      grupo: 'Tipos de gráfico',
      firma: 'plt.fill_between(x, y1, y2=0, alpha=0.3)',
      resumen: 'Rellena el área entre dos curvas (o entre una curva y el eje): bandas de confianza, áreas.',
      ejemplo: `import matplotlib.pyplot as plt\n\nx = [1, 2, 3, 4]\ny = [10, 14, 12, 18]\nplt.plot(x, y)\nplt.fill_between(x, y, alpha=0.3)\nplt.title("Área bajo la curva")\nprint("gráfico creado")`,
      salida: 'gráfico creado',
      lecciones: ['m9-l1'],
    },
    {
      id: 'matplotlib-df-plot',
      nombre: 'df.plot()',
      grupo: 'Tipos de gráfico',
      firma: 'df.plot(x=None, y=None, kind="line", title=None, figsize=None)',
      resumen: 'Atajo de pandas: grafica una columna o el DataFrame completo con matplotlib por debajo.',
      parametros: [
        { nombre: 'kind', descripcion: '"line", "bar", "barh", "hist", "box", "scatter", "pie", "area".', porDefecto: '"line"' },
        { nombre: 'x, y', descripcion: 'Columnas para los ejes.', porDefecto: 'None' },
      ],
      ejemplo: `import pandas as pd\nimport matplotlib.pyplot as plt\n\ndf = pd.DataFrame({"mes": ["Ene", "Feb", "Mar"], "ventas": [100, 130, 120]})\ndf.plot(x="mes", y="ventas", kind="bar", title="Ventas", legend=False)\nprint("gráfico creado")`,
      salida: 'gráfico creado',
      lecciones: ['m9-l1'],
    },

    // ───────────────────────── Títulos, ejes y leyenda ─────────────────────────
    {
      id: 'matplotlib-title-labels',
      nombre: 'plt.title() / xlabel() / ylabel()',
      grupo: 'Títulos, ejes y leyenda',
      firma: 'plt.title(texto, fontsize=None) · plt.xlabel(texto) · plt.ylabel(texto)',
      resumen: 'Ponen el título del gráfico y los nombres de los ejes.',
      ejemplo: `import matplotlib.pyplot as plt\n\nplt.plot([1, 2, 3], [2, 4, 3])\nplt.title("Ventas semanales", fontsize=14)\nplt.xlabel("Semana")\nplt.ylabel("Unidades vendidas")\nprint(plt.gca().get_title())`,
      salida: 'Ventas semanales',
      notas: ['Todo gráfico necesita título y ejes con nombre y unidades: quien lo lee no debería adivinar qué muestra.'],
      lecciones: ['m9-l1'],
    },
    {
      id: 'matplotlib-legend',
      nombre: 'plt.legend()',
      grupo: 'Títulos, ejes y leyenda',
      firma: 'plt.legend(loc="best", title=None)',
      resumen: 'Muestra la leyenda con los nombres (label) de cada serie dibujada.',
      parametros: [{ nombre: 'loc', descripcion: 'Posición: "best", "upper left", "lower right", "center"…', porDefecto: '"best"' }],
      ejemplo: `import matplotlib.pyplot as plt\n\nplt.plot([1, 2, 3], [10, 20, 15], label="Norte")\nplt.plot([1, 2, 3], [5, 8, 12], label="Sur")\nplt.legend(loc="upper left")\nprint(len(plt.gca().get_lines()))`,
      salida: '2',
      notas: ['Cada plt.plot() necesita su label="..." para aparecer en la leyenda.'],
      lecciones: ['m9-l1'],
    },
    {
      id: 'matplotlib-grid',
      nombre: 'plt.grid()',
      grupo: 'Títulos, ejes y leyenda',
      firma: 'plt.grid(True, alpha=0.3, linestyle="--")',
      resumen: 'Dibuja una cuadrícula de fondo que ayuda a leer valores.',
      ejemplo: `import matplotlib.pyplot as plt\n\nplt.plot([1, 2, 3], [3, 1, 2])\nplt.grid(True, alpha=0.3)\nprint("gráfico creado")`,
      salida: 'gráfico creado',
      lecciones: ['m9-l1'],
    },
    {
      id: 'matplotlib-xticks',
      nombre: 'plt.xticks() / yticks()',
      grupo: 'Títulos, ejes y leyenda',
      firma: 'plt.xticks(posiciones=None, etiquetas=None, rotation=0)',
      resumen: 'Controla las marcas del eje; rotation gira las etiquetas largas para que no se empalmen.',
      ejemplo: `import matplotlib.pyplot as plt\n\nplt.bar(["Accesorios", "Electrónica", "Hogar y jardín"], [5, 9, 3])\nplt.xticks(rotation=30, ha="right")\nprint("gráfico creado")`,
      salida: 'gráfico creado',
      lecciones: ['m9-l1'],
    },
    {
      id: 'matplotlib-lim',
      nombre: 'plt.xlim() / ylim()',
      grupo: 'Títulos, ejes y leyenda',
      firma: 'plt.xlim(min, max) · plt.ylim(min, max)',
      resumen: 'Fija el rango visible de cada eje.',
      ejemplo: `import matplotlib.pyplot as plt\n\nplt.plot([1, 2, 3], [10, 20, 15])\nplt.ylim(0, 25)\nprint(plt.ylim())`,
      salida: '(0.0, 25.0)',
      notas: ['En gráficos de barras empieza siempre en 0 (ylim(0, ...)).'],
      lecciones: ['m21-l2'],
    },
    {
      id: 'matplotlib-annotate',
      nombre: 'plt.axhline() / axvline() / text() / annotate()',
      grupo: 'Títulos, ejes y leyenda',
      firma: 'plt.axhline(y) · plt.axvline(x) · plt.text(x, y, texto) · plt.annotate(texto, xy, xytext, arrowprops)',
      resumen: 'Añaden una línea de referencia (meta, promedio) o un texto/flecha que destaque un punto.',
      ejemplo: `import matplotlib.pyplot as plt\n\nventas = [100, 120, 90, 150]\nplt.plot(ventas)\nplt.axhline(sum(ventas) / len(ventas), color="gray", linestyle="--", label="Promedio")\nplt.annotate("Máximo", xy=(3, 150), xytext=(1.8, 148), arrowprops={"arrowstyle": "->"})\nplt.legend()\nprint("gráfico creado")`,
      salida: 'gráfico creado',
      lecciones: ['m21-l2'],
    },

    // ───────────────────────── Figuras y varios gráficos ─────────────────────────
    {
      id: 'matplotlib-figure',
      nombre: 'plt.figure()',
      grupo: 'Figuras y varios gráficos',
      firma: 'plt.figure(figsize=(ancho, alto), dpi=100)',
      resumen: 'Crea una figura nueva con el tamaño indicado (en pulgadas).',
      ejemplo: `import matplotlib.pyplot as plt\n\nfig = plt.figure(figsize=(8, 3))\nplt.plot([1, 2, 3])\nprint(fig.get_size_inches())`,
      salida: '[8. 3.]',
      lecciones: ['m9-l1'],
    },
    {
      id: 'matplotlib-subplots',
      nombre: 'plt.subplots()',
      grupo: 'Figuras y varios gráficos',
      firma: 'fig, ax = plt.subplots(filas=1, columnas=1, figsize=None)',
      resumen: 'Crea una figura con varios gráficos (ejes) en una cuadrícula; cada ax es un gráfico independiente.',
      ejemplo: `import matplotlib.pyplot as plt\n\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9, 3))\nax1.plot([1, 2, 3], [3, 1, 2])\nax1.set_title("Línea")\nax2.bar(["A", "B"], [4, 7])\nax2.set_title("Barras")\nfig.tight_layout()\nprint(len(fig.axes))`,
      salida: '2',
      notas: ['Con ejes (ax) los métodos llevan "set_": ax.set_title(), ax.set_xlabel(), ax.set_ylim().', 'Con varias filas y columnas, ax es una matriz: ax[0, 1].'],
      relacionadas: ['matplotlib-tight-layout'],
      lecciones: ['m21-l2'],
    },
    {
      id: 'matplotlib-tight-layout',
      nombre: 'plt.tight_layout()',
      grupo: 'Figuras y varios gráficos',
      firma: 'plt.tight_layout() · fig.tight_layout()',
      resumen: 'Ajusta los márgenes para que títulos y etiquetas no se superpongan ni se corten.',
      ejemplo: `import matplotlib.pyplot as plt\n\nfig, axes = plt.subplots(2, 1)\naxes[0].set_title("Arriba")\naxes[1].set_title("Abajo")\nfig.tight_layout()\nprint("listo")`,
      salida: 'listo',
      lecciones: ['m21-l2'],
    },
    {
      id: 'matplotlib-savefig',
      nombre: 'plt.savefig()',
      grupo: 'Figuras y varios gráficos',
      firma: 'plt.savefig(ruta, dpi=100, bbox_inches="tight")',
      resumen: 'Guarda el gráfico como imagen (PNG, PDF, SVG).',
      ejemplo: `import matplotlib.pyplot as plt\nfrom pathlib import Path\n\nplt.plot([1, 2, 3], [2, 4, 3])\nplt.savefig("grafico.png", dpi=150, bbox_inches="tight")\nprint(Path("grafico.png").exists())`,
      salida: 'True',
      notas: ['Llama a savefig antes de plt.show(): después de mostrarlo, la figura puede quedar vacía.'],
      lecciones: ['m9-l1'],
    },
    {
      id: 'matplotlib-show',
      nombre: 'plt.show()',
      grupo: 'Figuras y varios gráficos',
      firma: 'plt.show()',
      resumen: 'Muestra las figuras pendientes. Necesario en scripts; en notebooks y en esta plataforma se muestra solo.',
      ejemplo: `import matplotlib.pyplot as plt\n\nplt.plot([1, 2, 3])\nplt.show()\nprint("fin")`,
      salida: 'fin',
      lecciones: ['m0-l2', 'm9-l1'],
    },

    // ───────────────────────── Estilo ─────────────────────────
    {
      id: 'matplotlib-style',
      nombre: 'plt.style.use()',
      grupo: 'Estilo',
      firma: 'plt.style.use(nombre)',
      resumen: 'Aplica un estilo predefinido ("ggplot", "bmh", "dark_background"…) a todos los gráficos siguientes.',
      ejemplo: `import matplotlib.pyplot as plt\n\nplt.style.use("ggplot")\nplt.plot([1, 2, 3], [1, 4, 9])\nprint("ggplot" in plt.style.available)`,
      salida: 'True',
      notas: ['plt.style.available lista los estilos disponibles.'],
      lecciones: ['m9-l4'],
    },
    {
      id: 'matplotlib-colors',
      nombre: 'Colores y estilos de línea',
      grupo: 'Estilo',
      firma: 'color="red" · color="#346dff" · color="C0" · linestyle="--" · alpha=0.5',
      resumen: 'Los colores se pueden dar por nombre, código hexadecimal o ciclo (C0, C1…); alpha controla la transparencia.',
      ejemplo: `import matplotlib.pyplot as plt\n\nplt.plot([1, 2, 3], [1, 2, 3], color="red", linestyle="--", linewidth=2)\nplt.plot([1, 2, 3], [3, 2, 1], color="#346dff", alpha=0.6)\nprint(len(plt.gca().get_lines()))`,
      salida: '2',
      notas: ['Usa un color para destacar y grises para el contexto; evita más de 5–6 colores en un mismo gráfico.'],
      lecciones: ['m9-l4'],
    },
  ],
}
