import type { ColeccionRef } from './tipos'

export const numpyRef: ColeccionRef = {
  id: 'numpy',
  titulo: 'NumPy',
  descripcion: 'Arreglos numéricos rápidos: crearlos, operar con ellos sin bucles, filtrarlos y calcular estadísticas.',
  icono: '🔢',
  lenguaje: 'python',
  nota: 'Todos los ejemplos usan import numpy as np.',
  entradas: [
    // ───────────────────────── Crear arreglos ─────────────────────────
    {
      id: 'numpy-array',
      nombre: 'np.array()',
      grupo: 'Crear arreglos',
      firma: 'np.array(objeto, dtype=None)',
      resumen: 'Crea un arreglo de NumPy a partir de una lista (o lista de listas).',
      parametros: [
        { nombre: 'objeto', descripcion: 'Lista, tupla o lista de listas con los datos.' },
        { nombre: 'dtype', descripcion: 'Tipo de dato de los elementos (int, float, "float64"…). Si se omite, NumPy lo deduce.', porDefecto: 'None' },
      ],
      ejemplo: `import numpy as np\n\na = np.array([1, 2, 3])\nb = np.array([[1, 2], [3, 4]])\nprint(a)\nprint(b)\nprint(np.array([1, 2, 3], dtype=float))`,
      salida: '[1 2 3]\n[[1 2]\n [3 4]]\n[1. 2. 3.]',
      notas: ['Un arreglo solo guarda un tipo de dato: si mezclas enteros y decimales, todo pasa a decimal.'],
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-arange',
      nombre: 'np.arange()',
      grupo: 'Crear arreglos',
      firma: 'np.arange(inicio=0, fin, paso=1)',
      resumen: 'Crea una secuencia de números con un paso fijo; el final no se incluye (como range).',
      ejemplo: `import numpy as np\n\nprint(np.arange(5))\nprint(np.arange(2, 10, 3))\nprint(np.arange(0, 1, 0.25))`,
      salida: '[0 1 2 3 4]\n[2 5 8]\n[0.   0.25 0.5  0.75]',
      relacionadas: ['numpy-linspace', 'python-range'],
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-linspace',
      nombre: 'np.linspace()',
      grupo: 'Crear arreglos',
      firma: 'np.linspace(inicio, fin, num=50, endpoint=True)',
      resumen: 'Crea un número exacto de valores igualmente espaciados entre dos extremos (el final sí se incluye).',
      parametros: [
        { nombre: 'num', descripcion: 'Cuántos valores generar.', porDefecto: '50' },
        { nombre: 'endpoint', descripcion: 'Si es False, excluye el valor final.', porDefecto: 'True' },
      ],
      ejemplo: `import numpy as np\n\nprint(np.linspace(0, 1, 5))\nprint(np.linspace(0, 10, 3))`,
      salida: '[0.   0.25 0.5  0.75 1.  ]\n[ 0.  5. 10.]',
      notas: ['Muy útil para ejes de gráficos: np.linspace(0, 10, 100).'],
      relacionadas: ['numpy-arange'],
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-zeros-ones',
      nombre: 'np.zeros() / np.ones() / np.full()',
      grupo: 'Crear arreglos',
      firma: 'np.zeros(forma) · np.ones(forma) · np.full(forma, valor)',
      resumen: 'Crea arreglos llenos de ceros, unos o de un valor dado, con la forma indicada.',
      ejemplo: `import numpy as np\n\nprint(np.zeros(3))\nprint(np.ones((2, 2)))\nprint(np.full((1, 3), 7))`,
      salida: '[0. 0. 0.]\n[[1. 1.]\n [1. 1.]]\n[[7 7 7]]',
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-random',
      nombre: 'np.random',
      grupo: 'Crear arreglos',
      firma: 'rng = np.random.default_rng(semilla) · rng.integers(a, b, size) · rng.normal(media, desv, size) · rng.random(size) · rng.choice(a, size)',
      resumen: 'Genera números aleatorios (enteros, normales, uniformes) de forma reproducible con una semilla.',
      ejemplo: `import numpy as np\n\nrng = np.random.default_rng(42)\nenteros = rng.integers(1, 7, size=5)\nnormales = rng.normal(loc=100, scale=15, size=1000)\nprint(enteros.shape, enteros.min() >= 1, enteros.max() <= 6)\nprint(round(normales.mean()))`,
      salida: '(5,) True True\n100',
      notas: ['Fija siempre la semilla (default_rng(42)) para que tus resultados se puedan repetir.'],
      lecciones: ['m6-l1'],
    },

    // ───────────────────────── Atributos y forma ─────────────────────────
    {
      id: 'numpy-shape',
      nombre: 'arr.shape / ndim / size / dtype',
      grupo: 'Atributos y forma',
      firma: 'arr.shape · arr.ndim · arr.size · arr.dtype',
      resumen: 'Describen el arreglo: sus dimensiones, número de ejes, total de elementos y tipo de dato.',
      ejemplo: `import numpy as np\n\na = np.array([[1, 2, 3], [4, 5, 6]])\nprint(a.shape)\nprint(a.ndim)\nprint(a.size)\nprint(a.dtype)`,
      salida: '(2, 3)\n2\n6\nint64',
      notas: ['shape es una tupla (filas, columnas, ...). Son atributos: se escriben sin paréntesis.', 'En Windows el dtype entero por defecto puede ser int32.'],
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-reshape',
      nombre: 'arr.reshape()',
      grupo: 'Atributos y forma',
      firma: 'arr.reshape(nueva_forma)',
      resumen: 'Cambia la forma de un arreglo sin cambiar sus datos; -1 deja que NumPy calcule esa dimensión.',
      ejemplo: `import numpy as np\n\na = np.arange(6)\nprint(a.reshape(2, 3))\nprint(a.reshape(3, -1).shape)\nprint(a.reshape(-1, 1).shape)`,
      salida: '[[0 1 2]\n [3 4 5]]\n(3, 2)\n(6, 1)',
      notas: ['El número total de elementos debe coincidir. scikit-learn pide X 2D: reshape(-1, 1) convierte una columna 1D en 2D.'],
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-transpose',
      nombre: 'arr.T / flatten()',
      grupo: 'Atributos y forma',
      firma: 'arr.T · arr.flatten()',
      resumen: 'T intercambia filas por columnas (transpuesta); flatten aplana el arreglo a una dimensión.',
      ejemplo: `import numpy as np\n\na = np.array([[1, 2, 3], [4, 5, 6]])\nprint(a.T)\nprint(a.flatten())`,
      salida: '[[1 4]\n [2 5]\n [3 6]]\n[1 2 3 4 5 6]',
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-concatenate',
      nombre: 'np.concatenate() / np.vstack() / np.hstack()',
      grupo: 'Atributos y forma',
      firma: 'np.concatenate([a, b], axis=0) · np.vstack([a, b]) · np.hstack([a, b])',
      resumen: 'Une arreglos: vstack los apila en vertical (más filas) y hstack en horizontal (más columnas).',
      ejemplo: `import numpy as np\n\na = np.array([[1, 2]])\nb = np.array([[3, 4]])\nprint(np.vstack([a, b]))\nprint(np.hstack([a, b]))`,
      salida: '[[1 2]\n [3 4]]\n[[1 2 3 4]]',
      lecciones: ['m6-l1'],
    },

    // ───────────────────────── Operaciones y estadística ─────────────────────────
    {
      id: 'numpy-vectorizacion',
      nombre: 'Operaciones vectorizadas',
      grupo: 'Operaciones y estadística',
      firma: 'arr + 1 · arr * 2 · arr1 + arr2 · arr ** 2 · arr > 3',
      resumen: 'Operar sobre todo el arreglo a la vez, sin bucles for: más corto y mucho más rápido.',
      ejemplo: `import numpy as np\n\nprecios = np.array([10, 20, 30])\nprint(precios * 1.19)\nprint(precios + np.array([1, 2, 3]))\nprint(precios > 15)`,
      salida: '[11.9 23.8 35.7]\n[11 22 33]\n[False  True  True]',
      notas: ['Dos arreglos se operan elemento a elemento si tienen la misma forma (o formas compatibles: broadcasting).'],
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-sum-mean',
      nombre: 'sum() / mean() / median()',
      grupo: 'Operaciones y estadística',
      firma: 'arr.sum(axis=None) · arr.mean(axis=None) · np.median(arr, axis=None)',
      resumen: 'Suma, promedio y mediana del arreglo completo o a lo largo de un eje.',
      parametros: [{ nombre: 'axis', descripcion: '0 opera por columnas (colapsa las filas); 1 opera por filas. Sin indicar, usa todo el arreglo.', porDefecto: 'None' }],
      ejemplo: `import numpy as np\n\na = np.array([[1, 2, 3], [4, 5, 6]])\nprint(a.sum())\nprint(a.mean(axis=0))\nprint(a.sum(axis=1))\nprint(np.median(a))`,
      salida: '21\n[2.5 3.5 4.5]\n[ 6 15]\n3.5',
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-min-max',
      nombre: 'min() / max() / argmin() / argmax()',
      grupo: 'Operaciones y estadística',
      firma: 'arr.min() · arr.max() · arr.argmin() · arr.argmax()',
      resumen: 'El mínimo y el máximo, y la posición (índice) donde ocurren.',
      ejemplo: `import numpy as np\n\nventas = np.array([120, 340, 210, 90])\nprint(ventas.max(), ventas.min())\nprint(ventas.argmax())`,
      salida: '340 90\n1',
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-std-var',
      nombre: 'std() / var()',
      grupo: 'Operaciones y estadística',
      firma: 'arr.std(ddof=0) · arr.var(ddof=0)',
      resumen: 'Desviación estándar y varianza: qué tan dispersos están los datos.',
      parametros: [{ nombre: 'ddof', descripcion: 'Grados de libertad. Usa ddof=1 para la desviación de una muestra (como pandas).', porDefecto: '0' }],
      ejemplo: `import numpy as np\n\nd = np.array([2, 4, 4, 4, 5, 5, 7, 9])\nprint(d.std())\nprint(round(d.std(ddof=1), 3))`,
      salida: '2.0\n2.138',
      notas: ['NumPy usa por defecto la desviación poblacional (ddof=0); pandas usa la muestral (ddof=1).'],
      lecciones: ['m10-l1'],
    },
    {
      id: 'numpy-percentile',
      nombre: 'np.percentile() / np.quantile()',
      grupo: 'Operaciones y estadística',
      firma: 'np.percentile(arr, q) · np.quantile(arr, q)',
      resumen: 'Valor por debajo del cual cae el q% (percentile, 0-100) o la fracción q (quantile, 0-1) de los datos.',
      ejemplo: `import numpy as np\n\nd = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])\nprint(np.percentile(d, 50))\nprint(np.percentile(d, [25, 75]))\nprint(np.quantile(d, 0.9))`,
      salida: '5.5\n[3.25 7.75]\n9.1',
      relacionadas: ['pandas-quantile'],
      lecciones: ['m10-l2', 'm10-l4'],
    },
    {
      id: 'numpy-corrcoef',
      nombre: 'np.corrcoef()',
      grupo: 'Operaciones y estadística',
      firma: 'np.corrcoef(x, y)',
      resumen: 'Matriz de correlación de Pearson entre variables (valores de -1 a 1).',
      ejemplo: `import numpy as np\n\nx = np.array([1, 2, 3, 4, 5])\ny = np.array([2, 4, 6, 8, 10])\nprint(round(np.corrcoef(x, y)[0, 1], 4))\nprint(round(np.corrcoef(x, -y)[0, 1], 4))`,
      salida: '1.0\n-1.0',
      relacionadas: ['pandas-corr'],
      lecciones: ['m10-l3'],
    },
    {
      id: 'numpy-dot',
      nombre: 'np.dot() / @',
      grupo: 'Operaciones y estadística',
      firma: 'np.dot(a, b) · a @ b',
      resumen: 'Producto punto de vectores y producto de matrices.',
      ejemplo: `import numpy as np\n\nw = np.array([0.5, -1])\nx = np.array([1, 2])\nprint(np.dot(w, x))\nA = np.array([[1, 2], [3, 4]])\nprint(A @ np.array([1, 1]))`,
      salida: '-1.5\n[3 7]',
      notas: ['Es la operación central de la regresión lineal y de las redes neuronales.'],
      lecciones: ['m17-l1', 'm17-l2'],
    },
    {
      id: 'numpy-sqrt-exp',
      nombre: 'np.sqrt() / np.exp() / np.log() / np.abs()',
      grupo: 'Operaciones y estadística',
      firma: 'np.sqrt(arr) · np.exp(arr) · np.log(arr) · np.abs(arr)',
      resumen: 'Funciones matemáticas aplicadas a todos los elementos a la vez.',
      ejemplo: `import numpy as np\n\nprint(np.sqrt(np.array([4, 9, 16])))\nprint(np.round(np.exp(1), 4))\nprint(round(np.log(np.e), 4))\nprint(np.abs(np.array([-3, 2])))`,
      salida: '[2. 3. 4.]\n2.7183\n1.0\n[3 2]',
      notas: ['np.log es el logaritmo natural; para base 10 usa np.log10.'],
      lecciones: ['m17-l1'],
    },
    {
      id: 'numpy-round',
      nombre: 'np.round()',
      grupo: 'Operaciones y estadística',
      firma: 'np.round(arr, decimals=0)',
      resumen: 'Redondea todos los elementos a cierta cantidad de decimales.',
      ejemplo: `import numpy as np\n\nprint(np.round(np.array([1.2345, 2.5678]), 2))`,
      salida: '[1.23 2.57]',
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-sort-unique',
      nombre: 'np.sort() / np.unique()',
      grupo: 'Operaciones y estadística',
      firma: 'np.sort(arr) · np.unique(arr, return_counts=False)',
      resumen: 'Ordena un arreglo y obtiene sus valores distintos (con sus frecuencias si return_counts=True).',
      ejemplo: `import numpy as np\n\na = np.array([3, 1, 2, 3, 1, 3])\nprint(np.sort(a))\nvalores, cuentas = np.unique(a, return_counts=True)\nprint(valores, cuentas)`,
      salida: '[1 1 2 3 3 3]\n[1 2 3] [2 1 3]',
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-cumsum-diff',
      nombre: 'np.cumsum() / np.diff()',
      grupo: 'Operaciones y estadística',
      firma: 'np.cumsum(arr) · np.diff(arr)',
      resumen: 'cumsum calcula el acumulado; diff calcula la diferencia entre elementos consecutivos.',
      ejemplo: `import numpy as np\n\nventas = np.array([10, 15, 12, 20])\nprint(np.cumsum(ventas))\nprint(np.diff(ventas))`,
      salida: '[10 25 37 57]\n[ 5 -3  8]',
      relacionadas: ['pandas-cumsum', 'pandas-diff'],
      lecciones: ['m6-l1'],
    },

    // ───────────────────────── Selección y filtrado ─────────────────────────
    {
      id: 'numpy-indexing',
      nombre: 'Indexado y slicing',
      grupo: 'Selección y filtrado',
      firma: 'arr[i] · arr[i, j] · arr[inicio:fin] · arr[:, j] · arr[i, :]',
      resumen: 'Selecciona elementos, filas o columnas; en 2D se indica [fila, columna].',
      ejemplo: `import numpy as np\n\na = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])\nprint(a[0, 1])\nprint(a[:, 0])\nprint(a[1])\nprint(a[:2, 1:])`,
      salida: '2\n[1 4 7]\n[4 5 6]\n[[2 3]\n [5 6]]',
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-boolean-mask',
      nombre: 'Filtrado con condiciones (máscaras)',
      grupo: 'Selección y filtrado',
      firma: 'arr[arr > valor] · arr[(cond1) & (cond2)]',
      resumen: 'Se queda con los elementos que cumplen una condición.',
      ejemplo: `import numpy as np\n\nedades = np.array([15, 22, 31, 17, 45])\nprint(edades[edades >= 18])\nprint(edades[(edades > 20) & (edades < 40)])\nprint((edades >= 18).sum())`,
      salida: '[22 31 45]\n[22 31]\n3',
      notas: ['Combina condiciones con & (y), | (o) y ~ (no), cada una entre paréntesis. No uses and/or.', 'Sumar un arreglo de True/False cuenta cuántos cumplen la condición.'],
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-where',
      nombre: 'np.where()',
      grupo: 'Selección y filtrado',
      firma: 'np.where(condicion, si_verdadero, si_falso) · np.where(condicion)',
      resumen: 'Elige entre dos valores según una condición, o devuelve las posiciones donde se cumple.',
      ejemplo: `import numpy as np\n\nnotas = np.array([2.5, 4.0, 3.2, 4.8])\nprint(np.where(notas >= 3.0, "aprueba", "reprueba"))\nprint(np.where(notas >= 4.0))`,
      salida: "['reprueba' 'aprueba' 'aprueba' 'aprueba']\n(array([1, 3]),)",
      relacionadas: ['numpy-boolean-mask'],
      lecciones: ['m6-l1'],
    },
    {
      id: 'numpy-isnan',
      nombre: 'np.nan / np.isnan()',
      grupo: 'Selección y filtrado',
      firma: 'np.nan · np.isnan(arr) · np.nanmean(arr)',
      resumen: 'NaN representa un dato faltante; isnan lo detecta y nanmean promedia ignorándolos.',
      ejemplo: `import numpy as np\n\na = np.array([1.0, np.nan, 3.0])\nprint(np.isnan(a))\nprint(a.mean())\nprint(np.nanmean(a))`,
      salida: '[False  True False]\nnan\n2.0',
      notas: ['Cualquier operación con NaN da NaN; por eso existen las versiones nan* (nansum, nanmean…).'],
      relacionadas: ['pandas-isna'],
      lecciones: ['m7-l2'],
    },
  ],
}
