import type { ColeccionRef } from './tipos'

// DataFrame de ejemplo que usan casi todas las entradas.
const DF = `import pandas as pd

df = pd.DataFrame({
    "producto": ["Mouse", "Teclado", "Monitor", "Mouse", "Laptop"],
    "categoria": ["Accesorios", "Accesorios", "Electronica", "Accesorios", "Electronica"],
    "cantidad": [3, 1, 2, 5, 1],
    "precio": [15.0, 45.0, 200.0, 15.0, 900.0],
    "ciudad": ["Bogota", "Lima", "Bogota", "Cali", "Lima"],
})`

export const pandasRef: ColeccionRef = {
  id: 'pandas',
  titulo: 'pandas',
  descripcion: 'Tablas de datos (DataFrame y Series): leer, explorar, seleccionar, limpiar, transformar, agrupar y combinar.',
  icono: '🐼',
  lenguaje: 'python',
  nota: 'Los ejemplos usan este DataFrame de 5 filas (se crea al inicio de cada ejemplo): producto, categoria, cantidad, precio y ciudad. Se importa con import pandas as pd. Las salidas mostradas son las de pandas 2.2 (la versión que ejecuta esta plataforma). Con pandas 3 (2026) el código funciona igual, pero las columnas de texto se muestran con dtype `str` en lugar de `object`, y las fechas con `datetime64[us]` en lugar de `[ns]`.',
  entradas: [
    // ───────────────────────── Crear y leer datos ─────────────────────────
    {
      id: 'pandas-dataframe',
      nombre: 'pd.DataFrame()',
      grupo: 'Crear y leer datos',
      firma: 'pd.DataFrame(data=None, columns=None, index=None)',
      resumen: 'Crea una tabla (filas × columnas) a partir de un diccionario, una lista de listas, etc.',
      parametros: [
        { nombre: 'data', descripcion: 'Diccionario {columna: valores}, lista de listas, lista de diccionarios…' },
        { nombre: 'columns', descripcion: 'Nombres de las columnas (o cuáles tomar).', porDefecto: 'None' },
        { nombre: 'index', descripcion: 'Etiquetas de las filas.', porDefecto: '0, 1, 2…' },
      ],
      ejemplo: `import pandas as pd\n\ndf = pd.DataFrame({"nombre": ["Ana", "Luis"], "edad": [30, 25]})\nprint(df)\nprint(pd.DataFrame([[1, 2], [3, 4]], columns=["a", "b"]))`,
      salida: "  nombre  edad\n0    Ana    30\n1   Luis    25\n   a  b\n0  1  2\n1  3  4",
      lecciones: ['m6-l2'],
    },
    {
      id: 'pandas-series',
      nombre: 'pd.Series()',
      grupo: 'Crear y leer datos',
      firma: 'pd.Series(data, index=None, name=None)',
      resumen: 'Crea una columna de datos con etiquetas (cada columna de un DataFrame es una Series).',
      ejemplo: `import pandas as pd\n\ns = pd.Series([10, 20, 30], index=["a", "b", "c"], name="ventas")\nprint(s)\nprint(s["b"])\nprint(s.mean())`,
      salida: "a    10\nb    20\nc    30\nName: ventas, dtype: int64\n20\n20.0",
      lecciones: ['m6-l2'],
    },
    {
      id: 'pandas-read-csv',
      nombre: 'pd.read_csv()',
      grupo: 'Crear y leer datos',
      firma: 'pd.read_csv(ruta, sep=",", header="infer", names=None, usecols=None, dtype=None, parse_dates=None, index_col=None, nrows=None, na_values=None, encoding=None)',
      resumen: 'Lee un archivo CSV (o texto CSV) y lo convierte en un DataFrame.',
      parametros: [
        { nombre: 'ruta', descripcion: 'Ruta del archivo, una URL, o un objeto de texto como io.StringIO.' },
        { nombre: 'sep', descripcion: 'Separador de columnas: ";" para CSV de Excel en español, "\\t" para TSV.', porDefecto: '","' },
        { nombre: 'header', descripcion: 'Fila que contiene los nombres de columna; None si el archivo no los trae.', porDefecto: '"infer" (la primera fila)' },
        { nombre: 'names', descripcion: 'Lista con los nombres de columna a usar (útil junto con header=None).', porDefecto: 'None' },
        { nombre: 'usecols', descripcion: 'Lista de las únicas columnas que se cargan (ahorra memoria).', porDefecto: 'None' },
        { nombre: 'dtype', descripcion: 'Tipo de cada columna, p. ej. {"codigo": str} para no perder ceros a la izquierda.', porDefecto: 'None' },
        { nombre: 'parse_dates', descripcion: 'Columnas que se convierten a fecha al leer.', porDefecto: 'None' },
        { nombre: 'index_col', descripcion: 'Columna que se usa como índice.', porDefecto: 'None' },
        { nombre: 'nrows', descripcion: 'Cuántas filas leer (para probar con archivos grandes).', porDefecto: 'None' },
        { nombre: 'na_values', descripcion: 'Textos extra que se tratan como dato faltante (p. ej. "N/A", "-").', porDefecto: 'None' },
        { nombre: 'encoding', descripcion: 'Codificación del archivo: "utf-8", "latin-1" si salen símbolos raros.', porDefecto: '"utf-8"' },
      ],
      ejemplo: `import pandas as pd\nimport io\n\ntexto = """producto;precio;fecha\nMouse;15,5;2024-01-05\nTeclado;45;2024-01-07\n"""\ndf = pd.read_csv(io.StringIO(texto), sep=";", decimal=",", parse_dates=["fecha"])\nprint(df)\nprint(df.dtypes)`,
      salida: "  producto  precio      fecha\n0    Mouse    15.5 2024-01-05\n1  Teclado    45.0 2024-01-07\nproducto            object\nprecio             float64\nfecha       datetime64[ns]\ndtype: object",
      notas: ['En un computador local escribes la ruta: pd.read_csv("ventas.csv"). Aquí se usa io.StringIO para simular un archivo.', 'decimal="," sirve para números con coma decimal.'],
      relacionadas: ['pandas-to-csv', 'python-csv'],
      lecciones: ['m6-l4'],
    },
    {
      id: 'pandas-read-json',
      nombre: 'pd.read_json()',
      grupo: 'Crear y leer datos',
      firma: 'pd.read_json(ruta_o_texto, orient=None)',
      resumen: 'Lee datos en formato JSON y los convierte en un DataFrame.',
      ejemplo: `import pandas as pd\nimport io\n\ntexto = '[{"nombre": "Ana", "edad": 30}, {"nombre": "Luis", "edad": 25}]'\ndf = pd.read_json(io.StringIO(texto))\nprint(df)`,
      salida: "  nombre  edad\n0    Ana    30\n1   Luis    25",
      relacionadas: ['python-json'],
      lecciones: ['m5-l3'],
    },
    {
      id: 'pandas-to-csv',
      nombre: 'df.to_csv()',
      grupo: 'Crear y leer datos',
      firma: 'df.to_csv(ruta=None, index=True, sep=",", encoding="utf-8")',
      resumen: 'Guarda el DataFrame en un archivo CSV (o devuelve el texto si no das ruta).',
      parametros: [
        { nombre: 'ruta', descripcion: 'Archivo de destino. Sin ruta devuelve el CSV como texto.', porDefecto: 'None' },
        { nombre: 'index', descripcion: 'Si es False, no escribe el índice como columna.', porDefecto: 'True' },
        { nombre: 'sep', descripcion: 'Separador de columnas.', porDefecto: '","' },
      ],
      ejemplo: `import pandas as pd\n\ndf = pd.DataFrame({"producto": ["Mouse", "Teclado"], "precio": [15, 45]})\nprint(df.to_csv(index=False))`,
      salida: 'producto,precio\nMouse,15\nTeclado,45',
      notas: ['Casi siempre conviene index=False: si no, al releer aparece una columna extra "Unnamed: 0".'],
      relacionadas: ['pandas-read-csv'],
      lecciones: ['m6-l4'],
    },
    {
      id: 'pandas-to-dict',
      nombre: 'df.to_dict() / tolist()',
      grupo: 'Crear y leer datos',
      firma: 'df.to_dict(orient="dict") · serie.tolist()',
      resumen: 'Convierte el DataFrame a diccionario (orient="records" da una lista de filas) o una columna a lista.',
      parametros: [{ nombre: 'orient', descripcion: '"dict", "list", "records" (una lista de diccionarios por fila), "index"…', porDefecto: '"dict"' }],
      ejemplo: `import pandas as pd\n\ndf = pd.DataFrame({"a": [1, 2], "b": ["x", "y"]})\nprint(df.to_dict(orient="records"))\nprint(df["a"].tolist())`,
      salida: "[{'a': 1, 'b': 'x'}, {'a': 2, 'b': 'y'}]\n[1, 2]",
      lecciones: ['m6-l2'],
    },

    // ───────────────────────── Explorar un DataFrame ─────────────────────────
    {
      id: 'pandas-head',
      nombre: 'df.head() / df.tail()',
      grupo: 'Explorar un DataFrame',
      firma: 'df.head(n=5) · df.tail(n=5)',
      resumen: 'Muestra las primeras (head) o las últimas (tail) n filas para echar un vistazo.',
      parametros: [{ nombre: 'n', descripcion: 'Cuántas filas mostrar.', porDefecto: '5' }],
      ejemplo: `${DF}\n\nprint(df.head(2))\nprint(df.tail(1))`,
      salida: "  producto   categoria  cantidad  precio  ciudad\n0    Mouse  Accesorios         3    15.0  Bogota\n1  Teclado  Accesorios         1    45.0    Lima\n  producto    categoria  cantidad  precio ciudad\n4   Laptop  Electronica         1   900.0   Lima",
      lecciones: ['m6-l4'],
    },
    {
      id: 'pandas-shape',
      nombre: 'df.shape / len(df)',
      grupo: 'Explorar un DataFrame',
      firma: 'df.shape · len(df) · df.size',
      resumen: 'shape da (filas, columnas); len(df) da solo el número de filas.',
      ejemplo: `${DF}\n\nprint(df.shape)\nprint(len(df))\nprint(df.shape[1])`,
      salida: '(5, 5)\n5\n5',
      notas: ['shape es un atributo: se escribe sin paréntesis.'],
      lecciones: ['m6-l4'],
    },
    {
      id: 'pandas-info',
      nombre: 'df.info()',
      grupo: 'Explorar un DataFrame',
      firma: 'df.info()',
      resumen: 'Resume las columnas: nombre, cuántos valores no nulos tienen, tipo de dato y memoria usada.',
      ejemplo: `${DF}\n\ndf.info()`,
      salida: "<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 5 entries, 0 to 4\nData columns (total 5 columns):\n #   Column     Non-Null Count  Dtype  \n---  ------     --------------  -----  \n 0   producto   5 non-null      object \n 1   categoria  5 non-null      object \n 2   cantidad   5 non-null      int64  \n 3   precio     5 non-null      float64\n 4   ciudad     5 non-null      object \ndtypes: float64(1), int64(1), object(3)\nmemory usage: 332.0+ bytes",
      notas: ['Compara "Non-Null Count" con el total de filas para detectar columnas con datos faltantes.'],
      relacionadas: ['pandas-dtypes', 'pandas-isna'],
      lecciones: ['m6-l4'],
    },
    {
      id: 'pandas-describe',
      nombre: 'df.describe()',
      grupo: 'Explorar un DataFrame',
      firma: 'df.describe(include=None)',
      resumen: 'Estadísticas rápidas de las columnas numéricas: conteo, media, desviación, mínimo, cuartiles y máximo.',
      parametros: [{ nombre: 'include', descripcion: '"all" incluye también las columnas de texto; "object" solo texto.', porDefecto: 'None (solo numéricas)' }],
      ejemplo: `${DF}\n\nprint(df[["cantidad", "precio"]].describe())`,
      salida: "       cantidad      precio\ncount   5.00000    5.000000\nmean    2.40000  235.000000\nstd     1.67332  379.588593\nmin     1.00000   15.000000\n25%     1.00000   15.000000\n50%     2.00000   45.000000\n75%     3.00000  200.000000\nmax     5.00000  900.000000",
      lecciones: ['m10-l1'],
    },
    {
      id: 'pandas-dtypes',
      nombre: 'df.dtypes / df.columns / df.index',
      grupo: 'Explorar un DataFrame',
      firma: 'df.dtypes · df.columns · df.index',
      resumen: 'Tipo de cada columna, lista de nombres de columna y etiquetas de las filas.',
      ejemplo: `${DF}\n\nprint(df.dtypes)\nprint(list(df.columns))\nprint(df.index)`,
      salida: "producto      object\ncategoria     object\ncantidad       int64\nprecio       float64\nciudad        object\ndtype: object\n['producto', 'categoria', 'cantidad', 'precio', 'ciudad']\nRangeIndex(start=0, stop=5, step=1)",
      notas: ['Las columnas de texto aparecen como "object".'],
      lecciones: ['m6-l4', 'm7-l3'],
    },
    {
      id: 'pandas-value-counts',
      nombre: 'serie.value_counts()',
      grupo: 'Explorar un DataFrame',
      firma: 'serie.value_counts(normalize=False, dropna=True)',
      resumen: 'Cuenta cuántas veces aparece cada valor distinto de una columna.',
      parametros: [
        { nombre: 'normalize', descripcion: 'Si es True, devuelve proporciones en lugar de conteos.', porDefecto: 'False' },
        { nombre: 'dropna', descripcion: 'Si es False, también cuenta los nulos.', porDefecto: 'True' },
      ],
      ejemplo: `${DF}\n\nprint(df["ciudad"].value_counts())\nprint(df["ciudad"].value_counts(normalize=True))`,
      salida: "ciudad\nBogota    2\nLima      2\nCali      1\nName: count, dtype: int64\nciudad\nBogota    0.4\nLima      0.4\nCali      0.2\nName: proportion, dtype: float64",
      lecciones: ['m6-l4', 'm18-l1'],
    },
    {
      id: 'pandas-unique',
      nombre: 'serie.unique() / nunique()',
      grupo: 'Explorar un DataFrame',
      firma: 'serie.unique() · serie.nunique(dropna=True)',
      resumen: 'unique lista los valores distintos; nunique cuenta cuántos hay.',
      ejemplo: `${DF}\n\nprint(df["ciudad"].unique())\nprint(df["ciudad"].nunique())`,
      salida: "['Bogota' 'Lima' 'Cali']\n3",
      lecciones: ['m6-l4'],
    },
    {
      id: 'pandas-sample',
      nombre: 'df.sample()',
      grupo: 'Explorar un DataFrame',
      firma: 'df.sample(n=None, frac=None, random_state=None)',
      resumen: 'Toma filas al azar (para revisar una muestra o crear subconjuntos).',
      parametros: [
        { nombre: 'n', descripcion: 'Cantidad de filas.', porDefecto: 'None' },
        { nombre: 'frac', descripcion: 'Fracción de las filas (0.2 = 20%).', porDefecto: 'None' },
        { nombre: 'random_state', descripcion: 'Semilla para que el sorteo sea reproducible.', porDefecto: 'None' },
      ],
      ejemplo: `${DF}\n\nprint(len(df.sample(n=2, random_state=1)))\nprint(len(df.sample(frac=0.6, random_state=1)))`,
      salida: '2\n3',
      lecciones: ['m12-l1'],
    },

    // ───────────────────────── Seleccionar y filtrar ─────────────────────────
    {
      id: 'pandas-select-columns',
      nombre: 'df["col"] / df[["a", "b"]]',
      grupo: 'Seleccionar y filtrar',
      firma: 'df["columna"] · df[["col1", "col2"]]',
      resumen: 'Una columna entre corchetes simples da una Series; una lista de columnas da un DataFrame.',
      ejemplo: `${DF}\n\nprint(type(df["precio"]).__name__)\nprint(type(df[["precio"]]).__name__)\nprint(df[["producto", "precio"]].head(2))`,
      salida: "Series\nDataFrame\n  producto  precio\n0    Mouse    15.0\n1  Teclado    45.0",
      lecciones: ['m6-l2', 'm6-l3'],
    },
    {
      id: 'pandas-loc',
      nombre: 'df.loc[]',
      grupo: 'Seleccionar y filtrar',
      firma: 'df.loc[filas, columnas]',
      resumen: 'Selecciona por etiqueta o por condición: filas y columnas por nombre (el final del rango sí se incluye).',
      ejemplo: `${DF}\n\nprint(df.loc[0, "producto"])\nprint(df.loc[1:2, ["producto", "precio"]])\nprint(df.loc[df["precio"] > 100, "producto"])`,
      salida: "Mouse\n  producto  precio\n1  Teclado    45.0\n2  Monitor   200.0\n2    Monitor\n4     Laptop\nName: producto, dtype: object",
      notas: ['loc usa etiquetas y es inclusivo: df.loc[1:2] trae las filas 1 y 2. iloc usa posiciones y excluye el final.'],
      relacionadas: ['pandas-iloc'],
      lecciones: ['m6-l3'],
    },
    {
      id: 'pandas-iloc',
      nombre: 'df.iloc[]',
      grupo: 'Seleccionar y filtrar',
      firma: 'df.iloc[filas, columnas]',
      resumen: 'Selecciona por posición numérica (empezando en 0); el final del rango no se incluye.',
      ejemplo: `${DF}\n\nprint(df.iloc[0, 0])\nprint(df.iloc[-1])\nprint(df.iloc[1:3, 0:2])`,
      salida: "Mouse\nproducto          Laptop\ncategoria    Electronica\ncantidad               1\nprecio             900.0\nciudad              Lima\nName: 4, dtype: object\n  producto    categoria\n1  Teclado   Accesorios\n2  Monitor  Electronica",
      relacionadas: ['pandas-loc'],
      lecciones: ['m6-l3'],
    },
    {
      id: 'pandas-boolean-filter',
      nombre: 'Filtrar con condiciones',
      grupo: 'Seleccionar y filtrar',
      firma: 'df[df["col"] > valor] · df[(cond1) & (cond2)] · df[(cond1) | (cond2)] · df[~cond]',
      resumen: 'Se queda con las filas que cumplen una condición; combina condiciones con & (y), | (o) y ~ (no).',
      ejemplo: `${DF}\n\ncaros = df[df["precio"] > 100]\nprint(caros["producto"].tolist())\nbogota_caro = df[(df["ciudad"] == "Bogota") & (df["precio"] > 100)]\nprint(bogota_caro["producto"].tolist())\nprint(df[~(df["ciudad"] == "Lima")].shape[0])`,
      salida: "['Monitor', 'Laptop']\n['Monitor']\n3",
      notas: ['Cada condición va entre paréntesis. No uses and/or/not: dan error con Series.'],
      lecciones: ['m6-l3'],
    },
    {
      id: 'pandas-isin',
      nombre: 'serie.isin() / between()',
      grupo: 'Seleccionar y filtrar',
      firma: 'serie.isin(valores) · serie.between(minimo, maximo, inclusive="both")',
      resumen: 'isin comprueba pertenencia a una lista; between comprueba un rango.',
      ejemplo: `${DF}\n\nprint(df[df["ciudad"].isin(["Lima", "Cali"])]["producto"].tolist())\nprint(df[df["precio"].between(20, 300)]["producto"].tolist())`,
      salida: "['Teclado', 'Mouse', 'Laptop']\n['Teclado', 'Monitor']",
      lecciones: ['m6-l3'],
    },
    {
      id: 'pandas-query',
      nombre: 'df.query()',
      grupo: 'Seleccionar y filtrar',
      firma: 'df.query("expresion")',
      resumen: 'Filtra filas con una condición escrita como texto, más corta y legible.',
      ejemplo: `${DF}\n\nprint(df.query("precio > 100 and ciudad == 'Lima'")["producto"].tolist())\nminimo = 40\nprint(df.query("precio > @minimo")["producto"].tolist())`,
      salida: "['Laptop']\n['Teclado', 'Monitor', 'Laptop']",
      notas: ['Usa @variable para referirte a variables de Python dentro del texto.'],
      relacionadas: ['pandas-boolean-filter'],
      lecciones: ['m6-l3'],
    },
    {
      id: 'pandas-sort-values',
      nombre: 'df.sort_values()',
      grupo: 'Seleccionar y filtrar',
      firma: 'df.sort_values(by, ascending=True, na_position="last")',
      resumen: 'Ordena las filas por una o varias columnas.',
      parametros: [
        { nombre: 'by', descripcion: 'Columna (o lista de columnas) por la que ordenar.' },
        { nombre: 'ascending', descripcion: 'False para orden descendente; puede ser una lista, una por columna.', porDefecto: 'True' },
        { nombre: 'na_position', descripcion: '"first" o "last": dónde van los nulos.', porDefecto: '"last"' },
      ],
      ejemplo: `${DF}\n\nprint(df.sort_values("precio", ascending=False)[["producto", "precio"]].head(3))\nprint(df.sort_values(["categoria", "precio"], ascending=[True, False])["producto"].tolist())`,
      salida: "  producto  precio\n4   Laptop   900.0\n2  Monitor   200.0\n1  Teclado    45.0\n['Teclado', 'Mouse', 'Mouse', 'Laptop', 'Monitor']",
      notas: ['Devuelve un DataFrame nuevo; no modifica el original.'],
      lecciones: ['m6-l3'],
    },
    {
      id: 'pandas-nlargest',
      nombre: 'df.nlargest() / nsmallest()',
      grupo: 'Seleccionar y filtrar',
      firma: 'df.nlargest(n, columns) · df.nsmallest(n, columns)',
      resumen: 'Atajo para obtener las n filas con los valores más altos (o más bajos) de una columna.',
      ejemplo: `${DF}\n\nprint(df.nlargest(2, "precio")["producto"].tolist())\nprint(df.nsmallest(2, "precio")["producto"].tolist())`,
      salida: "['Laptop', 'Monitor']\n['Mouse', 'Mouse']",
      lecciones: ['m6-l3'],
    },
    {
      id: 'pandas-drop',
      nombre: 'df.drop()',
      grupo: 'Seleccionar y filtrar',
      firma: 'df.drop(columns=None, index=None)',
      resumen: 'Elimina columnas o filas y devuelve un DataFrame nuevo.',
      ejemplo: `${DF}\n\nprint(list(df.drop(columns=["ciudad", "categoria"]).columns))\nprint(len(df.drop(index=[0, 1])))`,
      salida: "['producto', 'cantidad', 'precio']\n3",
      notas: ['No modifica el original: guarda el resultado en una variable o reasígnalo.'],
      lecciones: ['m7-l1'],
    },
    {
      id: 'pandas-rename',
      nombre: 'df.rename()',
      grupo: 'Seleccionar y filtrar',
      firma: 'df.rename(columns={"viejo": "nuevo"})',
      resumen: 'Cambia el nombre de columnas (o de filas) con un diccionario viejo → nuevo.',
      ejemplo: `${DF}\n\nr = df.rename(columns={"producto": "item", "precio": "precio_usd"})\nprint(list(r.columns))`,
      salida: "['item', 'categoria', 'cantidad', 'precio_usd', 'ciudad']",
      notas: ['Para renombrar todas a la vez: df.columns = ["a", "b", ...].'],
      lecciones: ['m6-l2'],
    },
    {
      id: 'pandas-set-index',
      nombre: 'df.set_index() / reset_index()',
      grupo: 'Seleccionar y filtrar',
      firma: 'df.set_index("col") · df.reset_index(drop=False)',
      resumen: 'set_index convierte una columna en el índice; reset_index lo devuelve a columna (o lo descarta con drop=True).',
      ejemplo: `${DF}\n\nx = df.set_index("producto")\nprint(x.loc["Laptop", "precio"])\nprint(list(x.reset_index().columns)[:2])`,
      salida: "900.0\n['producto', 'categoria']",
      lecciones: ['m6-l2', 'm8-l1'],
    },
    {
      id: 'pandas-assign',
      nombre: 'Crear columnas nuevas / df.assign()',
      grupo: 'Seleccionar y filtrar',
      firma: 'df["nueva"] = expresion · df.assign(nueva=expresion)',
      resumen: 'Agrega una columna calculada a partir de otras; assign devuelve una copia sin tocar el original.',
      ejemplo: `${DF}\n\ndf["ingresos"] = df["cantidad"] * df["precio"]\nprint(df[["producto", "ingresos"]])\nprint(df.assign(con_iva=df["ingresos"] * 1.19)["con_iva"].round(1).tolist())`,
      salida: "  producto  ingresos\n0    Mouse      45.0\n1  Teclado      45.0\n2  Monitor     400.0\n3    Mouse      75.0\n4   Laptop     900.0\n[53.6, 53.6, 476.0, 89.2, 1071.0]",
      lecciones: ['m6-l2', 'm8-l4'],
    },

    // ───────────────────────── Limpiar datos ─────────────────────────
    {
      id: 'pandas-isna',
      nombre: 'df.isna() / notna()',
      grupo: 'Limpiar datos',
      firma: 'df.isna() · df.notna() · df.isna().sum()',
      resumen: 'Detecta valores faltantes (NaN/None): devuelve True donde falta el dato.',
      ejemplo: `import pandas as pd\nimport numpy as np\n\ndf = pd.DataFrame({"a": [1, np.nan, 3], "b": ["x", "y", None]})\nprint(df.isna())\nprint(df.isna().sum())\nprint(df["a"].notna().sum())`,
      salida: "       a      b\n0  False  False\n1   True  False\n2  False   True\na    1\nb    1\ndtype: int64\n2",
      notas: ['df.isna().sum() es la forma más rápida de ver cuántos nulos tiene cada columna.'],
      relacionadas: ['pandas-dropna', 'pandas-fillna'],
      lecciones: ['m7-l2'],
    },
    {
      id: 'pandas-dropna',
      nombre: 'df.dropna()',
      grupo: 'Limpiar datos',
      firma: 'df.dropna(axis=0, how="any", subset=None)',
      resumen: 'Elimina las filas (o columnas) con valores faltantes.',
      parametros: [
        { nombre: 'axis', descripcion: '0 elimina filas; 1 elimina columnas.', porDefecto: '0' },
        { nombre: 'how', descripcion: '"any" borra si hay algún nulo; "all" solo si todos son nulos.', porDefecto: '"any"' },
        { nombre: 'subset', descripcion: 'Lista de columnas que se revisan (el resto se ignora).', porDefecto: 'None' },
      ],
      ejemplo: `import pandas as pd\nimport numpy as np\n\ndf = pd.DataFrame({"a": [1, np.nan, 3], "b": [4, 5, np.nan]})\nprint(len(df.dropna()))\nprint(len(df.dropna(subset=["a"])))`,
      salida: '1\n2',
      notas: ['Antes de borrar, piensa si perderás demasiados datos: a veces es mejor rellenar con fillna.'],
      relacionadas: ['pandas-fillna'],
      lecciones: ['m7-l2'],
    },
    {
      id: 'pandas-fillna',
      nombre: 'df.fillna()',
      grupo: 'Limpiar datos',
      firma: 'df.fillna(valor) · df.fillna(method=...) · serie.ffill() · serie.bfill()',
      resumen: 'Rellena los valores faltantes con un valor fijo, la media, o el dato anterior/siguiente.',
      ejemplo: `import pandas as pd\nimport numpy as np\n\ns = pd.Series([10.0, np.nan, 30.0, np.nan])\nprint(s.fillna(0).tolist())\nprint(s.fillna(s.mean()).tolist())\nprint(s.ffill().tolist())`,
      salida: '[10.0, 0.0, 30.0, 0.0]\n[10.0, 20.0, 30.0, 20.0]\n[10.0, 10.0, 30.0, 30.0]',
      notas: ['Una media o mediana calculada sobre todo el dataset antes de dividir en train/test provoca data leakage.'],
      lecciones: ['m7-l2', 'm13-l4'],
    },
    {
      id: 'pandas-duplicated',
      nombre: 'df.duplicated() / drop_duplicates()',
      grupo: 'Limpiar datos',
      firma: 'df.duplicated(subset=None, keep="first") · df.drop_duplicates(subset=None, keep="first")',
      resumen: 'duplicated marca las filas repetidas; drop_duplicates las elimina.',
      parametros: [
        { nombre: 'subset', descripcion: 'Columnas que se comparan para decidir si hay duplicado.', porDefecto: 'None (todas)' },
        { nombre: 'keep', descripcion: '"first" conserva la primera aparición, "last" la última, False borra todas.', porDefecto: '"first"' },
      ],
      ejemplo: `import pandas as pd\n\ndf = pd.DataFrame({"email": ["a@x.com", "b@x.com", "a@x.com"], "ciudad": ["Bogota", "Cali", "Bogota"]})\nprint(df.duplicated().sum())\nprint(len(df.drop_duplicates()))\nprint(len(df.drop_duplicates(subset=["email"])))`,
      salida: '1\n2\n2',
      lecciones: ['m7-l1'],
    },
    {
      id: 'pandas-astype',
      nombre: 'serie.astype()',
      grupo: 'Limpiar datos',
      firma: 'serie.astype(tipo)',
      resumen: 'Convierte una columna a otro tipo de dato (int, float, str, "category", "datetime64[ns]").',
      ejemplo: `import pandas as pd\n\ns = pd.Series(["1", "2", "3"])\nprint(s.astype(int).sum())\nprint(pd.Series([1.0, 2.0]).astype(int).tolist())\nprint(pd.Series(["a", "b", "a"]).astype("category").dtype)`,
      salida: '6\n[1, 2]\ncategory',
      notas: ['Falla si algún valor no se puede convertir ("abc" a int). Para convertir ignorando errores usa pd.to_numeric(errors="coerce").'],
      relacionadas: ['pandas-to-numeric'],
      lecciones: ['m7-l3'],
    },
    {
      id: 'pandas-to-numeric',
      nombre: 'pd.to_numeric()',
      grupo: 'Limpiar datos',
      firma: 'pd.to_numeric(serie, errors="raise")',
      resumen: 'Convierte texto a número; con errors="coerce" los valores inválidos pasan a NaN.',
      parametros: [{ nombre: 'errors', descripcion: '"raise" lanza error; "coerce" convierte lo inválido en NaN; "ignore" deja todo igual.', porDefecto: '"raise"' }],
      ejemplo: `import pandas as pd\n\ns = pd.Series(["10", "25", "N/A", "7"])\nn = pd.to_numeric(s, errors="coerce")\nprint(n.tolist())\nprint(n.isna().sum())`,
      salida: '[10.0, 25.0, nan, 7.0]\n1',
      lecciones: ['m7-l3'],
    },
    {
      id: 'pandas-replace',
      nombre: 'serie.replace()',
      grupo: 'Limpiar datos',
      firma: 'serie.replace(viejo, nuevo) · serie.replace({"a": "x", "b": "y"})',
      resumen: 'Sustituye valores por otros (uno a uno o con un diccionario de equivalencias).',
      ejemplo: `import pandas as pd\n\ns = pd.Series(["M", "F", "M", "?"])\nprint(s.replace({"M": "Masculino", "F": "Femenino"}).tolist())`,
      salida: "['Masculino', 'Femenino', 'Masculino', '?']",
      lecciones: ['m7-l2'],
    },
    {
      id: 'pandas-str-accessor',
      nombre: 'serie.str.* (métodos de texto)',
      grupo: 'Limpiar datos',
      firma: 'serie.str.lower() · .strip() · .replace(a, b) · .contains(txt) · .startswith(txt) · .split(sep) · .len() · .title()',
      resumen: 'Aplica operaciones de texto a toda una columna a la vez.',
      ejemplo: `import pandas as pd\n\ns = pd.Series(["  Ana Perez ", "LUIS gomez", "marta"])\nlimpio = s.str.strip().str.title()\nprint(limpio.tolist())\nprint(s.str.lower().str.contains("a").tolist())\nprint(limpio.str.split(" ").str[0].tolist())`,
      salida: "['Ana Perez', 'Luis Gomez', 'Marta']\n[True, False, True]\n['Ana', 'Luis', 'Marta']",
      notas: ['Los valores nulos se propagan (el resultado es NaN), no dan error.'],
      relacionadas: ['python-str-strip'],
      lecciones: ['m7-l1', 'm7-l3'],
    },
    {
      id: 'pandas-apply',
      nombre: 'serie.apply() / map()',
      grupo: 'Limpiar datos',
      firma: 'serie.apply(funcion) · serie.map(funcion_o_diccionario) · df.apply(funcion, axis=1)',
      resumen: 'Aplica una función a cada valor de una columna (o a cada fila con axis=1).',
      ejemplo: `${DF}\n\nprint(df["precio"].apply(lambda p: "caro" if p > 100 else "barato").tolist())\nprint(df["ciudad"].map({"Bogota": "BOG", "Lima": "LIM", "Cali": "CLO"}).tolist())\nprint(df.apply(lambda f: f["cantidad"] * f["precio"], axis=1).tolist())`,
      salida: "['barato', 'barato', 'caro', 'barato', 'caro']\n['BOG', 'LIM', 'BOG', 'CLO', 'LIM']\n[45.0, 45.0, 400.0, 75.0, 900.0]",
      notas: ['Las operaciones vectorizadas (df["a"] * df["b"]) son mucho más rápidas que apply: úsalo solo cuando no haya alternativa.'],
      lecciones: ['m7-l3'],
    },
    {
      id: 'pandas-clip',
      nombre: 'serie.clip() / round()',
      grupo: 'Limpiar datos',
      firma: 'serie.clip(lower=None, upper=None) · serie.round(decimales=0)',
      resumen: 'clip limita los valores a un rango (útil con outliers); round redondea.',
      ejemplo: `import pandas as pd\n\ns = pd.Series([-5, 3, 12, 40])\nprint(s.clip(lower=0, upper=10).tolist())\nprint(pd.Series([1.234, 5.678]).round(1).tolist())`,
      salida: '[0, 3, 10, 10]\n[1.2, 5.7]',
      lecciones: ['m10-l2'],
    },
    {
      id: 'pandas-get-dummies',
      nombre: 'pd.get_dummies()',
      grupo: 'Limpiar datos',
      firma: 'pd.get_dummies(df, columns=None, drop_first=False, dtype=int)',
      resumen: 'One-Hot Encoding: convierte columnas de texto en columnas 0/1, una por categoría.',
      parametros: [
        { nombre: 'columns', descripcion: 'Qué columnas codificar (si se omite, todas las de texto).', porDefecto: 'None' },
        { nombre: 'drop_first', descripcion: 'Elimina la primera categoría para evitar redundancia (útil en regresión lineal).', porDefecto: 'False' },
        { nombre: 'dtype', descripcion: 'Tipo de las columnas resultantes; int da 0/1 en lugar de True/False.', porDefecto: 'bool' },
      ],
      ejemplo: `import pandas as pd\n\ndf = pd.DataFrame({"plan": ["Basico", "Premium", "Basico"], "gasto": [20, 80, 25]})\nprint(pd.get_dummies(df, columns=["plan"], dtype=int))`,
      salida: "   gasto  plan_Basico  plan_Premium\n0     20            1             0\n1     80            0             1\n2     25            1             0",
      relacionadas: ['sklearn-onehotencoder'],
      lecciones: ['m13-l1'],
    },

    // ───────────────────────── Fechas y series de tiempo ─────────────────────────
    {
      id: 'pandas-to-datetime',
      nombre: 'pd.to_datetime()',
      grupo: 'Fechas y series de tiempo',
      firma: 'pd.to_datetime(serie, format=None, errors="raise", dayfirst=False)',
      resumen: 'Convierte texto a fechas reales para poder filtrar, restar y agrupar por tiempo.',
      parametros: [
        { nombre: 'format', descripcion: 'Formato exacto del texto, p. ej. "%d/%m/%Y". Acelera y evita ambigüedades.', porDefecto: 'None' },
        { nombre: 'errors', descripcion: '"coerce" convierte lo inválido en NaT (fecha nula).', porDefecto: '"raise"' },
        { nombre: 'dayfirst', descripcion: 'Si es True, interpreta 05/03/2024 como 5 de marzo.', porDefecto: 'False' },
      ],
      ejemplo: `import pandas as pd\n\ns = pd.to_datetime(pd.Series(["15/03/2024", "01/04/2024"]), format="%d/%m/%Y")\nprint(s.dt.month.tolist())\nprint((s.iloc[1] - s.iloc[0]).days)`,
      salida: '[3, 4]\n17',
      relacionadas: ['python-datetime'],
      lecciones: ['m7-l3'],
    },
    {
      id: 'pandas-dt-accessor',
      nombre: 'serie.dt.* (partes de una fecha)',
      grupo: 'Fechas y series de tiempo',
      firma: 'serie.dt.year · .month · .day · .dayofweek · .day_name() · .strftime(formato)',
      resumen: 'Extrae año, mes, día, día de la semana, etc. de una columna de fechas.',
      ejemplo: `import pandas as pd\n\nf = pd.to_datetime(pd.Series(["2024-03-15", "2024-12-25"]))\nprint(f.dt.year.tolist(), f.dt.month.tolist())\nprint(f.dt.dayofweek.tolist())\nprint(f.dt.day_name().tolist())\nprint(f.dt.strftime("%d/%m/%y").tolist())`,
      salida: "[2024, 2024] [3, 12]\n[4, 2]\n['Friday', 'Wednesday']\n['15/03/24', '25/12/24']",
      notas: ['dayofweek: lunes = 0 … domingo = 6.'],
      lecciones: ['m13-l3', 'm7-l3'],
    },
    {
      id: 'pandas-date-range',
      nombre: 'pd.date_range()',
      grupo: 'Fechas y series de tiempo',
      firma: 'pd.date_range(start, end=None, periods=None, freq="D")',
      resumen: 'Genera una secuencia de fechas consecutivas.',
      parametros: [
        { nombre: 'periods', descripcion: 'Cuántas fechas generar (alternativa a end).', porDefecto: 'None' },
        { nombre: 'freq', descripcion: '"D" día, "W" semana, "h" hora, "MS" inicio de mes…', porDefecto: '"D"' },
      ],
      ejemplo: `import pandas as pd\n\nf = pd.date_range("2024-01-01", periods=4, freq="D")\nprint(f.strftime("%Y-%m-%d").tolist())\nprint(len(pd.date_range("2024-01-01", "2024-01-31")))`,
      salida: "['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04']\n31",
      lecciones: ['m16-l1'],
    },
    {
      id: 'pandas-resample',
      nombre: 'serie.resample()',
      grupo: 'Fechas y series de tiempo',
      firma: 'serie.resample(regla).sum() · .mean() · .count()',
      resumen: 'Agrupa una serie con índice de fechas por periodos (semana, mes…) y los resume.',
      ejemplo: `import pandas as pd\n\nv = pd.Series(range(1, 15), index=pd.date_range("2024-01-01", periods=14, freq="D"))\nprint(v.resample("W").sum().tolist())`,
      salida: '[28, 77]',
      notas: ['Requiere que el índice sea de tipo fecha (DatetimeIndex).', 'Con "W" las semanas terminan en domingo.'],
      lecciones: ['m16-l1'],
    },
    {
      id: 'pandas-rolling',
      nombre: 'serie.rolling()',
      grupo: 'Fechas y series de tiempo',
      firma: 'serie.rolling(window, min_periods=None).mean()',
      resumen: 'Calcula una estadística sobre una ventana móvil (por ejemplo, media móvil de 3 días).',
      parametros: [
        { nombre: 'window', descripcion: 'Tamaño de la ventana (cuántos puntos).' },
        { nombre: 'min_periods', descripcion: 'Mínimo de datos para calcular; por defecto igual a window.', porDefecto: 'window' },
      ],
      ejemplo: `import pandas as pd\n\ns = pd.Series([10, 12, 11, 13, 15])\nprint(s.rolling(3).mean().tolist())`,
      salida: '[nan, nan, 11.0, 12.0, 13.0]',
      notas: ['Los primeros window-1 valores son NaN porque aún no hay suficientes datos.'],
      lecciones: ['m16-l1'],
    },
    {
      id: 'pandas-shift',
      nombre: 'serie.shift()',
      grupo: 'Fechas y series de tiempo',
      firma: 'serie.shift(periodos=1)',
      resumen: 'Desplaza los valores hacia adelante (o atrás con negativos); base de las variables de rezago.',
      ejemplo: `import pandas as pd\n\ns = pd.Series([10, 12, 11, 13])\nprint(s.shift(1).tolist())\nprint(s.shift(-1).tolist())`,
      salida: '[nan, 10.0, 12.0, 11.0]\n[12.0, 11.0, 13.0, nan]',
      relacionadas: ['pandas-diff'],
      lecciones: ['m16-l3'],
    },
    {
      id: 'pandas-diff',
      nombre: 'serie.diff() / pct_change()',
      grupo: 'Fechas y series de tiempo',
      firma: 'serie.diff(periodos=1) · serie.pct_change(periodos=1)',
      resumen: 'diff da la diferencia con el valor anterior; pct_change la variación porcentual (0.2 = 20%).',
      ejemplo: `import pandas as pd\n\ns = pd.Series([100, 120, 90])\nprint(s.diff().tolist())\nprint(s.pct_change().round(3).tolist())`,
      salida: '[nan, 20.0, -30.0]\n[nan, 0.2, -0.25]',
      lecciones: ['m8-l4', 'm21-l1'],
    },
    {
      id: 'pandas-cumsum',
      nombre: 'serie.cumsum() / cumprod() / cummax()',
      grupo: 'Fechas y series de tiempo',
      firma: 'serie.cumsum() · serie.cumprod() · serie.cummax()',
      resumen: 'Acumulados: suma, producto o máximo hasta cada fila.',
      ejemplo: `import pandas as pd\n\nprint(pd.Series([10, 15, 12]).cumsum().tolist())\nprint(pd.Series([1, 3, 2, 5]).cummax().tolist())`,
      salida: '[10, 25, 37]\n[1, 3, 3, 5]',
      lecciones: ['m8-l4'],
    },

    // ───────────────────────── Estadística y resumen ─────────────────────────
    {
      id: 'pandas-stats',
      nombre: 'mean() / median() / sum() / min() / max() / count()',
      grupo: 'Estadística y resumen',
      firma: 'serie.mean() · .median() · .sum() · .min() · .max() · .count()',
      resumen: 'Estadísticas básicas de una columna; ignoran los valores nulos.',
      ejemplo: `${DF}\n\np = df["precio"]\nprint(p.mean(), p.median())\nprint(p.sum(), p.min(), p.max())\nprint(p.count())`,
      salida: '235.0 45.0\n1175.0 15.0 900.0\n5',
      notas: ['Cuando hay valores atípicos la mediana describe mejor lo "típico" que la media.'],
      lecciones: ['m10-l1'],
    },
    {
      id: 'pandas-std',
      nombre: 'std() / var()',
      grupo: 'Estadística y resumen',
      firma: 'serie.std(ddof=1) · serie.var(ddof=1)',
      resumen: 'Desviación estándar y varianza (de muestra por defecto).',
      ejemplo: `import pandas as pd\n\ns = pd.Series([2, 4, 4, 4, 5, 5, 7, 9])\nprint(round(s.std(), 3))\nprint(s.std(ddof=0))`,
      salida: '2.138\n2.0',
      notas: ['pandas usa ddof=1 (muestra); NumPy usa ddof=0 por defecto.'],
      relacionadas: ['numpy-std-var'],
      lecciones: ['m10-l1'],
    },
    {
      id: 'pandas-quantile',
      nombre: 'serie.quantile()',
      grupo: 'Estadística y resumen',
      firma: 'serie.quantile(q=0.5)',
      resumen: 'Valor por debajo del cual queda la fracción q de los datos (0.25 = primer cuartil).',
      ejemplo: `import pandas as pd\n\ns = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])\nprint(s.quantile(0.5))\nq1, q3 = s.quantile(0.25), s.quantile(0.75)\nprint(q1, q3, q3 - q1)`,
      salida: '5.5\n3.25 7.75 4.5',
      notas: ['El rango intercuartílico IQR = Q3 − Q1 sirve para detectar outliers: fuera de [Q1 − 1.5·IQR, Q3 + 1.5·IQR].'],
      relacionadas: ['numpy-percentile'],
      lecciones: ['m10-l2', 'm10-l4'],
    },
    {
      id: 'pandas-mode',
      nombre: 'serie.mode()',
      grupo: 'Estadística y resumen',
      firma: 'serie.mode()',
      resumen: 'Devuelve el valor (o valores) más frecuente.',
      ejemplo: `import pandas as pd\n\nprint(pd.Series([1, 2, 2, 3, 2]).mode().tolist())\nprint(pd.Series(["a", "b", "b"]).mode()[0])`,
      salida: '[2]\nb',
      lecciones: ['m10-l1'],
    },
    {
      id: 'pandas-corr',
      nombre: 'df.corr()',
      grupo: 'Estadística y resumen',
      firma: 'df.corr(method="pearson", numeric_only=False)',
      resumen: 'Matriz de correlación entre columnas numéricas (de -1 a 1).',
      parametros: [
        { nombre: 'method', descripcion: '"pearson" (lineal), "spearman" o "kendall" (por rangos, más robustos a outliers).', porDefecto: '"pearson"' },
        { nombre: 'numeric_only', descripcion: 'True ignora columnas de texto (necesario si el DataFrame tiene texto).', porDefecto: 'False' },
      ],
      ejemplo: `import pandas as pd\n\ndf = pd.DataFrame({"horas": [1, 2, 3, 4, 5], "nota": [2.0, 2.8, 3.1, 4.2, 4.9], "ruido": [5, 1, 4, 2, 3]})\nc = df.corr()\nprint(c.round(2))\nprint(round(df["horas"].corr(df["nota"]), 3))`,
      salida: "       horas  nota  ruido\nhoras   1.00  0.99  -0.30\nnota    0.99  1.00  -0.37\nruido  -0.30 -0.37   1.00\n0.989",
      notas: ['Correlación no implica causalidad. Un valor cercano a 0 puede ocultar una relación no lineal: grafica antes de concluir.'],
      relacionadas: ['numpy-corrcoef'],
      lecciones: ['m10-l3'],
    },
    {
      id: 'pandas-idxmax',
      nombre: 'serie.idxmax() / idxmin()',
      grupo: 'Estadística y resumen',
      firma: 'serie.idxmax() · serie.idxmin()',
      resumen: 'Devuelve la etiqueta (índice) donde está el valor máximo o mínimo.',
      ejemplo: `import pandas as pd\n\nventas = pd.Series({"Norte": 120, "Sur": 340, "Centro": 210})\nprint(ventas.idxmax())\nprint(ventas.idxmin())`,
      salida: 'Sur\nNorte',
      lecciones: ['m21-l3'],
    },
    {
      id: 'pandas-cut',
      nombre: 'pd.cut() / pd.qcut()',
      grupo: 'Estadística y resumen',
      firma: 'pd.cut(serie, bins, labels=None) · pd.qcut(serie, q, labels=None)',
      resumen: 'Convierte números en categorías: cut con rangos que tú defines; qcut con grupos del mismo tamaño.',
      ejemplo: `import pandas as pd\n\nedades = pd.Series([15, 25, 40, 70])\nprint(pd.cut(edades, bins=[0, 18, 60, 120], labels=["menor", "adulto", "mayor"]).tolist())\nprint(pd.qcut(pd.Series(range(1, 9)), q=4, labels=False).tolist())`,
      salida: "['menor', 'adulto', 'adulto', 'mayor']\n[0, 0, 1, 1, 2, 2, 3, 3]",
      lecciones: ['m10-l4'],
    },

    // ───────────────────────── Agrupar y resumir ─────────────────────────
    {
      id: 'pandas-groupby',
      nombre: 'df.groupby()',
      grupo: 'Agrupar y resumir',
      firma: 'df.groupby(by, as_index=True)[columna].funcion()',
      resumen: 'Divide las filas en grupos según una columna y calcula un resumen por cada grupo.',
      parametros: [
        { nombre: 'by', descripcion: 'Columna (o lista de columnas) que define los grupos.' },
        { nombre: 'as_index', descripcion: 'Si es False, los grupos quedan como columna normal en lugar de índice.', porDefecto: 'True' },
      ],
      ejemplo: `${DF}\n\ndf["ingresos"] = df["cantidad"] * df["precio"]\nprint(df.groupby("categoria")["ingresos"].sum())\nprint(df.groupby("ciudad")["cantidad"].mean())\nprint(df.groupby(["categoria", "ciudad"])["ingresos"].sum().reset_index())`,
      salida: "categoria\nAccesorios      165.0\nElectronica    1300.0\nName: ingresos, dtype: float64\nciudad\nBogota    2.5\nCali      5.0\nLima      1.0\nName: cantidad, dtype: float64\n     categoria  ciudad  ingresos\n0   Accesorios  Bogota      45.0\n1   Accesorios    Cali      75.0\n2   Accesorios    Lima      45.0\n3  Electronica  Bogota     400.0\n4  Electronica    Lima     900.0",
      notas: ['Piénsalo como "separar → aplicar → combinar". Es el equivalente de GROUP BY en SQL.'],
      relacionadas: ['pandas-agg', 'sql-group-by'],
      lecciones: ['m8-l1'],
    },
    {
      id: 'pandas-agg',
      nombre: 'groupby().agg()',
      grupo: 'Agrupar y resumir',
      firma: 'df.groupby("col").agg(nombre=("columna", "funcion"), ...)',
      resumen: 'Calcula varias estadísticas a la vez (y con nombre propio) por grupo.',
      ejemplo: `${DF}\n\nr = df.groupby("categoria").agg(\n    unidades=("cantidad", "sum"),\n    precio_medio=("precio", "mean"),\n    productos=("producto", "nunique"),\n)\nprint(r)`,
      salida: "             unidades  precio_medio  productos\ncategoria                                     \nAccesorios          9          25.0          2\nElectronica         3         550.0          2",
      notas: ['Funciones disponibles como texto: "sum", "mean", "median", "min", "max", "count", "nunique", "std", "first", "last".'],
      lecciones: ['m8-l2'],
    },
    {
      id: 'pandas-transform',
      nombre: 'groupby().transform()',
      grupo: 'Agrupar y resumir',
      firma: 'df.groupby("col")["x"].transform(funcion)',
      resumen: 'Calcula un resumen por grupo pero lo devuelve con el mismo tamaño que el original (una fila por fila).',
      ejemplo: `${DF}\n\ndf["total_cat"] = df.groupby("categoria")["cantidad"].transform("sum")\ndf["peso"] = (df["cantidad"] / df["total_cat"]).round(2)\nprint(df[["producto", "categoria", "peso"]])`,
      salida: "  producto    categoria  peso\n0    Mouse   Accesorios  0.33\n1  Teclado   Accesorios  0.11\n2  Monitor  Electronica  0.67\n3    Mouse   Accesorios  0.56\n4   Laptop  Electronica  0.33",
      lecciones: ['m8-l2'],
    },
    {
      id: 'pandas-pivot-table',
      nombre: 'df.pivot_table()',
      grupo: 'Agrupar y resumir',
      firma: 'df.pivot_table(values, index, columns, aggfunc="mean", fill_value=None, margins=False)',
      resumen: 'Tabla dinámica: filas y columnas de categorías con un valor resumido en cada cruce.',
      parametros: [
        { nombre: 'values', descripcion: 'Columna que se resume.' },
        { nombre: 'index', descripcion: 'Columna(s) que forman las filas.' },
        { nombre: 'columns', descripcion: 'Columna(s) que forman las columnas.', porDefecto: 'None' },
        { nombre: 'aggfunc', descripcion: 'Función de resumen: "sum", "mean", "count"…', porDefecto: '"mean"' },
        { nombre: 'fill_value', descripcion: 'Valor para los cruces sin datos.', porDefecto: 'None' },
        { nombre: 'margins', descripcion: 'Si es True, agrega fila y columna de totales (All).', porDefecto: 'False' },
      ],
      ejemplo: `${DF}\n\nt = df.pivot_table(values="cantidad", index="categoria", columns="ciudad", aggfunc="sum", fill_value=0, margins=True)\nprint(t)`,
      salida: "ciudad       Bogota  Cali  Lima  All\ncategoria                           \nAccesorios        3     5     1    9\nElectronica       2     0     1    3\nAll               5     5     2   12",
      lecciones: ['m8-l3'],
    },
    {
      id: 'pandas-crosstab',
      nombre: 'pd.crosstab()',
      grupo: 'Agrupar y resumir',
      firma: 'pd.crosstab(index, columns, normalize=False)',
      resumen: 'Tabla de frecuencias: cuenta cuántas filas hay en cada cruce de dos categorías.',
      ejemplo: `${DF}\n\nprint(pd.crosstab(df["categoria"], df["ciudad"]))`,
      salida: "ciudad       Bogota  Cali  Lima\ncategoria                      \nAccesorios        1     1     1\nElectronica       1     0     1",
      relacionadas: ['pandas-pivot-table'],
      lecciones: ['m8-l3'],
    },

    // ───────────────────────── Combinar tablas ─────────────────────────
    {
      id: 'pandas-concat',
      nombre: 'pd.concat()',
      grupo: 'Combinar tablas',
      firma: 'pd.concat([df1, df2], axis=0, ignore_index=False)',
      resumen: 'Une tablas apilándolas (axis=0, más filas) o pegándolas lado a lado (axis=1, más columnas).',
      parametros: [
        { nombre: 'axis', descripcion: '0 apila filas; 1 pega columnas.', porDefecto: '0' },
        { nombre: 'ignore_index', descripcion: 'True renumera el índice 0, 1, 2…', porDefecto: 'False' },
      ],
      ejemplo: `import pandas as pd\n\nenero = pd.DataFrame({"producto": ["Mouse"], "ventas": [10]})\nfebrero = pd.DataFrame({"producto": ["Teclado"], "ventas": [7]})\ntodo = pd.concat([enero, febrero], ignore_index=True)\nprint(todo)`,
      salida: "  producto  ventas\n0    Mouse      10\n1  Teclado       7",
      relacionadas: ['pandas-merge'],
      lecciones: ['m7-l4'],
    },
    {
      id: 'pandas-merge',
      nombre: 'pd.merge() / df.merge()',
      grupo: 'Combinar tablas',
      firma: 'df1.merge(df2, how="inner", on=None, left_on=None, right_on=None, suffixes=("_x", "_y"))',
      resumen: 'Une dos tablas por una columna en común (como un JOIN de SQL).',
      parametros: [
        { nombre: 'how', descripcion: '"inner" solo coincidencias; "left" conserva todas las de la izquierda; "right"; "outer" todas.', porDefecto: '"inner"' },
        { nombre: 'on', descripcion: 'Columna(s) con el mismo nombre en ambas tablas.', porDefecto: 'None' },
        { nombre: 'left_on / right_on', descripcion: 'Columnas de unión cuando se llaman distinto en cada tabla.', porDefecto: 'None' },
        { nombre: 'suffixes', descripcion: 'Sufijos para columnas repetidas que no son la clave.', porDefecto: '("_x", "_y")' },
      ],
      ejemplo: `import pandas as pd\n\nclientes = pd.DataFrame({"id": [1, 2, 3], "nombre": ["Ana", "Luis", "Marta"]})\npedidos = pd.DataFrame({"cliente_id": [1, 1, 3], "total": [50, 30, 20]})\ninterno = clientes.merge(pedidos, left_on="id", right_on="cliente_id")\nizquierda = clientes.merge(pedidos, left_on="id", right_on="cliente_id", how="left")\nprint(len(interno), len(izquierda))\nprint(izquierda[["nombre", "total"]])`,
      salida: "3 4\n  nombre  total\n0    Ana   50.0\n1    Ana   30.0\n2   Luis    NaN\n3  Marta   20.0",
      notas: ['Un merge "left" deja NaN en las columnas de la derecha cuando no hay coincidencia (por ejemplo, clientes sin pedidos).'],
      relacionadas: ['sql-inner-join', 'pandas-concat'],
      lecciones: ['m7-l4'],
    },
    {
      id: 'pandas-melt',
      nombre: 'df.melt() / df.pivot()',
      grupo: 'Combinar tablas',
      firma: 'df.melt(id_vars, value_vars, var_name, value_name) · df.pivot(index, columns, values)',
      resumen: 'melt pasa de formato ancho a largo (varias columnas → una); pivot hace lo contrario.',
      ejemplo: `import pandas as pd\n\nancho = pd.DataFrame({"producto": ["A", "B"], "ene": [10, 20], "feb": [12, 22]})\nlargo = ancho.melt(id_vars="producto", var_name="mes", value_name="ventas")\nprint(largo)\nprint(largo.pivot(index="producto", columns="mes", values="ventas"))`,
      salida: "  producto  mes  ventas\n0        A  ene      10\n1        B  ene      20\n2        A  feb      12\n3        B  feb      22\nmes       ene  feb\nproducto          \nA          10   12\nB          20   22",
      lecciones: ['m8-l3'],
    },
  ],
}
