import type { ColeccionRef } from './tipos'

export const pythonRef: ColeccionRef = {
  id: 'python',
  titulo: 'Python básico',
  descripcion: 'Funciones integradas, métodos de texto, listas, diccionarios, control de flujo, errores, archivos y módulos de la biblioteca estándar.',
  icono: '🐍',
  lenguaje: 'python',
  entradas: [
    // ───────────────────────── Funciones integradas ─────────────────────────
    {
      id: 'python-print',
      nombre: 'print()',
      grupo: 'Funciones integradas',
      firma: 'print(*objetos, sep=" ", end="\\n")',
      resumen: 'Muestra valores en pantalla (la salida estándar).',
      parametros: [
        { nombre: '*objetos', descripcion: 'Uno o más valores a mostrar; se convierten a texto.' },
        { nombre: 'sep', descripcion: 'Texto que se pone entre los valores.', porDefecto: '" " (un espacio)' },
        { nombre: 'end', descripcion: 'Texto que se pone al final.', porDefecto: '"\\n" (salto de línea)' },
      ],
      ejemplo: `print("Total:", 42)\nprint("a", "b", "c", sep="-")\nprint("sin salto", end="!")\nprint()`,
      salida: `Total: 42\na-b-c\nsin salto!`,
      notas: ['Es la forma más simple de ver qué contiene una variable mientras depuras.'],
      lecciones: ['m1-l4'],
    },
    {
      id: 'python-input',
      nombre: 'input()',
      grupo: 'Funciones integradas',
      firma: 'input(mensaje="")',
      resumen: 'Pide un texto al usuario por teclado y lo devuelve como str.',
      parametros: [{ nombre: 'mensaje', descripcion: 'Texto que se muestra antes de esperar la respuesta.', porDefecto: '""' }],
      ejemplo: `# input() siempre devuelve texto; conviértelo si necesitas un número.\nrespuesta = "25"            # simula lo que escribiría el usuario\nedad = int(respuesta)\nprint(edad + 1)`,
      salida: '26',
      notas: ['Siempre devuelve un str: usa int() o float() para convertirlo.', 'En los ejercicios del navegador no hay teclado, por eso aquí se simula la respuesta.'],
      relacionadas: ['python-int', 'python-float'],
      lecciones: ['m1-l4'],
    },
    {
      id: 'python-len',
      nombre: 'len()',
      grupo: 'Funciones integradas',
      firma: 'len(objeto)',
      resumen: 'Cuenta los elementos de una lista, texto, diccionario, conjunto o tupla.',
      ejemplo: `print(len([10, 20, 30]))\nprint(len("hola"))\nprint(len({"a": 1, "b": 2}))`,
      salida: '3\n4\n2',
      lecciones: ['m1-l2', 'm3-l1'],
    },
    {
      id: 'python-type',
      nombre: 'type()',
      grupo: 'Funciones integradas',
      firma: 'type(objeto)',
      resumen: 'Devuelve el tipo de un valor (int, float, str, list…).',
      ejemplo: `print(type(5))\nprint(type(5.0))\nprint(type("5"))\nprint(type([5]))`,
      salida: "<class 'int'>\n<class 'float'>\n<class 'str'>\n<class 'list'>",
      relacionadas: ['python-isinstance'],
      lecciones: ['m1-l1'],
    },
    {
      id: 'python-isinstance',
      nombre: 'isinstance()',
      grupo: 'Funciones integradas',
      firma: 'isinstance(objeto, tipo)',
      resumen: 'Comprueba si un valor es de un tipo dado (True o False).',
      parametros: [
        { nombre: 'objeto', descripcion: 'El valor a revisar.' },
        { nombre: 'tipo', descripcion: 'Un tipo, o una tupla de tipos: (int, float).' },
      ],
      ejemplo: `print(isinstance(5, int))\nprint(isinstance("5", int))\nprint(isinstance(3.14, (int, float)))`,
      salida: 'True\nFalse\nTrue',
      lecciones: ['m1-l1'],
    },
    {
      id: 'python-int',
      nombre: 'int()',
      grupo: 'Funciones integradas',
      firma: 'int(valor, base=10)',
      resumen: 'Convierte un valor a número entero (trunca los decimales).',
      parametros: [
        { nombre: 'valor', descripcion: 'Texto o número a convertir.' },
        { nombre: 'base', descripcion: 'Base numérica cuando el valor es texto (2 para binario, 16 para hexadecimal…).', porDefecto: '10' },
      ],
      ejemplo: `print(int("42"))\nprint(int(7.9))\nprint(int("ff", 16))`,
      salida: '42\n7\n255',
      notas: ['int(7.9) da 7: trunca, no redondea. Para redondear usa round().', 'int("3.5") falla con ValueError: convierte primero a float.'],
      relacionadas: ['python-float', 'python-round'],
      lecciones: ['m1-l1'],
    },
    {
      id: 'python-float',
      nombre: 'float()',
      grupo: 'Funciones integradas',
      firma: 'float(valor)',
      resumen: 'Convierte un valor a número decimal.',
      ejemplo: `print(float("3.5"))\nprint(float(2))\nprint(0.1 + 0.2 == 0.3)\nprint(round(0.1 + 0.2, 2) == 0.3)`,
      salida: '3.5\n2.0\nFalse\nTrue',
      notas: ['Los decimales binarios tienen pequeños errores de precisión: no compares floats con ==; redondea o usa math.isclose.'],
      relacionadas: ['python-int', 'python-round'],
      lecciones: ['m1-l1', 'm1-l3'],
    },
    {
      id: 'python-str',
      nombre: 'str()',
      grupo: 'Funciones integradas',
      firma: 'str(valor)',
      resumen: 'Convierte cualquier valor a texto.',
      ejemplo: `edad = 30\nmensaje = "Tengo " + str(edad) + " años"\nprint(mensaje)`,
      salida: 'Tengo 30 años',
      notas: ['Para mezclar texto y números es más cómodo usar f-strings: f"Tengo {edad} años".'],
      relacionadas: ['python-fstring'],
      lecciones: ['m1-l2'],
    },
    {
      id: 'python-bool',
      nombre: 'bool()',
      grupo: 'Funciones integradas',
      firma: 'bool(valor)',
      resumen: 'Convierte un valor a True o False según si es "vacío" o no.',
      descripcion: 'Son falsos (False): 0, 0.0, "" (texto vacío), [] , {}, set(), None. Todo lo demás es verdadero.',
      ejemplo: `print(bool(0), bool(5))\nprint(bool(""), bool("hola"))\nprint(bool([]), bool([0]))`,
      salida: 'False True\nFalse True\nFalse True',
      lecciones: ['m1-l3', 'm2-l1'],
    },
    {
      id: 'python-round',
      nombre: 'round()',
      grupo: 'Funciones integradas',
      firma: 'round(numero, ndigits=None)',
      resumen: 'Redondea un número a cierta cantidad de decimales.',
      parametros: [
        { nombre: 'numero', descripcion: 'El número a redondear.' },
        { nombre: 'ndigits', descripcion: 'Cantidad de decimales. Sin este parámetro devuelve un entero.', porDefecto: 'None' },
      ],
      ejemplo: `print(round(3.14159, 2))\nprint(round(2.5))\nprint(round(3.5))\nprint(round(1234, -2))`,
      salida: '3.14\n2\n4\n1200',
      notas: ['Python redondea los .5 al entero par más cercano (2.5 → 2, 3.5 → 4).'],
      lecciones: ['m1-l3'],
    },
    {
      id: 'python-abs',
      nombre: 'abs()',
      grupo: 'Funciones integradas',
      firma: 'abs(numero)',
      resumen: 'Devuelve el valor absoluto (sin signo) de un número.',
      ejemplo: `print(abs(-7))\nprint(abs(3.5))`,
      salida: '7\n3.5',
      lecciones: ['m1-l3'],
    },
    {
      id: 'python-sum',
      nombre: 'sum()',
      grupo: 'Funciones integradas',
      firma: 'sum(iterable, start=0)',
      resumen: 'Suma todos los elementos numéricos de una colección.',
      parametros: [
        { nombre: 'iterable', descripcion: 'Lista, tupla, conjunto o cualquier secuencia de números.' },
        { nombre: 'start', descripcion: 'Valor inicial al que se le suma todo.', porDefecto: '0' },
      ],
      ejemplo: `notas = [4.5, 3.0, 5.0]\nprint(sum(notas))\nprint(sum(notas) / len(notas))`,
      salida: '12.5\n4.166666666666667',
      relacionadas: ['python-len', 'python-min', 'python-max'],
      lecciones: ['m2-l2'],
    },
    {
      id: 'python-min',
      nombre: 'min()',
      grupo: 'Funciones integradas',
      firma: 'min(iterable, key=None)',
      resumen: 'Devuelve el elemento más pequeño de una colección.',
      parametros: [{ nombre: 'key', descripcion: 'Función que indica con qué valor comparar cada elemento.', porDefecto: 'None' }],
      ejemplo: `print(min([7, 2, 9]))\nprint(min(["pera", "uva", "manzana"], key=len))`,
      salida: '2\nuva',
      relacionadas: ['python-max'],
      lecciones: ['m3-l1'],
    },
    {
      id: 'python-max',
      nombre: 'max()',
      grupo: 'Funciones integradas',
      firma: 'max(iterable, key=None)',
      resumen: 'Devuelve el elemento más grande de una colección.',
      parametros: [{ nombre: 'key', descripcion: 'Función que indica con qué valor comparar cada elemento.', porDefecto: 'None' }],
      ejemplo: `ventas = {"Ana": 120, "Luis": 340, "Marta": 210}\nprint(max([7, 2, 9]))\nprint(max(ventas, key=ventas.get))`,
      salida: '9\nLuis',
      relacionadas: ['python-min'],
      lecciones: ['m3-l1', 'm3-l2'],
    },
    {
      id: 'python-range',
      nombre: 'range()',
      grupo: 'Funciones integradas',
      firma: 'range(inicio=0, fin, paso=1)',
      resumen: 'Genera una secuencia de enteros; el valor "fin" no se incluye.',
      parametros: [
        { nombre: 'inicio', descripcion: 'Primer número (incluido).', porDefecto: '0' },
        { nombre: 'fin', descripcion: 'Donde se detiene (excluido).' },
        { nombre: 'paso', descripcion: 'Cuánto se avanza entre números; puede ser negativo.', porDefecto: '1' },
      ],
      ejemplo: `print(list(range(5)))\nprint(list(range(2, 10, 3)))\nprint(list(range(5, 0, -2)))`,
      salida: '[0, 1, 2, 3, 4]\n[2, 5, 8]\n[5, 3, 1]',
      lecciones: ['m2-l2'],
    },
    {
      id: 'python-enumerate',
      nombre: 'enumerate()',
      grupo: 'Funciones integradas',
      firma: 'enumerate(iterable, start=0)',
      resumen: 'Recorre una colección entregando (posición, elemento).',
      parametros: [{ nombre: 'start', descripcion: 'Número desde el que empieza la cuenta.', porDefecto: '0' }],
      ejemplo: `for i, fruta in enumerate(["pera", "uva"], start=1):\n    print(i, fruta)`,
      salida: '1 pera\n2 uva',
      relacionadas: ['python-zip'],
      lecciones: ['m2-l2'],
    },
    {
      id: 'python-zip',
      nombre: 'zip()',
      grupo: 'Funciones integradas',
      firma: 'zip(*iterables)',
      resumen: 'Junta varias listas en pares (o tuplas) elemento a elemento.',
      ejemplo: `nombres = ["Ana", "Luis"]\nedades = [30, 25]\nfor n, e in zip(nombres, edades):\n    print(n, e)\nprint(dict(zip(nombres, edades)))`,
      salida: "Ana 30\nLuis 25\n{'Ana': 30, 'Luis': 25}",
      notas: ['Se detiene cuando se acaba la lista más corta.'],
      relacionadas: ['python-enumerate'],
      lecciones: ['m3-l2'],
    },
    {
      id: 'python-sorted',
      nombre: 'sorted()',
      grupo: 'Funciones integradas',
      firma: 'sorted(iterable, key=None, reverse=False)',
      resumen: 'Devuelve una lista nueva ordenada, sin modificar la original.',
      parametros: [
        { nombre: 'key', descripcion: 'Función que calcula la clave de ordenación de cada elemento.', porDefecto: 'None' },
        { nombre: 'reverse', descripcion: 'Si es True, ordena de mayor a menor.', porDefecto: 'False' },
      ],
      ejemplo: `numeros = [3, 1, 2]\nprint(sorted(numeros))\nprint(sorted(numeros, reverse=True))\nprint(sorted(["pera", "uva", "manzana"], key=len))\nprint(numeros)`,
      salida: "[1, 2, 3]\n[3, 2, 1]\n['uva', 'pera', 'manzana']\n[3, 1, 2]",
      notas: ['A diferencia de lista.sort(), no cambia la lista original.'],
      relacionadas: ['python-list-sort'],
      lecciones: ['m3-l1'],
    },
    {
      id: 'python-reversed',
      nombre: 'reversed()',
      grupo: 'Funciones integradas',
      firma: 'reversed(secuencia)',
      resumen: 'Recorre una secuencia de atrás hacia adelante.',
      ejemplo: `print(list(reversed([1, 2, 3])))\nprint("".join(reversed("hola")))`,
      salida: '[3, 2, 1]\naloh',
      lecciones: ['m3-l1'],
    },
    {
      id: 'python-any-all',
      nombre: 'any() / all()',
      grupo: 'Funciones integradas',
      firma: 'any(iterable) · all(iterable)',
      resumen: 'any: ¿alguno es verdadero? all: ¿todos son verdaderos?',
      ejemplo: `edades = [15, 22, 31]\nprint(any(e >= 18 for e in edades))\nprint(all(e >= 18 for e in edades))`,
      salida: 'True\nFalse',
      lecciones: ['m2-l4'],
    },
    {
      id: 'python-map-filter',
      nombre: 'map() / filter()',
      grupo: 'Funciones integradas',
      firma: 'map(funcion, iterable) · filter(funcion, iterable)',
      resumen: 'map transforma cada elemento; filter se queda con los que cumplen una condición.',
      ejemplo: `numeros = [1, 2, 3, 4]\nprint(list(map(lambda n: n * n, numeros)))\nprint(list(filter(lambda n: n % 2 == 0, numeros)))`,
      salida: '[1, 4, 9, 16]\n[2, 4]',
      notas: ['Las comprensiones de listas hacen lo mismo y suelen leerse mejor: [n * n for n in numeros].'],
      relacionadas: ['python-comprehension', 'python-lambda'],
      lecciones: ['m4-l3'],
    },

    // ───────────────────────── Texto (str) ─────────────────────────
    {
      id: 'python-fstring',
      nombre: 'f-string',
      grupo: 'Texto (str)',
      firma: 'f"texto {expresion:formato}"',
      resumen: 'Inserta valores dentro de un texto; permite dar formato a números.',
      descripcion: 'Las llaves {} evalúan cualquier expresión. Después de ":" se indica el formato: .2f (2 decimales), , (separador de miles), % (porcentaje), > (alinear).',
      ejemplo: `nombre = "Ana"\ntotal = 1234.5678\nprint(f"Hola {nombre}")\nprint(f"Total: {total:,.2f}")\nprint(f"Avance: {0.256:.1%}")`,
      salida: 'Hola Ana\nTotal: 1,234.57\nAvance: 25.6%',
      lecciones: ['m1-l2'],
    },
    {
      id: 'python-str-upper',
      nombre: 'str.upper() / lower() / title()',
      grupo: 'Texto (str)',
      firma: 'texto.upper() · texto.lower() · texto.title() · texto.capitalize()',
      resumen: 'Cambia mayúsculas y minúsculas de un texto.',
      ejemplo: `t = "python para DATOS"\nprint(t.upper())\nprint(t.lower())\nprint(t.title())\nprint(t.capitalize())`,
      salida: 'PYTHON PARA DATOS\npython para datos\nPython Para Datos\nPython para datos',
      notas: ['Los métodos de str devuelven un texto nuevo; no modifican el original.', 'lower() es útil para comparar textos sin importar mayúsculas.'],
      lecciones: ['m1-l2'],
    },
    {
      id: 'python-str-strip',
      nombre: 'str.strip()',
      grupo: 'Texto (str)',
      firma: 'texto.strip(caracteres=None)',
      resumen: 'Quita espacios (o los caracteres indicados) del inicio y del final.',
      parametros: [{ nombre: 'caracteres', descripcion: 'Conjunto de caracteres a quitar en los extremos. Sin indicar, quita espacios y saltos de línea.', porDefecto: 'None' }],
      ejemplo: `print("[" + "  hola  ".strip() + "]")\nprint("[" + "  hola  ".lstrip() + "]")\nprint("[" + "  hola  ".rstrip() + "]")\nprint("***hola***".strip("*"))`,
      salida: '[hola]\n[hola  ]\n[  hola]\nhola',
      notas: ['lstrip quita solo por la izquierda y rstrip solo por la derecha.'],
      lecciones: ['m1-l2'],
    },
    {
      id: 'python-str-split',
      nombre: 'str.split()',
      grupo: 'Texto (str)',
      firma: 'texto.split(sep=None, maxsplit=-1)',
      resumen: 'Divide un texto en una lista de partes.',
      parametros: [
        { nombre: 'sep', descripcion: 'Texto por el que se corta. Sin indicar, corta por cualquier espacio en blanco.', porDefecto: 'None' },
        { nombre: 'maxsplit', descripcion: 'Máximo de cortes (-1 = sin límite).', porDefecto: '-1' },
      ],
      ejemplo: `print("a b  c".split())\nprint("ana,luis,marta".split(","))\nprint("2024-01-15".split("-", 1))`,
      salida: "['a', 'b', 'c']\n['ana', 'luis', 'marta']\n['2024', '01-15']",
      relacionadas: ['python-str-join'],
      lecciones: ['m1-l2'],
    },
    {
      id: 'python-str-join',
      nombre: 'str.join()',
      grupo: 'Texto (str)',
      firma: 'separador.join(iterable_de_textos)',
      resumen: 'Une una lista de textos usando el separador indicado.',
      ejemplo: `palabras = ["datos", "con", "Python"]\nprint(" ".join(palabras))\nprint("-".join(palabras))\nprint(", ".join(str(n) for n in [1, 2, 3]))`,
      salida: 'datos con Python\ndatos-con-Python\n1, 2, 3',
      notas: ['Todos los elementos deben ser texto: convierte los números con str().'],
      relacionadas: ['python-str-split'],
      lecciones: ['m1-l2'],
    },
    {
      id: 'python-str-replace',
      nombre: 'str.replace()',
      grupo: 'Texto (str)',
      firma: 'texto.replace(viejo, nuevo, cuenta=-1)',
      resumen: 'Reemplaza todas las apariciones de un fragmento por otro.',
      parametros: [
        { nombre: 'viejo', descripcion: 'Fragmento a buscar.' },
        { nombre: 'nuevo', descripcion: 'Fragmento que lo sustituye.' },
        { nombre: 'cuenta', descripcion: 'Máximo de reemplazos (-1 = todos).', porDefecto: '-1' },
      ],
      ejemplo: `print("a-b-c".replace("-", "_"))\nprint("aaaa".replace("a", "b", 2))`,
      salida: 'a_b_c\nbbaa',
      lecciones: ['m1-l2'],
    },
    {
      id: 'python-str-find',
      nombre: 'str.find() / in / startswith() / endswith()',
      grupo: 'Texto (str)',
      firma: 'texto.find(sub) · sub in texto · texto.startswith(pref) · texto.endswith(suf)',
      resumen: 'Busca fragmentos dentro de un texto.',
      descripcion: 'find devuelve la posición de la primera aparición (o -1 si no está). "in" responde True/False. startswith y endswith revisan el inicio y el final.',
      ejemplo: `t = "reporte_2024.csv"\nprint(t.find("2024"))\nprint("2024" in t)\nprint(t.startswith("reporte"))\nprint(t.endswith(".csv"))`,
      salida: '8\nTrue\nTrue\nTrue',
      lecciones: ['m1-l2'],
    },
    {
      id: 'python-str-count',
      nombre: 'str.count()',
      grupo: 'Texto (str)',
      firma: 'texto.count(sub)',
      resumen: 'Cuenta cuántas veces aparece un fragmento (sin solaparse).',
      ejemplo: `print("banana".count("a"))\nprint("banana".count("an"))`,
      salida: '3\n2',
      lecciones: ['m1-l2'],
    },
    {
      id: 'python-str-isdigit',
      nombre: 'str.isdigit() / isalpha()',
      grupo: 'Texto (str)',
      firma: 'texto.isdigit() · texto.isalpha() · texto.isalnum()',
      resumen: 'Comprueba si un texto contiene solo dígitos, solo letras o ambos.',
      ejemplo: `print("2024".isdigit())\nprint("abc".isalpha())\nprint("abc123".isalnum())\nprint("12.5".isdigit())`,
      salida: 'True\nTrue\nTrue\nFalse',
      notas: ['"12.5".isdigit() es False por el punto: para decimales usa try/except con float().'],
      lecciones: ['m1-l4'],
    },

    // ───────────────────────── Listas ─────────────────────────
    {
      id: 'python-list-indexing',
      nombre: 'lista[i] y slicing',
      grupo: 'Listas',
      firma: 'lista[i] · lista[inicio:fin:paso]',
      resumen: 'Accede a un elemento por posición o a un tramo de la lista.',
      descripcion: 'Las posiciones empiezan en 0; las negativas cuentan desde el final (-1 es el último). En un slice el índice "fin" no se incluye.',
      ejemplo: `n = [10, 20, 30, 40, 50]\nprint(n[0], n[-1])\nprint(n[1:3])\nprint(n[:2])\nprint(n[::2])\nprint(n[::-1])`,
      salida: '10 50\n[20, 30]\n[10, 20]\n[10, 30, 50]\n[50, 40, 30, 20, 10]',
      lecciones: ['m3-l1'],
    },
    {
      id: 'python-list-append',
      nombre: 'lista.append()',
      grupo: 'Listas',
      firma: 'lista.append(elemento)',
      resumen: 'Agrega un elemento al final de la lista.',
      ejemplo: `frutas = ["pera"]\nfrutas.append("uva")\nprint(frutas)`,
      salida: "['pera', 'uva']",
      notas: ['Modifica la lista y devuelve None: no hagas lista = lista.append(x).'],
      relacionadas: ['python-list-extend', 'python-list-insert'],
      lecciones: ['m3-l1'],
    },
    {
      id: 'python-list-extend',
      nombre: 'lista.extend()',
      grupo: 'Listas',
      firma: 'lista.extend(iterable)',
      resumen: 'Agrega todos los elementos de otra colección al final.',
      ejemplo: `a = [1, 2]\na.extend([3, 4])\nprint(a)\na.append([5, 6])\nprint(a)`,
      salida: '[1, 2, 3, 4]\n[1, 2, 3, 4, [5, 6]]',
      notas: ['append añade UN elemento (aunque sea una lista); extend añade cada elemento por separado.'],
      relacionadas: ['python-list-append'],
      lecciones: ['m3-l1'],
    },
    {
      id: 'python-list-insert',
      nombre: 'lista.insert()',
      grupo: 'Listas',
      firma: 'lista.insert(posicion, elemento)',
      resumen: 'Inserta un elemento en una posición, desplazando los demás.',
      ejemplo: `n = [1, 3]\nn.insert(1, 2)\nprint(n)`,
      salida: '[1, 2, 3]',
      lecciones: ['m3-l1'],
    },
    {
      id: 'python-list-remove',
      nombre: 'lista.remove() / pop() / del',
      grupo: 'Listas',
      firma: 'lista.remove(valor) · lista.pop(posicion=-1) · del lista[i]',
      resumen: 'Quita elementos: por valor (remove), por posición devolviéndolo (pop) o con del.',
      ejemplo: `n = [10, 20, 30, 20]\nn.remove(20)\nprint(n)\nultimo = n.pop()\nprint(ultimo, n)\ndel n[0]\nprint(n)`,
      salida: '[10, 30, 20]\n20 [10, 30]\n[30]',
      notas: ['remove quita solo la primera coincidencia y falla con ValueError si el valor no está.'],
      lecciones: ['m3-l1'],
    },
    {
      id: 'python-list-sort',
      nombre: 'lista.sort()',
      grupo: 'Listas',
      firma: 'lista.sort(key=None, reverse=False)',
      resumen: 'Ordena la lista en el lugar (modifica la original).',
      parametros: [
        { nombre: 'key', descripcion: 'Función que calcula la clave de ordenación.', porDefecto: 'None' },
        { nombre: 'reverse', descripcion: 'True para orden descendente.', porDefecto: 'False' },
      ],
      ejemplo: `n = [3, 1, 2]\nn.sort()\nprint(n)\nn.sort(reverse=True)\nprint(n)`,
      salida: '[1, 2, 3]\n[3, 2, 1]',
      notas: ['Devuelve None. Si necesitas conservar la original, usa sorted().'],
      relacionadas: ['python-sorted'],
      lecciones: ['m3-l1'],
    },
    {
      id: 'python-list-index-count',
      nombre: 'lista.index() / count()',
      grupo: 'Listas',
      firma: 'lista.index(valor) · lista.count(valor)',
      resumen: 'index da la posición de la primera aparición; count cuenta cuántas veces aparece.',
      ejemplo: `n = [5, 7, 5, 9]\nprint(n.index(7))\nprint(n.count(5))`,
      salida: '1\n2',
      lecciones: ['m3-l1'],
    },
    {
      id: 'python-comprehension',
      nombre: 'Comprensión de listas',
      grupo: 'Listas',
      firma: '[expresion for x in iterable if condicion]',
      resumen: 'Crea una lista nueva transformando y/o filtrando otra, en una sola línea.',
      ejemplo: `numeros = [1, 2, 3, 4, 5, 6]\ncuadrados = [n * n for n in numeros]\npares = [n for n in numeros if n % 2 == 0]\netiquetas = ["par" if n % 2 == 0 else "impar" for n in numeros]\nprint(cuadrados)\nprint(pares)\nprint(etiquetas[:3])`,
      salida: "[1, 4, 9, 16, 25, 36]\n[2, 4, 6]\n['impar', 'par', 'impar']",
      notas: ['También existen para diccionarios {k: v for ...} y conjuntos {x for ...}.'],
      lecciones: ['m2-l4'],
    },

    // ───────────────────────── Diccionarios, tuplas y conjuntos ─────────────────────────
    {
      id: 'python-dict-basico',
      nombre: 'diccionario[clave]',
      grupo: 'Diccionarios, tuplas y conjuntos',
      firma: 'd = {clave: valor}; d[clave]; d[clave] = valor',
      resumen: 'Guarda pares clave → valor; se lee y se escribe por clave.',
      ejemplo: `precios = {"mouse": 15, "teclado": 45}\nprecios["monitor"] = 200\nprint(precios["mouse"])\nprint(precios)\nprint("teclado" in precios)`,
      salida: "15\n{'mouse': 15, 'teclado': 45, 'monitor': 200}\nTrue",
      notas: ['Leer una clave que no existe lanza KeyError: usa .get() si puede faltar.'],
      relacionadas: ['python-dict-get'],
      lecciones: ['m3-l2'],
    },
    {
      id: 'python-dict-get',
      nombre: 'dict.get()',
      grupo: 'Diccionarios, tuplas y conjuntos',
      firma: 'd.get(clave, por_defecto=None)',
      resumen: 'Lee un valor sin error si la clave no existe: devuelve un valor por defecto.',
      ejemplo: `stock = {"mouse": 10}\nprint(stock.get("mouse"))\nprint(stock.get("teclado"))\nprint(stock.get("teclado", 0))`,
      salida: '10\nNone\n0',
      lecciones: ['m3-l2'],
    },
    {
      id: 'python-dict-views',
      nombre: 'dict.keys() / values() / items()',
      grupo: 'Diccionarios, tuplas y conjuntos',
      firma: 'd.keys() · d.values() · d.items()',
      resumen: 'Dan las claves, los valores o los pares (clave, valor) para recorrerlos.',
      ejemplo: `notas = {"Ana": 4.5, "Luis": 3.8}\nprint(list(notas.keys()))\nprint(list(notas.values()))\nfor nombre, nota in notas.items():\n    print(nombre, nota)`,
      salida: "['Ana', 'Luis']\n[4.5, 3.8]\nAna 4.5\nLuis 3.8",
      lecciones: ['m3-l2'],
    },
    {
      id: 'python-dict-update',
      nombre: 'dict.update() / pop() / setdefault()',
      grupo: 'Diccionarios, tuplas y conjuntos',
      firma: 'd.update(otro) · d.pop(clave, defecto) · d.setdefault(clave, valor)',
      resumen: 'Combina diccionarios, quita una clave devolviendo su valor, o crea una clave solo si falta.',
      ejemplo: `d = {"a": 1}\nd.update({"b": 2, "a": 10})\nprint(d)\nprint(d.pop("b"))\nd.setdefault("c", 0)\nd.setdefault("a", 99)\nprint(d)`,
      salida: "{'a': 10, 'b': 2}\n2\n{'a': 10, 'c': 0}",
      lecciones: ['m3-l2'],
    },
    {
      id: 'python-tuple',
      nombre: 'tupla (tuple)',
      grupo: 'Diccionarios, tuplas y conjuntos',
      firma: 't = (a, b, c)',
      resumen: 'Secuencia ordenada e inmutable (no se puede modificar tras crearla).',
      ejemplo: `punto = (3, 4)\nx, y = punto          # desempaquetado\nprint(x, y)\nprint(punto[0])\nprint(len(punto))`,
      salida: '3 4\n3\n2',
      notas: ['Es ideal para valores que van juntos y no deben cambiar (coordenadas, filas de una base de datos).'],
      lecciones: ['m3-l2'],
    },
    {
      id: 'python-set',
      nombre: 'conjunto (set)',
      grupo: 'Diccionarios, tuplas y conjuntos',
      firma: 's = {a, b, c} · set(iterable)',
      resumen: 'Colección sin orden y sin repetidos; ideal para eliminar duplicados.',
      ejemplo: `ciudades = ["Bogota", "Lima", "Bogota", "Cali", "Lima"]\nunicas = set(ciudades)\nprint(len(unicas))\nprint(sorted(unicas))\nunicas.add("Quito")\nprint("Quito" in unicas)`,
      salida: "3\n['Bogota', 'Cali', 'Lima']\nTrue",
      lecciones: ['m3-l3'],
    },
    {
      id: 'python-set-ops',
      nombre: 'Operaciones de conjuntos',
      grupo: 'Diccionarios, tuplas y conjuntos',
      firma: 'a | b · a & b · a - b · a ^ b',
      resumen: 'Unión (|), intersección (&), diferencia (-) y diferencia simétrica (^).',
      ejemplo: `a = {1, 2, 3}\nb = {2, 3, 4}\nprint(sorted(a | b))\nprint(sorted(a & b))\nprint(sorted(a - b))\nprint(sorted(a ^ b))`,
      salida: '[1, 2, 3, 4]\n[2, 3]\n[1]\n[1, 4]',
      relacionadas: ['python-set'],
      lecciones: ['m3-l3'],
    },

    // ───────────────────────── Control de flujo y funciones ─────────────────────────
    {
      id: 'python-if',
      nombre: 'if / elif / else',
      grupo: 'Control de flujo y funciones',
      firma: 'if condicion: ... elif otra: ... else: ...',
      resumen: 'Ejecuta un bloque u otro según se cumplan condiciones.',
      ejemplo: `nota = 3.7\nif nota >= 4.5:\n    print("Excelente")\nelif nota >= 3.0:\n    print("Aprobado")\nelse:\n    print("Reprobado")`,
      salida: 'Aprobado',
      notas: ['La indentación (4 espacios) define qué líneas pertenecen al bloque.', 'Operadores lógicos: and, or, not. Comparación: ==, !=, <, >, <=, >=.'],
      lecciones: ['m2-l1'],
    },
    {
      id: 'python-for',
      nombre: 'for',
      grupo: 'Control de flujo y funciones',
      firma: 'for elemento in coleccion: ...',
      resumen: 'Repite un bloque para cada elemento de una colección.',
      ejemplo: `total = 0\nfor precio in [10, 20, 30]:\n    total += precio\nprint(total)`,
      salida: '60',
      relacionadas: ['python-range', 'python-enumerate'],
      lecciones: ['m2-l2'],
    },
    {
      id: 'python-while',
      nombre: 'while / break / continue',
      grupo: 'Control de flujo y funciones',
      firma: 'while condicion: ... · break · continue',
      resumen: 'while repite mientras la condición sea verdadera; break sale del bucle; continue salta a la siguiente vuelta.',
      ejemplo: `n = 0\nwhile True:\n    n += 1\n    if n == 2:\n        continue\n    if n > 4:\n        break\n    print(n)`,
      salida: '1\n3\n4',
      notas: ['Cuida que la condición llegue a ser falsa o habrá un bucle infinito.'],
      lecciones: ['m2-l3'],
    },
    {
      id: 'python-def',
      nombre: 'def / return',
      grupo: 'Control de flujo y funciones',
      firma: 'def nombre(parametros): ... return valor',
      resumen: 'Define una función reutilizable que puede devolver un resultado.',
      ejemplo: `def promedio(valores):\n    return sum(valores) / len(valores)\n\nprint(promedio([4, 5, 6]))`,
      salida: '5.0',
      notas: ['Sin return, la función devuelve None.'],
      relacionadas: ['python-args-kwargs'],
      lecciones: ['m4-l1'],
    },
    {
      id: 'python-args-kwargs',
      nombre: 'Parámetros por defecto, *args y **kwargs',
      grupo: 'Control de flujo y funciones',
      firma: 'def f(a, b=10, *args, **kwargs)',
      resumen: 'Valores por defecto, número variable de argumentos posicionales (*args) y con nombre (**kwargs).',
      ejemplo: `def resumen(nombre, ciudad="Bogota", *extras, **opciones):\n    print(nombre, ciudad, extras, opciones)\n\nresumen("Ana")\nresumen("Luis", "Lima", 1, 2, activo=True)`,
      salida: "Ana Bogota () {}\nLuis Lima (1, 2) {'activo': True}",
      lecciones: ['m4-l2'],
    },
    {
      id: 'python-lambda',
      nombre: 'lambda',
      grupo: 'Control de flujo y funciones',
      firma: 'lambda parametros: expresion',
      resumen: 'Función anónima de una sola expresión, útil como argumento de sorted, map o filter.',
      ejemplo: `cuadrado = lambda x: x * x\nprint(cuadrado(5))\npersonas = [("Ana", 30), ("Luis", 25)]\nprint(sorted(personas, key=lambda p: p[1]))`,
      salida: "25\n[('Luis', 25), ('Ana', 30)]",
      lecciones: ['m4-l3'],
    },
    {
      id: 'python-import',
      nombre: 'import',
      grupo: 'Control de flujo y funciones',
      firma: 'import modulo · import modulo as alias · from modulo import nombre',
      resumen: 'Trae funciones de otros módulos o bibliotecas para usarlas.',
      ejemplo: `import math\nimport pandas as pd\nfrom math import sqrt\nprint(math.pi)\nprint(sqrt(16))\nprint(pd.__name__)`,
      salida: '3.141592653589793\n4.0\npandas',
      notas: ['Alias habituales: import pandas as pd, import numpy as np, import matplotlib.pyplot as plt.'],
      lecciones: ['m4-l4'],
    },

    // ───────────────────────── Errores y archivos ─────────────────────────
    {
      id: 'python-try-except',
      nombre: 'try / except / finally',
      grupo: 'Errores y archivos',
      firma: 'try: ... except TipoDeError as e: ... else: ... finally: ...',
      resumen: 'Captura errores para que el programa no se detenga y se pueda reaccionar.',
      ejemplo: `def a_numero(texto):\n    try:\n        return float(texto)\n    except ValueError:\n        return None\n    finally:\n        print("revisado:", texto)\n\nprint(a_numero("3.5"))\nprint(a_numero("abc"))`,
      salida: 'revisado: 3.5\n3.5\nrevisado: abc\nNone',
      notas: ['Captura errores concretos (ValueError, KeyError…) y evita un "except:" vacío que esconde fallos.', 'finally se ejecuta siempre, haya o no error.'],
      lecciones: ['m5-l1'],
    },
    {
      id: 'python-raise',
      nombre: 'raise',
      grupo: 'Errores y archivos',
      firma: 'raise TipoDeError("mensaje")',
      resumen: 'Lanza un error a propósito cuando los datos no son válidos.',
      ejemplo: `def dividir(a, b):\n    if b == 0:\n        raise ValueError("el divisor no puede ser cero")\n    return a / b\n\ntry:\n    dividir(1, 0)\nexcept ValueError as e:\n    print("Error:", e)`,
      salida: 'Error: el divisor no puede ser cero',
      lecciones: ['m5-l1'],
    },
    {
      id: 'python-open',
      nombre: 'open() y with',
      grupo: 'Errores y archivos',
      firma: 'with open(ruta, modo="r", encoding=None) as archivo: ...',
      resumen: 'Abre un archivo para leerlo o escribirlo; with lo cierra automáticamente.',
      parametros: [
        { nombre: 'ruta', descripcion: 'Dónde está (o se creará) el archivo.' },
        { nombre: 'modo', descripcion: '"r" leer, "w" escribir (borra lo anterior), "a" añadir al final.', porDefecto: '"r"' },
        { nombre: 'encoding', descripcion: 'Codificación del texto; usa "utf-8" para tildes y ñ.', porDefecto: 'según el sistema' },
      ],
      ejemplo: `with open("notas.txt", "w", encoding="utf-8") as f:\n    f.write("primera línea\\n")\n    f.write("segunda línea\\n")\n\nwith open("notas.txt", encoding="utf-8") as f:\n    for linea in f:\n        print(linea.strip())`,
      salida: 'primera línea\nsegunda línea',
      notas: ['f.read() lee todo; f.readlines() devuelve una lista de líneas; iterar f lee línea a línea (lo mejor para archivos grandes).'],
      lecciones: ['m5-l2'],
    },
    {
      id: 'python-pathlib',
      nombre: 'pathlib.Path',
      grupo: 'Errores y archivos',
      firma: 'Path(ruta) · .exists() · .name · .suffix · .parent · .read_text() · .write_text() · .glob("*.csv")',
      resumen: 'Maneja rutas de archivos y carpetas de forma portable entre sistemas.',
      ejemplo: `from pathlib import Path\n\nruta = Path("datos") / "ventas.csv"\nprint(ruta)\nprint(ruta.name, ruta.suffix, ruta.stem)\nprint(ruta.parent)\nprint(ruta.exists())`,
      salida: 'datos/ventas.csv\nventas.csv .csv ventas\ndatos\nFalse',
      relacionadas: ['python-open'],
      lecciones: ['m5-l2', 'm20-l1'],
    },
    {
      id: 'python-json',
      nombre: 'json.loads() / json.dumps()',
      grupo: 'Errores y archivos',
      firma: 'json.loads(texto) · json.dumps(objeto, indent=None, ensure_ascii=True) · json.load(f) · json.dump(obj, f)',
      resumen: 'Convierte entre texto JSON y diccionarios/listas de Python.',
      parametros: [
        { nombre: 'indent', descripcion: 'Espacios de sangría para que el JSON sea legible.', porDefecto: 'None' },
        { nombre: 'ensure_ascii', descripcion: 'Si es False, conserva tildes y ñ en lugar de escaparlas.', porDefecto: 'True' },
      ],
      ejemplo: `import json\n\ntexto = '{"nombre": "Ana", "edad": 30}'\ndatos = json.loads(texto)\nprint(datos["nombre"])\ndatos["activa"] = True\nprint(json.dumps(datos, ensure_ascii=False))`,
      salida: 'Ana\n{"nombre": "Ana", "edad": 30, "activa": true}',
      notas: ['loads/dumps trabajan con texto; load/dump con archivos (la "s" es de string).'],
      lecciones: ['m5-l3'],
    },
    {
      id: 'python-csv',
      nombre: 'csv.DictReader / csv.writer',
      grupo: 'Errores y archivos',
      firma: 'csv.DictReader(archivo) · csv.writer(archivo).writerow(fila)',
      resumen: 'Lee y escribe archivos CSV: DictReader entrega cada fila como diccionario.',
      ejemplo: `import csv, io\n\ncontenido = "producto,precio\\nMouse,15\\nTeclado,45\\n"\nfor fila in csv.DictReader(io.StringIO(contenido)):\n    print(fila["producto"], float(fila["precio"]))`,
      salida: 'Mouse 15.0\nTeclado 45.0',
      notas: ['Todo lo que se lee de un CSV es texto: convierte con int() o float(). Para análisis de datos, pandas.read_csv es más cómodo.'],
      relacionadas: ['pandas-read-csv'],
      lecciones: ['m5-l3'],
    },
    {
      id: 'python-assert',
      nombre: 'assert',
      grupo: 'Errores y archivos',
      firma: 'assert condicion, "mensaje"',
      resumen: 'Comprueba que algo es verdadero; si no, detiene el programa con un error. Base de las pruebas simples.',
      ejemplo: `def promedio(lista):\n    return sum(lista) / len(lista)\n\nassert promedio([2, 4, 6]) == 4\nassert promedio([10]) == 10, "falla con un solo elemento"\nprint("Todas las pruebas pasaron")`,
      salida: 'Todas las pruebas pasaron',
      lecciones: ['m5-l5'],
    },

    // ───────────────────────── Módulos útiles ─────────────────────────
    {
      id: 'python-math',
      nombre: 'math',
      grupo: 'Módulos útiles',
      firma: 'math.sqrt(x) · math.ceil(x) · math.floor(x) · math.pi · math.isclose(a, b)',
      resumen: 'Funciones matemáticas: raíz cuadrada, redondeo hacia arriba/abajo, constantes.',
      ejemplo: `import math\n\nprint(math.sqrt(81))\nprint(math.ceil(2.1), math.floor(2.9))\nprint(round(math.pi, 4))\nprint(math.isclose(0.1 + 0.2, 0.3))`,
      salida: '9.0\n3 2\n3.1416\nTrue',
      lecciones: ['m4-l4'],
    },
    {
      id: 'python-random',
      nombre: 'random',
      grupo: 'Módulos útiles',
      firma: 'random.seed(n) · random.randint(a, b) · random.choice(lista) · random.shuffle(lista) · random.sample(lista, k)',
      resumen: 'Números y elecciones al azar; seed hace que los resultados sean reproducibles.',
      ejemplo: `import random\n\nrandom.seed(42)\nprimero = random.randint(1, 100)\nrandom.seed(42)\nsegundo = random.randint(1, 100)\nprint(primero == segundo)\nprint(1 <= primero <= 100)`,
      salida: 'True\nTrue',
      notas: ['Fijar la semilla (seed) es clave para que un análisis o un modelo sea reproducible.'],
      lecciones: ['m4-l4'],
    },
    {
      id: 'python-datetime',
      nombre: 'datetime',
      grupo: 'Módulos útiles',
      firma: 'datetime(año, mes, día) · datetime.now() · timedelta(days=...) · .strftime(formato) · datetime.strptime(texto, formato)',
      resumen: 'Fechas y horas: crearlas, sumarles días, formatearlas y leerlas desde texto.',
      ejemplo: `from datetime import datetime, timedelta\n\nf = datetime(2024, 3, 15)\nprint(f.strftime("%d/%m/%Y"))\nprint(f + timedelta(days=20))\nprint(datetime.strptime("2024-12-25", "%Y-%m-%d").year)\nprint((datetime(2024, 3, 15) - datetime(2024, 3, 1)).days)`,
      salida: '15/03/2024\n2024-04-04 00:00:00\n2024\n14',
      notas: ['Códigos de formato: %Y año, %m mes, %d día, %H hora, %M minutos, %S segundos.'],
      relacionadas: ['pandas-to-datetime'],
      lecciones: ['m7-l3'],
    },
    {
      id: 'python-counter',
      nombre: 'collections.Counter',
      grupo: 'Módulos útiles',
      firma: 'Counter(iterable) · .most_common(n)',
      resumen: 'Cuenta cuántas veces aparece cada elemento.',
      ejemplo: `from collections import Counter\n\nc = Counter(["a", "b", "a", "c", "a", "b"])\nprint(c["a"])\nprint(c.most_common(2))`,
      salida: "3\n[('a', 3), ('b', 2)]",
      lecciones: ['m3-l2'],
    },
    {
      id: 'python-argparse',
      nombre: 'argparse',
      grupo: 'Módulos útiles',
      firma: 'ArgumentParser() · parser.add_argument("--nombre", type=int, default=1, required=False) · parser.parse_args()',
      resumen: 'Define los argumentos de un script para usarlo desde la línea de comandos.',
      ejemplo: `import argparse\n\nparser = argparse.ArgumentParser(description="Resume un CSV")\nparser.add_argument("--archivo", required=True)\nparser.add_argument("--top", type=int, default=3)\nargs = parser.parse_args(["--archivo", "ventas.csv"])\nprint(args.archivo, args.top)`,
      salida: 'ventas.csv 3',
      notas: ['En un script real se usa parser.parse_args() sin argumentos: lee lo que escribió el usuario en la terminal.'],
      lecciones: ['m20-l3'],
    },
    {
      id: 'python-dataclass',
      nombre: '@dataclass y type hints',
      grupo: 'Módulos útiles',
      firma: '@dataclass class Nombre: campo: tipo = valor',
      resumen: 'Crea clases de datos sin escribir __init__; los type hints documentan los tipos esperados.',
      ejemplo: `from dataclasses import dataclass\n\n@dataclass\nclass Producto:\n    nombre: str\n    precio: float\n    stock: int = 0\n\np = Producto("Mouse", 15.0)\nprint(p)\nprint(p.precio * 2)`,
      salida: "Producto(nombre='Mouse', precio=15.0, stock=0)\n30.0",
      lecciones: ['m5-l4'],
    },
  ],
}
