import type { ColeccionRef } from './tipos'

export const sklearnRef: ColeccionRef = {
  id: 'sklearn',
  titulo: 'scikit-learn',
  descripcion: 'Machine learning: preparar datos, entrenar modelos, medir su calidad, validar y agrupar.',
  icono: '🤖',
  lenguaje: 'python',
  nota: 'Casi todos los objetos siguen la misma API: fit(X, y) aprende, predict(X) predice, transform(X) transforma y score(X, y) evalúa. X siempre es 2D (filas × variables).',
  entradas: [
    // ───────────────────────── Preparar los datos ─────────────────────────
    {
      id: 'sklearn-train-test-split',
      nombre: 'train_test_split()',
      grupo: 'Preparar los datos',
      firma: 'train_test_split(X, y, test_size=0.25, random_state=None, stratify=None, shuffle=True)',
      resumen: 'Divide los datos en una parte para entrenar y otra para evaluar el modelo en datos que no ha visto.',
      parametros: [
        { nombre: 'test_size', descripcion: 'Fracción (0.2 = 20%) o número de filas para la prueba.', porDefecto: '0.25' },
        { nombre: 'random_state', descripcion: 'Semilla: hace la división reproducible.', porDefecto: 'None' },
        { nombre: 'stratify', descripcion: 'Pasa y para conservar la proporción de clases en ambos conjuntos (clave con clases desbalanceadas).', porDefecto: 'None' },
        { nombre: 'shuffle', descripcion: 'Mezclar antes de dividir. Con series temporales debe ser False.', porDefecto: 'True' },
      ],
      ejemplo: `from sklearn.model_selection import train_test_split\n\nX = [[i] for i in range(20)]\ny = [0] * 16 + [1] * 4\nX_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.25, stratify=y, random_state=42)\nprint(len(X_tr), len(X_te))\nprint(sum(y_te))`,
      salida: '15 5\n1',
      notas: ['Divide ANTES de escalar, imputar o codificar: esas transformaciones se ajustan solo con el entrenamiento (si no, hay data leakage).'],
      lecciones: ['m12-l1', 'm14-l5'],
    },
    {
      id: 'sklearn-standardscaler',
      nombre: 'StandardScaler',
      grupo: 'Preparar los datos',
      firma: 'StandardScaler().fit_transform(X)',
      resumen: 'Estandariza cada variable: media 0 y desviación estándar 1.',
      ejemplo: `from sklearn.preprocessing import StandardScaler\n\nX = [[10], [20], [30], [40]]\nesc = StandardScaler()\nZ = esc.fit_transform(X)\nprint(Z.round(2).tolist())\nprint(esc.mean_, esc.transform([[25]]).round(2).tolist())`,
      salida: '[[-1.34], [-0.45], [0.45], [1.34]]\n[25.] [[0.0]]',
      notas: ['fit solo con el entrenamiento; con los datos de prueba usa solo transform (nunca fit).', 'Imprescindible para K-Means, DBSCAN, PCA, regresión regularizada y redes neuronales.'],
      relacionadas: ['sklearn-minmaxscaler'],
      lecciones: ['m13-l2', 'm15-l3'],
    },
    {
      id: 'sklearn-minmaxscaler',
      nombre: 'MinMaxScaler',
      grupo: 'Preparar los datos',
      firma: 'MinMaxScaler(feature_range=(0, 1)).fit_transform(X)',
      resumen: 'Reescala cada variable a un rango fijo, normalmente de 0 a 1.',
      ejemplo: `from sklearn.preprocessing import MinMaxScaler\n\nprint(MinMaxScaler().fit_transform([[10], [20], [30], [50]]).round(2).tolist())`,
      salida: '[[0.0], [0.25], [0.5], [1.0]]',
      notas: ['Es sensible a los outliers: un valor extremo comprime a todos los demás.'],
      relacionadas: ['sklearn-standardscaler'],
      lecciones: ['m13-l2'],
    },
    {
      id: 'sklearn-onehotencoder',
      nombre: 'OneHotEncoder',
      grupo: 'Preparar los datos',
      firma: 'OneHotEncoder(sparse_output=True, handle_unknown="error", drop=None)',
      resumen: 'Convierte variables categóricas en columnas 0/1 (una por categoría), listo para usar en un modelo.',
      parametros: [
        { nombre: 'sparse_output', descripcion: 'False devuelve un arreglo normal en lugar de una matriz dispersa.', porDefecto: 'True' },
        { nombre: 'handle_unknown', descripcion: '"ignore" deja en ceros las categorías nuevas que no vio al entrenar (en vez de lanzar error).', porDefecto: '"error"' },
        { nombre: 'drop', descripcion: '"first" elimina una categoría por variable para evitar redundancia.', porDefecto: 'None' },
      ],
      ejemplo: `from sklearn.preprocessing import OneHotEncoder\n\nenc = OneHotEncoder(sparse_output=False, handle_unknown="ignore")\nX = enc.fit_transform([["Basico"], ["Premium"], ["Basico"]])\nprint(enc.categories_[0].tolist())\nprint(X.tolist())\nprint(enc.transform([["Nuevo"]]).tolist())`,
      salida: "['Basico', 'Premium']\n[[1.0, 0.0], [0.0, 1.0], [1.0, 0.0]]\n[[0.0, 0.0]]",
      relacionadas: ['pandas-get-dummies'],
      lecciones: ['m13-l1', 'm18-l2'],
    },
    {
      id: 'sklearn-simpleimputer',
      nombre: 'SimpleImputer',
      grupo: 'Preparar los datos',
      firma: 'SimpleImputer(strategy="mean", fill_value=None)',
      resumen: 'Rellena valores faltantes con la media, la mediana, el valor más frecuente o una constante.',
      parametros: [{ nombre: 'strategy', descripcion: '"mean", "median", "most_frequent" o "constant".', porDefecto: '"mean"' }],
      ejemplo: `import numpy as np\nfrom sklearn.impute import SimpleImputer\n\nX = np.array([[1.0], [np.nan], [3.0], [8.0]])\nprint(SimpleImputer(strategy="median").fit_transform(X).tolist())`,
      salida: '[[1.0], [3.0], [3.0], [8.0]]',
      notas: ['Dentro de un Pipeline, la mediana se calcula solo con los datos de entrenamiento.'],
      lecciones: ['m18-l2'],
    },
    {
      id: 'sklearn-columntransformer',
      nombre: 'ColumnTransformer',
      grupo: 'Preparar los datos',
      firma: 'ColumnTransformer([(nombre, transformador, columnas), ...], remainder="drop")',
      resumen: 'Aplica un tratamiento distinto a cada grupo de columnas (p. ej. escalar numéricas y codificar texto).',
      parametros: [{ nombre: 'remainder', descripcion: '"drop" descarta las columnas no listadas; "passthrough" las deja tal cual.', porDefecto: '"drop"' }],
      ejemplo: `import pandas as pd\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import OneHotEncoder, StandardScaler\n\ndf = pd.DataFrame({"edad": [20, 30, 40], "plan": ["A", "B", "A"]})\nct = ColumnTransformer([\n    ("num", StandardScaler(), ["edad"]),\n    ("cat", OneHotEncoder(sparse_output=False), ["plan"]),\n])\nprint(ct.fit_transform(df).shape)\nprint(list(ct.get_feature_names_out()))`,
      salida: "(3, 3)\n['num__edad', 'cat__plan_A', 'cat__plan_B']",
      lecciones: ['m18-l2'],
    },
    {
      id: 'sklearn-pipeline',
      nombre: 'Pipeline / make_pipeline',
      grupo: 'Preparar los datos',
      firma: 'Pipeline([("paso1", obj1), ("paso2", modelo)]) · make_pipeline(obj1, modelo)',
      resumen: 'Encadena preprocesamiento y modelo en un solo objeto: se ajusta y predice con un único fit/predict.',
      ejemplo: `from sklearn.linear_model import LinearRegression\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\n\nX = [[1], [2], [3], [4]]\ny = [10, 20, 30, 40]\nmodelo = make_pipeline(StandardScaler(), LinearRegression()).fit(X, y)\nprint(round(modelo.predict([[5]])[0], 1))\nprint(list(modelo.named_steps))`,
      salida: "50.0\n['standardscaler', 'linearregression']",
      notas: ['Evita data leakage: cada paso se ajusta solo con los datos de entrenamiento, incluso dentro de la validación cruzada.'],
      lecciones: ['m12-l4', 'm13-l4'],
    },

    // ───────────────────────── Modelos supervisados ─────────────────────────
    {
      id: 'sklearn-linearregression',
      nombre: 'LinearRegression',
      grupo: 'Modelos supervisados',
      firma: 'LinearRegression().fit(X, y) · .predict(X) · .coef_ · .intercept_ · .score(X, y)',
      resumen: 'Regresión lineal: ajusta una recta (o un plano) para predecir un número.',
      ejemplo: `from sklearn.linear_model import LinearRegression\n\nX = [[1], [2], [3], [4]]\ny = [3, 5, 7, 9]\nm = LinearRegression().fit(X, y)\nprint(m.coef_, round(m.intercept_, 2))\nprint(m.predict([[10]]).round(1))\nprint(m.score(X, y))`,
      salida: '[2.] 1.0\n[21.]\n1.0',
      notas: ['coef_ es el cambio en y por cada unidad que sube cada variable; intercept_ es el valor cuando X = 0.', 'score() devuelve R² en regresión y exactitud (accuracy) en clasificación.'],
      relacionadas: ['estadistica-ols'],
      lecciones: ['m12-l2'],
    },
    {
      id: 'sklearn-logisticregression',
      nombre: 'LogisticRegression',
      grupo: 'Modelos supervisados',
      firma: 'LogisticRegression(C=1.0, class_weight=None, max_iter=100)',
      resumen: 'Clasificación: estima la probabilidad de cada clase y asigna la más probable.',
      parametros: [
        { nombre: 'C', descripcion: 'Inverso de la regularización: valores pequeños = modelo más simple.', porDefecto: '1.0' },
        { nombre: 'class_weight', descripcion: '"balanced" da más peso a la clase minoritaria (clases desbalanceadas).', porDefecto: 'None' },
        { nombre: 'max_iter', descripcion: 'Iteraciones máximas del optimizador; súbelo si aparece ConvergenceWarning.', porDefecto: '100' },
      ],
      ejemplo: `from sklearn.linear_model import LogisticRegression\n\nX = [[1], [2], [3], [4], [5], [6], [7], [8]]\ny = [0, 0, 0, 0, 1, 1, 1, 1]\nm = LogisticRegression().fit(X, y)\nprint(m.predict([[2], [7]]).tolist())\nprint(m.predict_proba([[7]]).shape)\nprint(m.classes_.tolist())`,
      salida: '[0, 1]\n(1, 2)\n[0, 1]',
      notas: ['predict devuelve la clase; predict_proba devuelve una probabilidad por clase (columnas en el orden de classes_).'],
      lecciones: ['m14-l2', 'm14-l5'],
    },
    {
      id: 'sklearn-dummy',
      nombre: 'DummyClassifier / DummyRegressor',
      grupo: 'Modelos supervisados',
      firma: 'DummyClassifier(strategy="most_frequent") · DummyRegressor(strategy="mean")',
      resumen: 'Modelo "tonto" que sirve de línea base: predice siempre la clase más común (o la media).',
      ejemplo: `from sklearn.dummy import DummyClassifier\n\nX = [[0], [1], [2], [3], [4]]\ny = [0, 0, 0, 0, 1]\nbase = DummyClassifier(strategy="most_frequent").fit(X, y)\nprint(base.predict([[10]]).tolist())\nprint(base.score(X, y))`,
      salida: '[0]\n0.8',
      notas: ['Un modelo real debe superar claramente a la línea base; si no, no aporta valor.'],
      lecciones: ['m18-l3', 'm16-l3'],
    },
    {
      id: 'sklearn-mlp',
      nombre: 'MLPClassifier / MLPRegressor',
      grupo: 'Modelos supervisados',
      firma: 'MLPClassifier(hidden_layer_sizes=(100,), activation="relu", solver="adam", alpha=0.0001, max_iter=200, early_stopping=False, random_state=None)',
      resumen: 'Red neuronal de capas completamente conectadas (perceptrón multicapa).',
      parametros: [
        { nombre: 'hidden_layer_sizes', descripcion: 'Neuronas por capa oculta: (8,) una capa de 8; (16, 8) dos capas.', porDefecto: '(100,)' },
        { nombre: 'activation', descripcion: '"relu", "tanh" o "logistic".', porDefecto: '"relu"' },
        { nombre: 'solver', descripcion: '"adam" (datasets grandes) o "lbfgs" (datasets pequeños, converge mejor).', porDefecto: '"adam"' },
        { nombre: 'alpha', descripcion: 'Regularización L2: más alto = modelo más simple (contra el sobreajuste).', porDefecto: '0.0001' },
        { nombre: 'max_iter', descripcion: 'Iteraciones máximas; súbelo si hay ConvergenceWarning.', porDefecto: '200' },
        { nombre: 'early_stopping', descripcion: 'Detiene el entrenamiento cuando una parte de validación deja de mejorar.', porDefecto: 'False' },
      ],
      ejemplo: `from sklearn.neural_network import MLPClassifier\n\nX = [[0, 0], [0, 1], [1, 0], [1, 1]]\ny = [0, 1, 1, 0]\nred = MLPClassifier(hidden_layer_sizes=(8,), activation="tanh", solver="lbfgs", max_iter=2000, random_state=0).fit(X, y)\nprint(red.predict(X).tolist())\nprint(red.n_layers_)`,
      salida: '[0, 1, 1, 0]\n3',
      notas: ['Escala siempre las variables antes de entrenar una red.'],
      lecciones: ['m17-l4', 'm17-l5'],
    },

    // ───────────────────────── Métricas ─────────────────────────
    {
      id: 'sklearn-mae-rmse',
      nombre: 'mean_absolute_error / root_mean_squared_error / r2_score',
      grupo: 'Métricas',
      firma: 'mean_absolute_error(y_real, y_pred) · root_mean_squared_error(y_real, y_pred) · r2_score(y_real, y_pred)',
      resumen: 'Métricas de regresión: error promedio (MAE), error que penaliza los grandes (RMSE) y proporción explicada (R²).',
      ejemplo: `from sklearn.metrics import mean_absolute_error, r2_score, root_mean_squared_error\n\ny_real = [100, 200, 300]\ny_pred = [110, 190, 330]\nprint(round(mean_absolute_error(y_real, y_pred), 2))\nprint(round(root_mean_squared_error(y_real, y_pred), 2))\nprint(round(r2_score(y_real, y_pred), 3))`,
      salida: '16.67\n19.15\n0.945',
      notas: ['El primer argumento es siempre el valor real y el segundo la predicción.', 'RMSE ≥ MAE. R² = 0 equivale a predecir siempre la media; puede ser negativo.'],
      lecciones: ['m14-l1'],
    },
    {
      id: 'sklearn-accuracy',
      nombre: 'accuracy_score()',
      grupo: 'Métricas',
      firma: 'accuracy_score(y_real, y_pred)',
      resumen: 'Proporción de predicciones correctas. Engaña cuando las clases están desbalanceadas.',
      ejemplo: `from sklearn.metrics import accuracy_score\n\nprint(accuracy_score([0, 1, 1, 0], [0, 1, 0, 0]))\n# Un modelo que siempre dice "0" con un 5% de casos positivos:\nprint(accuracy_score([0] * 95 + [1] * 5, [0] * 100))`,
      salida: '0.75\n0.95',
      lecciones: ['m14-l3', 'm14-l5'],
    },
    {
      id: 'sklearn-precision-recall',
      nombre: 'precision_score / recall_score / f1_score',
      grupo: 'Métricas',
      firma: 'precision_score(y_real, y_pred) · recall_score(y_real, y_pred) · f1_score(y_real, y_pred)',
      resumen: 'Precisión: de lo que marqué positivo, cuánto lo era. Recall: de los positivos reales, cuántos encontré. F1: su media armónica.',
      ejemplo: `from sklearn.metrics import f1_score, precision_score, recall_score\n\ny_real = [1, 1, 1, 1, 0, 0, 0, 0, 0, 0]\ny_pred = [1, 1, 1, 0, 1, 1, 0, 0, 0, 0]\nprint(precision_score(y_real, y_pred))\nprint(recall_score(y_real, y_pred))\nprint(round(f1_score(y_real, y_pred), 2))`,
      salida: '0.6\n0.75\n0.67',
      notas: ['Prioriza recall si un falso negativo es muy costoso (no detectar una enfermedad); precisión si lo es un falso positivo.'],
      lecciones: ['m14-l3'],
    },
    {
      id: 'sklearn-confusion-matrix',
      nombre: 'confusion_matrix()',
      grupo: 'Métricas',
      firma: 'confusion_matrix(y_real, y_pred)',
      resumen: 'Tabla de aciertos y errores: [[verdaderos negativos, falsos positivos], [falsos negativos, verdaderos positivos]].',
      ejemplo: `from sklearn.metrics import confusion_matrix\n\ny_real = [1, 1, 1, 1, 0, 0, 0, 0, 0, 0]\ny_pred = [1, 1, 1, 0, 1, 1, 0, 0, 0, 0]\nprint(confusion_matrix(y_real, y_pred).tolist())`,
      salida: '[[4, 2], [1, 3]]',
      notas: ['Las filas son la clase real y las columnas la predicha (la clase 1 = positiva).'],
      lecciones: ['m14-l3'],
    },
    {
      id: 'sklearn-classification-report',
      nombre: 'classification_report()',
      grupo: 'Métricas',
      firma: 'classification_report(y_real, y_pred, output_dict=False)',
      resumen: 'Informe con precisión, recall y F1 de cada clase en un solo paso.',
      ejemplo: `from sklearn.metrics import classification_report\n\ny_real = [1, 1, 1, 1, 0, 0, 0, 0, 0, 0]\ny_pred = [1, 1, 1, 0, 1, 1, 0, 0, 0, 0]\ninforme = classification_report(y_real, y_pred, output_dict=True)\nprint(round(informe["1"]["recall"], 2))\nprint(informe["accuracy"])`,
      salida: '0.75\n0.7',
      lecciones: ['m14-l3'],
    },
    {
      id: 'sklearn-silhouette',
      nombre: 'silhouette_score()',
      grupo: 'Métricas',
      firma: 'silhouette_score(X, etiquetas)',
      resumen: 'Mide qué tan bien separados están los clusters (de -1 a 1; cerca de 1 es mejor).',
      ejemplo: `from sklearn.cluster import KMeans\nfrom sklearn.metrics import silhouette_score\n\nX = [[1, 1], [1.5, 2], [2, 1.5], [8, 8], [8.5, 9], [9, 8.5]]\netiquetas = KMeans(n_clusters=2, n_init=10, random_state=0).fit_predict(X)\nprint(round(silhouette_score(X, etiquetas), 2))`,
      salida: '0.9',
      lecciones: ['m15-l2'],
    },

    // ───────────────────────── Validación ─────────────────────────
    {
      id: 'sklearn-cross-val-score',
      nombre: 'cross_val_score()',
      grupo: 'Validación',
      firma: 'cross_val_score(modelo, X, y, cv=5, scoring=None)',
      resumen: 'Validación cruzada: entrena y evalúa varias veces con distintas particiones y devuelve un puntaje por pliegue.',
      parametros: [
        { nombre: 'cv', descripcion: 'Número de pliegues o un objeto como StratifiedKFold / TimeSeriesSplit.', porDefecto: '5' },
        { nombre: 'scoring', descripcion: 'Métrica: "accuracy", "f1", "recall", "r2", "neg_mean_absolute_error"… Las de error van en negativo.', porDefecto: 'la del modelo' },
      ],
      ejemplo: `from sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import cross_val_score\n\nX = [[i] for i in range(10)]\ny = [2 * i + 1 for i in range(10)]\nscores = cross_val_score(LinearRegression(), X, y, cv=5)\nprint(len(scores))\nprint(round(scores.mean(), 2))`,
      salida: '5\n1.0',
      notas: ['Reporta la media y la desviación (scores.std()). Mete el preprocesamiento en un Pipeline para evitar leakage.'],
      lecciones: ['m14-l4'],
    },
    {
      id: 'sklearn-kfold',
      nombre: 'StratifiedKFold / KFold / TimeSeriesSplit',
      grupo: 'Validación',
      firma: 'StratifiedKFold(n_splits=5, shuffle=False, random_state=None) · TimeSeriesSplit(n_splits=5)',
      resumen: 'Definen cómo se parten los datos en validación cruzada: estratificada (clasificación) o respetando el orden del tiempo.',
      ejemplo: `from sklearn.model_selection import TimeSeriesSplit\n\nfor train, test in TimeSeriesSplit(n_splits=3).split(range(10)):\n    print(train.tolist(), test.tolist())`,
      salida: '[0, 1, 2, 3] [4, 5]\n[0, 1, 2, 3, 4, 5] [6, 7]\n[0, 1, 2, 3, 4, 5, 6, 7] [8, 9]',
      notas: ['En series temporales el conjunto de prueba debe ser siempre posterior al de entrenamiento.'],
      lecciones: ['m16-l2', 'm18-l5'],
    },

    // ───────────────────────── Aprendizaje no supervisado ─────────────────────────
    {
      id: 'sklearn-kmeans',
      nombre: 'KMeans',
      grupo: 'Aprendizaje no supervisado',
      firma: 'KMeans(n_clusters=8, n_init="auto", random_state=None) · .fit(X) · .labels_ · .cluster_centers_ · .inertia_ · .predict(X)',
      resumen: 'Agrupa los datos en k clusters según su cercanía a centros que va recalculando.',
      parametros: [
        { nombre: 'n_clusters', descripcion: 'Cuántos grupos formar (k).', porDefecto: '8' },
        { nombre: 'n_init', descripcion: 'Veces que se repite con distintos puntos de partida; se queda con el mejor.', porDefecto: '"auto"' },
        { nombre: 'random_state', descripcion: 'Semilla para resultados reproducibles.', porDefecto: 'None' },
      ],
      ejemplo: `from sklearn.cluster import KMeans\n\nX = [[1, 1], [1.5, 2], [2, 1.5], [8, 8], [8.5, 9], [9, 8.5]]\nm = KMeans(n_clusters=2, n_init=10, random_state=0).fit(X)\nprint(m.labels_[0] == m.labels_[1], m.labels_[0] == m.labels_[3])\nprint(round(m.inertia_, 2))`,
      salida: 'True False\n2.0',
      notas: ['Los números de cluster (0, 1…) son arbitrarios: solo importa qué puntos quedan juntos.', 'Escala las variables antes de agrupar.'],
      lecciones: ['m15-l1', 'm15-l2'],
    },
    {
      id: 'sklearn-dbscan',
      nombre: 'DBSCAN',
      grupo: 'Aprendizaje no supervisado',
      firma: 'DBSCAN(eps=0.5, min_samples=5).fit_predict(X)',
      resumen: 'Agrupa por densidad, descubre el número de clusters solo y marca el ruido con la etiqueta -1.',
      parametros: [
        { nombre: 'eps', descripcion: 'Radio de vecindad: dos puntos más cerca que esto son vecinos.', porDefecto: '0.5' },
        { nombre: 'min_samples', descripcion: 'Vecinos necesarios (incluido el propio punto) para formar una zona densa.', porDefecto: '5' },
      ],
      ejemplo: `from sklearn.cluster import DBSCAN\n\nX = [[1, 1], [1.2, 1.1], [1.1, 1.3], [1.3, 1.2], [5, 5], [5.2, 5.1], [5.1, 5.3], [5.3, 5.2], [9, 1]]\netiquetas = DBSCAN(eps=0.6, min_samples=3).fit_predict(X)\nprint(etiquetas.tolist())`,
      salida: '[0, 0, 0, 0, 1, 1, 1, 1, -1]',
      notas: ['La etiqueta -1 no es un grupo: son puntos atípicos (ruido).', 'Muy sensible a eps: demasiado pequeño → todo es ruido; demasiado grande → un solo cluster.'],
      lecciones: ['m15-l4'],
    },
    {
      id: 'sklearn-pca',
      nombre: 'PCA',
      grupo: 'Aprendizaje no supervisado',
      firma: 'PCA(n_components=2).fit_transform(X) · .explained_variance_ratio_',
      resumen: 'Reduce el número de variables conservando la mayor parte de la varianza (de la información).',
      ejemplo: `from sklearn.decomposition import PCA\n\nX = [[1, 2, 2.01], [2, 4, 3.99], [3, 6, 6.02], [4, 8, 7.98], [5, 10, 10.01], [6, 12, 12.0]]\npca = PCA(n_components=1).fit(X)\nprint(pca.transform(X).shape)\nprint(round(pca.explained_variance_ratio_[0], 4))`,
      salida: '(6, 1)\n1.0',
      notas: ['Estandariza antes de aplicar PCA. Las componentes pierden interpretabilidad directa.'],
      lecciones: ['m15-l5'],
    },

    // ───────────────────────── Texto ─────────────────────────
    {
      id: 'sklearn-countvectorizer',
      nombre: 'CountVectorizer',
      grupo: 'Texto',
      firma: 'CountVectorizer(lowercase=True, stop_words=None, ngram_range=(1, 1), min_df=1, max_features=None)',
      resumen: 'Bag of Words: convierte textos en una matriz de conteo de palabras.',
      ejemplo: `from sklearn.feature_extraction.text import CountVectorizer\n\ntextos = ["me gusta python", "python es genial"]\nv = CountVectorizer()\nX = v.fit_transform(textos)\nprint(v.get_feature_names_out().tolist())\nprint(X.toarray().tolist())`,
      salida: "['es', 'genial', 'gusta', 'me', 'python']\n[[0, 0, 1, 1, 1], [1, 1, 0, 0, 1]]",
      notas: ['Ajusta (fit) solo con el entrenamiento; con datos nuevos usa transform.'],
      lecciones: ['m16-l4'],
    },
    {
      id: 'sklearn-tfidf',
      nombre: 'TfidfVectorizer',
      grupo: 'Texto',
      firma: 'TfidfVectorizer(lowercase=True, stop_words=None, ngram_range=(1, 1), min_df=1)',
      resumen: 'Como CountVectorizer, pero pondera las palabras: más peso a las poco frecuentes, menos a las comunes.',
      ejemplo: `from sklearn.feature_extraction.text import TfidfVectorizer\n\ntextos = ["gato come pescado", "gato duerme", "perro come"]\nt = TfidfVectorizer().fit(textos)\nprint(dict(zip(t.get_feature_names_out().tolist(), t.idf_.round(2).tolist())))`,
      salida: "{'come': 1.29, 'duerme': 1.69, 'gato': 1.29, 'perro': 1.69, 'pescado': 1.69}",
      relacionadas: ['sklearn-countvectorizer'],
      lecciones: ['m16-l5'],
    },

    // ───────────────────────── API común de los objetos ─────────────────────────
    {
      id: 'sklearn-fit-predict',
      nombre: 'fit() / predict() / transform() / score()',
      grupo: 'API común de los objetos',
      firma: 'obj.fit(X, y) · obj.predict(X) · obj.transform(X) · obj.fit_transform(X) · obj.score(X, y)',
      resumen: 'Los cuatro métodos que comparten casi todos los objetos de scikit-learn.',
      descripcion: 'fit aprende de los datos (calcula coeficientes, medias, categorías…). predict usa lo aprendido para predecir. transform aplica una transformación ya aprendida (escalar, codificar). fit_transform hace fit y transform en un paso. score evalúa el modelo.',
      ejemplo: `from sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LinearRegression\n\nX_train, X_test = [[1], [2], [3]], [[4]]\nesc = StandardScaler().fit(X_train)          # aprende media y desviación\nprint(esc.transform(X_test).round(2).tolist())  # aplica con lo aprendido\nm = LinearRegression().fit(X_train, [2, 4, 6])\nprint(m.predict(X_test).round(1).tolist())`,
      salida: '[[2.45]]\n[8.0]',
      notas: ['Regla de oro: fit solo con entrenamiento; con prueba solo transform/predict.'],
      lecciones: ['m12-l2', 'm13-l2'],
    },
  ],
}
