import type { ColeccionRef } from './tipos'

export const sqlRef: ColeccionRef = {
  id: 'sql',
  titulo: 'SQL',
  descripcion: 'Consultar, filtrar, agrupar y combinar tablas; funciones de texto, fecha y números; crear y modificar datos.',
  icono: '🗄️',
  lenguaje: 'sql',
  nota: 'Los ejemplos se ejecutan sobre una base de práctica en SQLite con tres tablas: clientes (id, nombre, ciudad, plan), productos (id, nombre, categoria, precio) y pedidos (id, cliente_id, producto_id, cantidad, fecha). En cada ejecución la base se reinicia: los cambios con INSERT/UPDATE/DELETE no se conservan.',
  entradas: [
    // ───────────────────────── Consultar ─────────────────────────
    {
      id: 'sql-select',
      nombre: 'SELECT … FROM',
      grupo: 'Consultar',
      firma: 'SELECT columnas FROM tabla',
      resumen: 'Pide columnas de una tabla. * trae todas; AS les pone otro nombre en el resultado.',
      ejemplo: `SELECT nombre, ciudad FROM clientes;\n\nSELECT nombre AS cliente, plan FROM clientes LIMIT 2;`,
      salida: "nombre | ciudad\nAna | Bogota\nLuis | Medellin\nMarta | Bogota\nPedro | Cali\nSofia | Medellin\nDiego | Bogota\ncliente | plan\nAna | Premium\nLuis | Basico",
      notas: ['SELECT * es cómodo para explorar; en consultas definitivas pide solo las columnas que necesitas.', 'El orden de escritura es: SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY → LIMIT.'],
      lecciones: ['m19-l1'],
    },
    {
      id: 'sql-where',
      nombre: 'WHERE',
      grupo: 'Consultar',
      firma: 'WHERE condicion',
      resumen: 'Filtra las filas que cumplen una condición (antes de agrupar).',
      ejemplo: `SELECT nombre, ciudad FROM clientes WHERE ciudad = 'Bogota';\n\nSELECT nombre FROM productos WHERE precio > 100 AND categoria = 'Accesorios';`,
      salida: "nombre | ciudad\nAna | Bogota\nMarta | Bogota\nDiego | Bogota\nnombre\nTeclado\nAudifonos",
      notas: ["Los textos van entre comillas simples: ciudad = 'Bogota'.", 'Operadores: =, <> (distinto), <, >, <=, >=, AND, OR, NOT.'],
      relacionadas: ['sql-having'],
      lecciones: ['m19-l1'],
    },
    {
      id: 'sql-in-between-like',
      nombre: 'IN / BETWEEN / LIKE',
      grupo: 'Consultar',
      firma: 'col IN (a, b) · col BETWEEN x AND y · col LIKE \'patron%\'',
      resumen: 'IN: pertenece a una lista. BETWEEN: dentro de un rango (incluye los extremos). LIKE: coincide con un patrón de texto.',
      descripcion: 'En LIKE, % reemplaza a cualquier cantidad de caracteres y _ a exactamente uno.',
      ejemplo: `SELECT nombre FROM clientes WHERE ciudad IN ('Cali', 'Medellin');\n\nSELECT nombre, precio FROM productos WHERE precio BETWEEN 100 AND 1000;\n\nSELECT nombre FROM clientes WHERE nombre LIKE 'M%';`,
      salida: "nombre\nLuis\nPedro\nSofia\nnombre | precio\nTeclado | 120.0\nMonitor | 800.0\nAudifonos | 150.0\nnombre\nMarta",
      lecciones: ['m19-l1'],
    },
    {
      id: 'sql-is-null',
      nombre: 'IS NULL / IS NOT NULL',
      grupo: 'Consultar',
      firma: 'col IS NULL · col IS NOT NULL',
      resumen: 'Comprueba si un valor falta (NULL). Nunca se usa = NULL.',
      ejemplo: `SELECT c.nombre\nFROM clientes c\nLEFT JOIN pedidos pe ON pe.cliente_id = c.id\nWHERE pe.id IS NULL;`,
      salida: "nombre\nDiego",
      notas: ['NULL significa "desconocido": no es igual a nada, ni siquiera a otro NULL. Por eso = NULL nunca es verdadero.'],
      relacionadas: ['sql-left-join', 'sql-coalesce'],
      lecciones: ['m19-l3'],
    },
    {
      id: 'sql-order-by',
      nombre: 'ORDER BY',
      grupo: 'Consultar',
      firma: 'ORDER BY columna [ASC | DESC], ...',
      resumen: 'Ordena el resultado: ASC (ascendente, por defecto) o DESC (descendente).',
      ejemplo: `SELECT nombre, precio FROM productos ORDER BY precio DESC;\n\nSELECT nombre, ciudad FROM clientes ORDER BY ciudad ASC, nombre DESC;`,
      salida: "nombre | precio\nLaptop | 2500.0\nMonitor | 800.0\nAudifonos | 150.0\nTeclado | 120.0\nMouse | 50.0\nnombre | ciudad\nMarta | Bogota\nDiego | Bogota\nAna | Bogota\nPedro | Cali\nSofia | Medellin\nLuis | Medellin",
      lecciones: ['m19-l1'],
    },
    {
      id: 'sql-limit',
      nombre: 'LIMIT / OFFSET',
      grupo: 'Consultar',
      firma: 'LIMIT n [OFFSET m]',
      resumen: 'Devuelve solo n filas; OFFSET salta las primeras m (paginación).',
      ejemplo: `SELECT nombre, precio FROM productos ORDER BY precio DESC LIMIT 2;\n\nSELECT nombre, precio FROM productos ORDER BY precio DESC LIMIT 2 OFFSET 2;`,
      salida: "nombre | precio\nLaptop | 2500.0\nMonitor | 800.0\nnombre | precio\nAudifonos | 150.0\nTeclado | 120.0",
      notas: ['Úsalo con ORDER BY: sin orden, "las primeras n filas" no está definido.'],
      lecciones: ['m19-l1'],
    },
    {
      id: 'sql-distinct',
      nombre: 'DISTINCT',
      grupo: 'Consultar',
      firma: 'SELECT DISTINCT columnas FROM tabla',
      resumen: 'Elimina las filas repetidas del resultado.',
      ejemplo: `SELECT DISTINCT ciudad FROM clientes ORDER BY ciudad;\n\nSELECT COUNT(DISTINCT cliente_id) AS clientes_con_pedidos FROM pedidos;`,
      salida: "ciudad\nBogota\nCali\nMedellin\nclientes_con_pedidos\n5",
      lecciones: ['m19-l1'],
    },

    // ───────────────────────── Agregar y agrupar ─────────────────────────
    {
      id: 'sql-aggregates',
      nombre: 'COUNT / SUM / AVG / MIN / MAX',
      grupo: 'Agregar y agrupar',
      firma: 'COUNT(*) · COUNT(col) · SUM(col) · AVG(col) · MIN(col) · MAX(col)',
      resumen: 'Funciones de agregación: resumen muchas filas en un solo valor.',
      ejemplo: `SELECT COUNT(*) AS pedidos, SUM(cantidad) AS unidades, MAX(fecha) AS ultimo\nFROM pedidos;\n\nSELECT ROUND(AVG(precio), 2) AS precio_medio, MIN(precio) AS minimo FROM productos;`,
      salida: "pedidos | unidades | ultimo\n10 | 21 | 2024-03-09\nprecio_medio | minimo\n724.0 | 50.0",
      notas: ['COUNT(*) cuenta filas; COUNT(columna) cuenta solo las que no son NULL.'],
      relacionadas: ['pandas-stats'],
      lecciones: ['m19-l2'],
    },
    {
      id: 'sql-group-by',
      nombre: 'GROUP BY',
      grupo: 'Agregar y agrupar',
      firma: 'SELECT col, AGREGACION(...) FROM tabla GROUP BY col',
      resumen: 'Divide las filas en grupos y calcula una agregación por cada grupo.',
      ejemplo: `SELECT ciudad, COUNT(*) AS clientes\nFROM clientes\nGROUP BY ciudad\nORDER BY ciudad;\n\nSELECT categoria, ROUND(AVG(precio), 2) AS precio_medio\nFROM productos\nGROUP BY categoria;`,
      salida: "ciudad | clientes\nBogota | 3\nCali | 1\nMedellin | 2\ncategoria | precio_medio\nAccesorios | 106.67\nElectronica | 1650.0",
      notas: ['Toda columna del SELECT que no sea una agregación debe aparecer en el GROUP BY.'],
      relacionadas: ['pandas-groupby', 'sql-having'],
      lecciones: ['m19-l2'],
    },
    {
      id: 'sql-having',
      nombre: 'HAVING',
      grupo: 'Agregar y agrupar',
      firma: 'GROUP BY col HAVING condicion_sobre_agregacion',
      resumen: 'Filtra los grupos después de agrupar (WHERE filtra filas antes de agrupar).',
      ejemplo: `SELECT ciudad, COUNT(*) AS clientes\nFROM clientes\nGROUP BY ciudad\nHAVING COUNT(*) >= 2\nORDER BY ciudad;`,
      salida: "ciudad | clientes\nBogota | 3\nMedellin | 2",
      notas: ['No se puede usar COUNT(*) dentro de WHERE: todavía no existen los grupos. Para eso está HAVING.'],
      relacionadas: ['sql-where'],
      lecciones: ['m19-l2'],
    },

    // ───────────────────────── Combinar tablas ─────────────────────────
    {
      id: 'sql-inner-join',
      nombre: 'JOIN / INNER JOIN',
      grupo: 'Combinar tablas',
      firma: 'FROM a JOIN b ON a.clave = b.clave',
      resumen: 'Une dos tablas y deja solo las filas que tienen coincidencia en ambas.',
      ejemplo: `SELECT c.nombre AS cliente, p.nombre AS producto, pe.cantidad\nFROM pedidos pe\nJOIN clientes c ON c.id = pe.cliente_id\nJOIN productos p ON p.id = pe.producto_id\nORDER BY pe.id\nLIMIT 4;`,
      salida: "cliente | producto | cantidad\nAna | Laptop | 1\nAna | Mouse | 2\nLuis | Teclado | 1\nMarta | Monitor | 2",
      notas: ['Los alias de tabla (pe, c, p) acortan el código y evitan ambigüedades cuando dos tablas tienen columnas con el mismo nombre.'],
      relacionadas: ['pandas-merge', 'sql-left-join'],
      lecciones: ['m19-l3'],
    },
    {
      id: 'sql-left-join',
      nombre: 'LEFT JOIN',
      grupo: 'Combinar tablas',
      firma: 'FROM a LEFT JOIN b ON a.clave = b.clave',
      resumen: 'Conserva todas las filas de la tabla izquierda, con NULL donde no hay coincidencia en la derecha.',
      ejemplo: `SELECT c.nombre, COUNT(pe.id) AS pedidos\nFROM clientes c\nLEFT JOIN pedidos pe ON pe.cliente_id = c.id\nGROUP BY c.id\nORDER BY pedidos, c.nombre;`,
      salida: "nombre | pedidos\nDiego | 0\nPedro | 1\nLuis | 2\nMarta | 2\nSofia | 2\nAna | 3",
      notas: ['Con LEFT JOIN + WHERE derecha.id IS NULL encuentras registros sin coincidencia (clientes que nunca compraron).', 'Cuenta con COUNT(pe.id) (no COUNT(*)) para que un cliente sin pedidos dé 0.'],
      relacionadas: ['sql-is-null'],
      lecciones: ['m19-l3'],
    },
    {
      id: 'sql-union',
      nombre: 'UNION / UNION ALL',
      grupo: 'Combinar tablas',
      firma: 'SELECT ... UNION [ALL] SELECT ...',
      resumen: 'Apila los resultados de dos consultas con las mismas columnas; UNION quita repetidos y UNION ALL los conserva.',
      ejemplo: `SELECT ciudad FROM clientes WHERE plan = 'Premium'\nUNION\nSELECT ciudad FROM clientes WHERE plan = 'Basico'\nORDER BY ciudad;`,
      salida: "ciudad\nBogota\nCali\nMedellin",
      relacionadas: ['pandas-concat'],
      lecciones: ['m19-l3'],
    },

    // ───────────────────────── Consultas avanzadas ─────────────────────────
    {
      id: 'sql-case',
      nombre: 'CASE WHEN',
      grupo: 'Consultas avanzadas',
      firma: 'CASE WHEN condicion THEN valor [WHEN ...] [ELSE valor] END',
      resumen: 'El "if / elif / else" de SQL: crea columnas derivadas según condiciones.',
      ejemplo: `SELECT nombre, precio,\n       CASE WHEN precio >= 800 THEN 'Alto'\n            WHEN precio >= 100 THEN 'Medio'\n            ELSE 'Bajo' END AS nivel\nFROM productos\nORDER BY precio DESC;`,
      salida: "nombre | precio | nivel\nLaptop | 2500.0 | Alto\nMonitor | 800.0 | Alto\nAudifonos | 150.0 | Medio\nTeclado | 120.0 | Medio\nMouse | 50.0 | Bajo",
      notas: ['Evalúa las condiciones en orden y usa la primera verdadera. Siempre se cierra con END.'],
      lecciones: ['m19-l4'],
    },
    {
      id: 'sql-subquery',
      nombre: 'Subconsulta',
      grupo: 'Consultas avanzadas',
      firma: 'WHERE col > (SELECT ...) · FROM (SELECT ...) AS alias',
      resumen: 'Una consulta dentro de otra, entre paréntesis; sirve para comparar con un valor calculado.',
      ejemplo: `SELECT nombre, precio\nFROM productos\nWHERE precio > (SELECT AVG(precio) FROM productos)\nORDER BY precio;`,
      salida: "nombre | precio\nMonitor | 800.0\nLaptop | 2500.0",
      lecciones: ['m19-l4'],
    },
    {
      id: 'sql-cte',
      nombre: 'WITH (CTE)',
      grupo: 'Consultas avanzadas',
      firma: 'WITH nombre AS (SELECT ...) SELECT ... FROM nombre',
      resumen: 'Da nombre a un resultado intermedio y lo usa como si fuera una tabla; hace las consultas largas más legibles.',
      ejemplo: `WITH gasto AS (\n    SELECT c.nombre AS nombre, SUM(pe.cantidad * p.precio) AS total\n    FROM clientes c\n    JOIN pedidos pe ON pe.cliente_id = c.id\n    JOIN productos p ON p.id = pe.producto_id\n    GROUP BY c.id\n)\nSELECT nombre, total FROM gasto WHERE total > 2000 ORDER BY total DESC;`,
      salida: "nombre | total\nAna | 2750.0\nPedro | 2500.0",
      notas: ['Puedes encadenar varios CTE separados por comas.'],
      lecciones: ['m19-l4'],
    },
    {
      id: 'sql-window',
      nombre: 'Funciones de ventana (OVER)',
      grupo: 'Consultas avanzadas',
      firma: 'funcion() OVER (PARTITION BY col ORDER BY col)',
      resumen: 'Calculan sobre un conjunto de filas relacionadas (ranking, acumulados) sin colapsarlas en un grupo.',
      ejemplo: `SELECT nombre, precio,\n       RANK() OVER (ORDER BY precio DESC) AS posicion,\n       SUM(precio) OVER (ORDER BY precio) AS acumulado\nFROM productos\nORDER BY posicion;`,
      salida: "nombre | precio | posicion | acumulado\nLaptop | 2500.0 | 1 | 3620.0\nMonitor | 800.0 | 2 | 1120.0\nAudifonos | 150.0 | 3 | 320.0\nTeclado | 120.0 | 4 | 170.0\nMouse | 50.0 | 5 | 50.0",
      notas: ['Funciones útiles: ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD y las agregaciones (SUM, AVG) con OVER.'],
      lecciones: ['m19-l4'],
    },
    {
      id: 'sql-coalesce',
      nombre: 'COALESCE()',
      grupo: 'Consultas avanzadas',
      firma: 'COALESCE(valor1, valor2, ...)',
      resumen: 'Devuelve el primer valor que no es NULL: sirve para reemplazar nulos por un valor por defecto.',
      ejemplo: `SELECT c.nombre, COALESCE(SUM(pe.cantidad), 0) AS unidades\nFROM clientes c\nLEFT JOIN pedidos pe ON pe.cliente_id = c.id\nGROUP BY c.id\nORDER BY c.nombre;`,
      salida: "nombre | unidades\nAna | 4\nDiego | 0\nLuis | 5\nMarta | 7\nPedro | 1\nSofia | 4",
      relacionadas: ['pandas-fillna'],
      lecciones: ['m19-l3'],
    },

    // ───────────────────────── Funciones de texto, número y fecha ─────────────────────────
    {
      id: 'sql-text-functions',
      nombre: 'UPPER / LOWER / LENGTH / SUBSTR / REPLACE / ||',
      grupo: 'Funciones de texto, número y fecha',
      firma: 'UPPER(t) · LOWER(t) · LENGTH(t) · SUBSTR(t, inicio, largo) · REPLACE(t, viejo, nuevo) · t1 || t2',
      resumen: 'Funciones para trabajar con texto: mayúsculas, longitud, extraer un fragmento, reemplazar y concatenar (||).',
      ejemplo: `SELECT UPPER(nombre) AS mayus,\n       LENGTH(nombre) AS largo,\n       SUBSTR(nombre, 1, 3) AS inicio,\n       nombre || ' - ' || ciudad AS etiqueta\nFROM clientes\nLIMIT 3;`,
      salida: "mayus | largo | inicio | etiqueta\nANA | 3 | Ana | Ana - Bogota\nLUIS | 4 | Lui | Luis - Medellin\nMARTA | 5 | Mar | Marta - Bogota",
      notas: ['SUBSTR cuenta desde 1 (no desde 0 como Python).'],
      relacionadas: ['pandas-str-accessor'],
      lecciones: ['m19-l5'],
    },
    {
      id: 'sql-round',
      nombre: 'ROUND / ABS',
      grupo: 'Funciones de texto, número y fecha',
      firma: 'ROUND(valor, decimales) · ABS(valor)',
      resumen: 'Redondea un número a cierta cantidad de decimales y calcula valor absoluto.',
      ejemplo: `SELECT ROUND(AVG(precio), 1) AS promedio,\n       ROUND(SUM(precio) / COUNT(*), 0) AS redondeado\nFROM productos;`,
      salida: "promedio | redondeado\n724.0 | 724.0",
      lecciones: ['m19-l2'],
    },
    {
      id: 'sql-strftime',
      nombre: 'strftime() / date()',
      grupo: 'Funciones de texto, número y fecha',
      firma: "strftime(formato, fecha) · date(fecha, '+7 days')",
      resumen: 'Extrae partes de una fecha (año, mes…) o la calcula; en SQLite las fechas se guardan como texto "AAAA-MM-DD".',
      descripcion: 'Formatos: %Y año, %m mes, %d día, %w día de la semana (0 = domingo), %Y-%m año-mes.',
      ejemplo: `SELECT strftime('%Y-%m', fecha) AS mes,\n       COUNT(*) AS pedidos\nFROM pedidos\nGROUP BY mes\nORDER BY mes;\n\nSELECT date('2024-01-31', '+1 day') AS manana;`,
      salida: "mes | pedidos\n2024-01 | 3\n2024-02 | 4\n2024-03 | 3\nmanana\n2024-02-01",
      notas: ['En otros motores se usan EXTRACT, DATE_TRUNC o TO_CHAR en lugar de strftime.'],
      relacionadas: ['pandas-dt-accessor'],
      lecciones: ['m19-l5'],
    },

    // ───────────────────────── Crear y modificar datos ─────────────────────────
    {
      id: 'sql-create-table',
      nombre: 'CREATE TABLE',
      grupo: 'Crear y modificar datos',
      firma: 'CREATE TABLE nombre (columna TIPO [restricciones], ...)',
      resumen: 'Crea una tabla. Tipos habituales en SQLite: INTEGER, REAL (decimal), TEXT.',
      parametros: [
        { nombre: 'PRIMARY KEY', descripcion: 'Identifica de forma única cada fila.' },
        { nombre: 'NOT NULL', descripcion: 'La columna no admite valores nulos.' },
        { nombre: 'DEFAULT', descripcion: 'Valor que se usa si no se indica uno al insertar.' },
        { nombre: 'UNIQUE', descripcion: 'No permite valores repetidos en esa columna.' },
      ],
      ejemplo: `CREATE TABLE ciudades (\n    id INTEGER PRIMARY KEY,\n    nombre TEXT NOT NULL UNIQUE,\n    habitantes INTEGER DEFAULT 0\n);\nINSERT INTO ciudades (nombre, habitantes) VALUES ('Bogota', 7400000);\nSELECT * FROM ciudades;`,
      salida: "id | nombre | habitantes\n1 | Bogota | 7400000",
      lecciones: ['m19-l5'],
    },
    {
      id: 'sql-insert',
      nombre: 'INSERT INTO',
      grupo: 'Crear y modificar datos',
      firma: 'INSERT INTO tabla (col1, col2) VALUES (v1, v2), (v3, v4)',
      resumen: 'Agrega una o varias filas a una tabla.',
      ejemplo: `INSERT INTO clientes (id, nombre, ciudad, plan)\nVALUES (7, 'Lucia', 'Cali', 'Premium');\n\nSELECT nombre, ciudad FROM clientes WHERE id = 7;`,
      salida: "nombre | ciudad\nLucia | Cali",
      notas: ['Indica siempre las columnas: el código sigue funcionando si la tabla cambia de orden.'],
      lecciones: ['m19-l5'],
    },
    {
      id: 'sql-update',
      nombre: 'UPDATE',
      grupo: 'Crear y modificar datos',
      firma: 'UPDATE tabla SET col = valor [WHERE condicion]',
      resumen: 'Modifica los valores de filas existentes.',
      ejemplo: `UPDATE clientes SET plan = 'Premium' WHERE nombre = 'Luis';\n\nSELECT nombre, plan FROM clientes WHERE nombre = 'Luis';`,
      salida: "nombre | plan\nLuis | Premium",
      notas: ['⚠️ Sin WHERE modifica TODAS las filas de la tabla. Revisa la condición con un SELECT antes.'],
      lecciones: ['m19-l5'],
    },
    {
      id: 'sql-delete',
      nombre: 'DELETE',
      grupo: 'Crear y modificar datos',
      firma: 'DELETE FROM tabla [WHERE condicion]',
      resumen: 'Elimina filas de una tabla.',
      ejemplo: `DELETE FROM pedidos WHERE fecha < '2024-02-01';\n\nSELECT COUNT(*) AS pedidos_restantes FROM pedidos;`,
      salida: "pedidos_restantes\n7",
      notas: ['⚠️ Sin WHERE borra todas las filas. Prueba primero con un SELECT usando la misma condición.'],
      lecciones: ['m19-l5'],
    },
    {
      id: 'sql-parametros',
      nombre: 'Consultas parametrizadas (?)',
      grupo: 'Crear y modificar datos',
      firma: 'conn.execute("... WHERE col = ?", (valor,))',
      resumen: 'Pasa los valores aparte del texto SQL con marcadores ?, para evitar la inyección SQL.',
      ejemplo: `-- Desde Python (sqlite3):\n-- conn.execute("SELECT nombre FROM clientes WHERE ciudad = ?", ("Bogota",))\nSELECT nombre FROM clientes WHERE ciudad = 'Bogota';`,
      salida: "nombre\nAna\nMarta\nDiego",
      notas: ['Nunca construyas SQL pegando texto del usuario con f-strings: permite que un valor malicioso cambie la consulta.', 'Los marcadores solo sirven para valores, no para nombres de tablas o columnas.'],
      relacionadas: ['sql-where'],
      lecciones: ['m19-l5'],
    },
    {
      id: 'sql-index',
      nombre: 'CREATE INDEX',
      grupo: 'Crear y modificar datos',
      firma: 'CREATE INDEX nombre ON tabla (columna)',
      resumen: 'Crea un índice para acelerar las búsquedas y uniones por esa columna en tablas grandes.',
      ejemplo: `CREATE INDEX idx_pedidos_cliente ON pedidos (cliente_id);\nSELECT name FROM sqlite_master WHERE type = 'index' AND name = 'idx_pedidos_cliente';`,
      salida: "name\nidx_pedidos_cliente",
      notas: ['Un índice acelera las lecturas pero hace más lentas las escrituras: créalos donde de verdad filtras o unes.'],
      lecciones: ['m19-l5'],
    },
  ],
}
