import type { ColeccionRef } from './tipos'

export const terminalRef: ColeccionRef = {
  id: 'terminal',
  titulo: 'Terminal y Git',
  descripcion: 'Comandos de la línea de comandos (Linux/macOS) y de Git para versionar tu trabajo.',
  icono: '⌨️',
  lenguaje: 'bash',
  nota: 'Estos comandos se escriben en tu propia terminal (aquí no se ejecutan). Son los de Linux y macOS; en Windows funcionan igual dentro de WSL o Git Bash. El símbolo $ indica el prompt: no se escribe.',
  entradas: [
    // ───────────────────────── Navegar ─────────────────────────
    {
      id: 'terminal-pwd',
      nombre: 'pwd',
      grupo: 'Navegar',
      firma: 'pwd',
      resumen: 'Muestra en qué carpeta estás (print working directory).',
      ejemplo: `$ pwd\n/home/ana/proyecto`,
      lecciones: ['m20-l1'],
    },
    {
      id: 'terminal-ls',
      nombre: 'ls',
      grupo: 'Navegar',
      firma: 'ls [-l] [-a] [-h] [ruta]',
      resumen: 'Lista el contenido de una carpeta.',
      parametros: [
        { nombre: '-l', descripcion: 'Formato largo: permisos, tamaño y fecha.' },
        { nombre: '-a', descripcion: 'Incluye archivos ocultos (los que empiezan por punto).' },
        { nombre: '-h', descripcion: 'Con -l, muestra tamaños legibles (KB, MB).' },
      ],
      ejemplo: `$ ls\ndatos  src  README.md\n$ ls -lah\n$ ls *.csv`,
      lecciones: ['m20-l1'],
    },
    {
      id: 'terminal-cd',
      nombre: 'cd',
      grupo: 'Navegar',
      firma: 'cd [ruta]',
      resumen: 'Cambia de carpeta.',
      descripcion: '. es la carpeta actual, .. la carpeta padre, ~ tu carpeta personal y - la carpeta anterior.',
      ejemplo: `$ cd datos        # entra a la carpeta datos\n$ cd ..           # sube un nivel\n$ cd ~            # va a tu carpeta personal\n$ cd -            # vuelve a la anterior`,
      notas: ['Si el nombre tiene espacios, enciérralo entre comillas: cd "Mis Documentos".', 'Tab autocompleta nombres: úsalo siempre.'],
      lecciones: ['m20-l1'],
    },

    // ───────────────────────── Archivos y carpetas ─────────────────────────
    {
      id: 'terminal-mkdir',
      nombre: 'mkdir',
      grupo: 'Archivos y carpetas',
      firma: 'mkdir [-p] carpeta',
      resumen: 'Crea una carpeta.',
      parametros: [{ nombre: '-p', descripcion: 'Crea también las carpetas intermedias que falten y no da error si ya existe.' }],
      ejemplo: `$ mkdir datos\n$ mkdir -p proyecto/data/raw`,
      lecciones: ['m20-l2'],
    },
    {
      id: 'terminal-touch',
      nombre: 'touch',
      grupo: 'Archivos y carpetas',
      firma: 'touch archivo',
      resumen: 'Crea un archivo vacío (o actualiza la fecha de uno existente).',
      ejemplo: `$ touch notas.txt analisis.py`,
      lecciones: ['m20-l2'],
    },
    {
      id: 'terminal-cp',
      nombre: 'cp',
      grupo: 'Archivos y carpetas',
      firma: 'cp [-r] origen destino',
      resumen: 'Copia archivos o carpetas.',
      parametros: [{ nombre: '-r', descripcion: 'Copia carpetas completas (recursivo).' }],
      ejemplo: `$ cp ventas.csv copia.csv\n$ cp ventas_*.csv backup/\n$ cp -r datos datos_backup`,
      lecciones: ['m20-l2'],
    },
    {
      id: 'terminal-mv',
      nombre: 'mv',
      grupo: 'Archivos y carpetas',
      firma: 'mv origen destino',
      resumen: 'Mueve archivos o carpetas; también sirve para renombrarlos.',
      ejemplo: `$ mv viejo.csv nuevo.csv       # renombrar\n$ mv informe.pdf docs/         # mover a otra carpeta`,
      lecciones: ['m20-l2'],
    },
    {
      id: 'terminal-rm',
      nombre: 'rm',
      grupo: 'Archivos y carpetas',
      firma: 'rm [-r] [-i] archivo',
      resumen: 'Borra archivos o carpetas. No hay papelera: lo borrado no se recupera.',
      parametros: [
        { nombre: '-r', descripcion: 'Borra carpetas y todo su contenido (recursivo).' },
        { nombre: '-i', descripcion: 'Pide confirmación antes de borrar cada elemento.' },
      ],
      ejemplo: `$ rm notas.txt\n$ rm -i temporal.csv\n$ rm -r carpeta_vieja`,
      notas: ['⚠️ Un espacio de más cambia todo: "rm -r datos/ *" borra datos/ Y todo lo de la carpeta actual. Revisa con ls primero.'],
      lecciones: ['m20-l2'],
    },
    {
      id: 'terminal-wildcards',
      nombre: 'Comodines: * y ?',
      grupo: 'Archivos y carpetas',
      firma: '* (cualquier texto) · ? (un carácter)',
      resumen: 'Seleccionan varios archivos a la vez por su nombre.',
      ejemplo: `$ ls *.csv               # todos los CSV\n$ ls ventas_??.csv       # ventas_01.csv, ventas_02.csv…\n$ cp ventas_*.csv backup/`,
      lecciones: ['m20-l2'],
    },

    // ───────────────────────── Leer y buscar texto ─────────────────────────
    {
      id: 'terminal-cat',
      nombre: 'cat / head / tail',
      grupo: 'Leer y buscar texto',
      firma: 'cat archivo · head -n N archivo · tail -n N archivo',
      resumen: 'cat imprime un archivo entero; head muestra sus primeras líneas y tail las últimas.',
      ejemplo: `$ cat notas.txt\n$ head -n 5 ventas.csv        # primeras 5 líneas\n$ tail -n 3 log.txt          # últimas 3 líneas\n$ tail -f log.txt            # sigue el archivo en vivo`,
      lecciones: ['m20-l2'],
    },
    {
      id: 'terminal-wc',
      nombre: 'wc',
      grupo: 'Leer y buscar texto',
      firma: 'wc [-l] [-w] archivo',
      resumen: 'Cuenta líneas, palabras y caracteres.',
      parametros: [
        { nombre: '-l', descripcion: 'Solo líneas.' },
        { nombre: '-w', descripcion: 'Solo palabras.' },
      ],
      ejemplo: `$ wc -l ventas.csv\n1501 ventas.csv`,
      notas: ['En un CSV con encabezado, restar 1 da el número de registros.'],
      lecciones: ['m20-l2'],
    },
    {
      id: 'terminal-grep',
      nombre: 'grep',
      grupo: 'Leer y buscar texto',
      firma: 'grep [-i] [-c] [-n] [-r] [-v] "texto" archivo',
      resumen: 'Busca las líneas que contienen un texto o patrón.',
      parametros: [
        { nombre: '-i', descripcion: 'Ignora mayúsculas y minúsculas.' },
        { nombre: '-c', descripcion: 'Cuenta las líneas que coinciden en vez de mostrarlas.' },
        { nombre: '-n', descripcion: 'Muestra el número de cada línea.' },
        { nombre: '-r', descripcion: 'Busca recursivamente dentro de una carpeta.' },
        { nombre: '-v', descripcion: 'Invierte: muestra las líneas que NO coinciden.' },
      ],
      ejemplo: `$ grep "ERROR" log.txt\n$ grep -c "ERROR" log.txt\n$ grep -in "error" log.txt\n$ grep -r "TODO" src/`,
      lecciones: ['m20-l2'],
    },
    {
      id: 'terminal-sort-uniq',
      nombre: 'sort / uniq / cut',
      grupo: 'Leer y buscar texto',
      firma: 'sort [-n] [-r] · uniq [-c] · cut -d"," -f1',
      resumen: 'Ordena líneas, quita o cuenta repetidas y extrae columnas de un archivo delimitado.',
      ejemplo: `$ cut -d"," -f2 ventas.csv | sort | uniq -c    # cuántas veces aparece cada valor de la columna 2\n$ sort -n -r cifras.txt | head -3               # los 3 números más altos`,
      notas: ['uniq solo junta repetidos consecutivos: casi siempre se usa después de sort.'],
      lecciones: ['m20-l2'],
    },
    {
      id: 'terminal-pipe',
      nombre: '| (pipe) y redirección > >>',
      grupo: 'Leer y buscar texto',
      firma: 'comando1 | comando2 · comando > archivo · comando >> archivo',
      resumen: 'El pipe pasa la salida de un comando como entrada del siguiente; > guarda en un archivo (sobrescribe) y >> añade al final.',
      ejemplo: `$ grep "ERROR" log.txt | wc -l           # cuántos errores hay\n$ grep "ERROR" log.txt > errores.txt     # guarda las líneas\n$ echo "fin" >> errores.txt              # añade una línea`,
      notas: ['Es la idea más poderosa de la terminal: piezas pequeñas que se combinan.'],
      lecciones: ['m20-l2'],
    },

    // ───────────────────────── Programas y entorno ─────────────────────────
    {
      id: 'terminal-python',
      nombre: 'python script.py',
      grupo: 'Programas y entorno',
      firma: 'python script.py [argumentos] · python -m modulo',
      resumen: 'Ejecuta un script de Python; los argumentos se leen con argparse o sys.argv.',
      ejemplo: `$ python analisis.py --archivo ventas.csv --top 5\n$ python -m venv .venv          # crea un entorno virtual\n$ python --version`,
      relacionadas: ['python-argparse'],
      lecciones: ['m20-l3'],
    },
    {
      id: 'terminal-venv-pip',
      nombre: 'venv y pip',
      grupo: 'Programas y entorno',
      firma: 'python -m venv .venv · source .venv/bin/activate · pip install paquete · pip freeze > requirements.txt',
      resumen: 'Un entorno virtual aísla las bibliotecas de cada proyecto; pip instala paquetes en él.',
      ejemplo: `$ python -m venv .venv\n$ source .venv/bin/activate        # en Windows: .venv\\Scripts\\activate\n$ pip install pandas scikit-learn\n$ pip freeze > requirements.txt   # guarda las versiones\n$ pip install -r requirements.txt # reinstala todo en otra máquina`,
      lecciones: ['m0-l2'],
    },
    {
      id: 'terminal-env',
      nombre: 'export / echo $VARIABLE',
      grupo: 'Programas y entorno',
      firma: 'export NOMBRE=valor · echo $NOMBRE',
      resumen: 'Define y lee variables de entorno: el lugar adecuado para claves y configuración sensibles.',
      ejemplo: `$ export API_KEY=abc123\n$ echo $API_KEY\nabc123`,
      notas: ['Desde Python se leen con os.environ.get("API_KEY"). Nunca escribas claves dentro del código ni las subas a Git.'],
      lecciones: ['m20-l3'],
    },
    {
      id: 'terminal-man-help',
      nombre: '--help / man / history',
      grupo: 'Programas y entorno',
      firma: 'comando --help · man comando · history',
      resumen: 'Ayuda del propio comando, manual completo y lista de comandos usados antes.',
      ejemplo: `$ grep --help\n$ man ls            # q para salir\n$ history | tail -5`,
      notas: ['Atajos: Tab autocompleta, ↑ recupera el comando anterior, Ctrl+C cancela, Ctrl+R busca en el historial.'],
      lecciones: ['m20-l3'],
    },

    // ───────────────────────── Git: empezar ─────────────────────────
    {
      id: 'terminal-git-config',
      nombre: 'git config',
      grupo: 'Git: empezar',
      firma: 'git config --global user.name "Nombre" · git config --global user.email "correo"',
      resumen: 'Configura quién eres; aparecerá en cada commit que hagas.',
      ejemplo: `$ git config --global user.name "Ana Perez"\n$ git config --global user.email "ana@correo.com"\n$ git config --list`,
      lecciones: ['m20-l4'],
    },
    {
      id: 'terminal-git-init',
      nombre: 'git init / git clone',
      grupo: 'Git: empezar',
      firma: 'git init · git clone URL',
      resumen: 'init convierte la carpeta actual en un repositorio nuevo; clone copia un repositorio remoto (p. ej. de GitHub).',
      ejemplo: `$ git init\n$ git clone https://github.com/usuario/proyecto.git`,
      lecciones: ['m20-l4', 'm20-l5'],
    },

    // ───────────────────────── Git: el ciclo diario ─────────────────────────
    {
      id: 'terminal-git-status',
      nombre: 'git status',
      grupo: 'Git: el ciclo diario',
      firma: 'git status',
      resumen: 'Muestra qué archivos cambiaron, cuáles están preparados (staging) y cuáles no se rastrean.',
      ejemplo: `$ git status`,
      notas: ['Úsalo con frecuencia: te dice siempre en qué punto estás y qué falta.'],
      lecciones: ['m20-l4'],
    },
    {
      id: 'terminal-git-add',
      nombre: 'git add',
      grupo: 'Git: el ciclo diario',
      firma: 'git add archivo · git add . · git add -p',
      resumen: 'Prepara cambios (staging) para incluirlos en el próximo commit.',
      parametros: [
        { nombre: '.', descripcion: 'Prepara todo lo que cambió en la carpeta actual.' },
        { nombre: '-p', descripcion: 'Elige trozo por trozo qué cambios preparar.' },
      ],
      ejemplo: `$ git add analisis.py\n$ git add .`,
      notas: ['Antes de "git add ." revisa git status: así evitas subir archivos de datos pesados o secretos.'],
      lecciones: ['m20-l4'],
    },
    {
      id: 'terminal-git-commit',
      nombre: 'git commit',
      grupo: 'Git: el ciclo diario',
      firma: 'git commit -m "mensaje" · git commit -am "mensaje"',
      resumen: 'Guarda una "fotografía" de lo preparado, con un mensaje que explica el cambio.',
      parametros: [
        { nombre: '-m', descripcion: 'Mensaje del commit.' },
        { nombre: '-a', descripcion: 'Prepara automáticamente los archivos ya rastreados que cambiaron (no incluye archivos nuevos).' },
      ],
      ejemplo: `$ git commit -m "Agrega limpieza de datos nulos"`,
      notas: ['Buen mensaje: corto, en imperativo y descriptivo. "cambios" o "arreglos" no ayudan a nadie.'],
      lecciones: ['m20-l4'],
    },
    {
      id: 'terminal-git-log',
      nombre: 'git log',
      grupo: 'Git: el ciclo diario',
      firma: 'git log [--oneline] [--graph] [-n N]',
      resumen: 'Muestra el historial de commits.',
      ejemplo: `$ git log --oneline\n7f9ae36 Agrega Modulos 12-13\n48d9959 Agrega Ruta 2\n44b69de Scaffold inicial`,
      lecciones: ['m20-l4'],
    },
    {
      id: 'terminal-git-diff',
      nombre: 'git diff',
      grupo: 'Git: el ciclo diario',
      firma: 'git diff · git diff --staged',
      resumen: 'Muestra línea por línea qué cambió (diff) respecto al último commit; --staged revisa lo ya preparado.',
      ejemplo: `$ git diff\n$ git diff --staged`,
      lecciones: ['m20-l4'],
    },
    {
      id: 'terminal-git-restore',
      nombre: 'git restore / git reset',
      grupo: 'Git: el ciclo diario',
      firma: 'git restore archivo · git restore --staged archivo',
      resumen: 'restore descarta cambios no guardados de un archivo; --staged lo saca del área de preparación sin perder los cambios.',
      ejemplo: `$ git restore --staged analisis.py   # deshace el git add\n$ git restore analisis.py            # descarta los cambios (¡no se recuperan!)`,
      notas: ['⚠️ restore sin --staged borra tus cambios locales de ese archivo de forma definitiva.'],
      lecciones: ['m20-l4'],
    },

    // ───────────────────────── Git: ramas ─────────────────────────
    {
      id: 'terminal-git-branch',
      nombre: 'git branch / git switch',
      grupo: 'Git: ramas',
      firma: 'git branch · git switch -c nueva-rama · git switch rama',
      resumen: 'Una rama es una línea independiente de trabajo; branch las lista y switch cambia (o crea con -c) de rama.',
      ejemplo: `$ git branch\n$ git switch -c nueva-limpieza\n$ git switch main`,
      notas: ['Técnicamente una rama es solo un puntero a un commit: crearla es instantáneo.'],
      lecciones: ['m20-l5'],
    },
    {
      id: 'terminal-git-merge',
      nombre: 'git merge',
      grupo: 'Git: ramas',
      firma: 'git merge rama',
      resumen: 'Incorpora a la rama actual los cambios de otra rama.',
      ejemplo: `$ git switch main\n$ git merge nueva-limpieza`,
      notas: ['Si ambas ramas cambiaron las mismas líneas hay un conflicto: edita el archivo, elige qué conservar, y haz git add + git commit.'],
      lecciones: ['m20-l5'],
    },

    // ───────────────────────── Git: trabajar con GitHub ─────────────────────────
    {
      id: 'terminal-git-remote',
      nombre: 'git remote',
      grupo: 'Git: trabajar con GitHub',
      firma: 'git remote -v · git remote add origin URL',
      resumen: 'Muestra o configura el repositorio remoto (normalmente llamado origin).',
      ejemplo: `$ git remote add origin https://github.com/usuario/proyecto.git\n$ git remote -v`,
      lecciones: ['m20-l5'],
    },
    {
      id: 'terminal-git-push-pull',
      nombre: 'git push / git pull / git fetch',
      grupo: 'Git: trabajar con GitHub',
      firma: 'git push [-u origin rama] · git pull · git fetch',
      resumen: 'push sube tus commits al remoto; pull trae y fusiona los cambios del remoto; fetch solo los descarga.',
      ejemplo: `$ git push -u origin main        # la primera vez (-u enlaza la rama)\n$ git push\n$ git pull`,
      notas: ['Flujo de colaboración: rama → commits → push → Pull Request → revisión → merge a main.'],
      lecciones: ['m20-l5'],
    },
    {
      id: 'terminal-gitignore',
      nombre: '.gitignore',
      grupo: 'Git: trabajar con GitHub',
      firma: 'archivo .gitignore en la raíz del repositorio',
      resumen: 'Lista de archivos y patrones que Git debe ignorar: secretos, datos pesados y archivos generados.',
      ejemplo: `# .gitignore\n*.pyc\n__pycache__/\n.env\n.venv/\ndatos_privados.csv\n.ipynb_checkpoints/`,
      notas: ['Créalo ANTES del primer commit. Una clave subida por error sigue en el historial aunque borres el archivo: revócala y crea una nueva.'],
      lecciones: ['m20-l5'],
    },
  ],
}
