import type { Lesson } from '../../types'

export const module41Lessons: Lesson[] = [
  {
    id: "m41-l1",
    moduloId: "modulo-41",
    titulo: "Modificar datos: INSERT, UPDATE, DELETE, transacciones y upsert",
    objetivo: "Insertar, actualizar y borrar filas con seguridad, agrupar cambios en transacciones y resolver conflictos con ON CONFLICT (upsert).",
    porQueImporta:
      "Un analista rara vez modifica las tablas de producción, pero sí prepara tablas de trabajo, corrige cargas y automatiza procesos. Un `UPDATE` o un `DELETE` sin `WHERE` es uno de los errores más temidos en el trabajo con bases de datos: conviene aprender el hábito seguro desde el principio.",
    concepto: "Las sentencias que modifican datos:\n\n- `INSERT INTO tabla (col1, col2) VALUES (v1, v2)`: añade filas. Indicar las columnas hace el código robusto a cambios en la tabla.\n- `UPDATE tabla SET col = valor WHERE condicion`: modifica las filas que cumplen la condición.\n- `DELETE FROM tabla WHERE condicion`: borra filas.\n\n**Regla de oro**: escribe primero el `WHERE` como un `SELECT` y compruébalo; solo entonces conviértelo en `UPDATE` o `DELETE`. Sin `WHERE`, la sentencia afecta a **todas** las filas.\n\n**Desde Python**, usa parámetros (`?`) en lugar de armar el texto con f-strings, para evitar errores de comillas y ataques de inyección SQL: `conn.executemany(\"INSERT INTO clientes VALUES (?, ?, ?, ?)\", lista_de_tuplas)`. `cursor.rowcount` indica cuántas filas afectó una sentencia.\n\n**Transacciones**: un grupo de cambios que se confirman o se descartan juntos. `conn.commit()` los guarda definitivamente y `conn.rollback()` los deshace. Así, si algo falla a mitad de una carga, la base no queda a medias. (Nuestra base de práctica vive solo en memoria y desaparece al terminar el programa.)\n\n**Upsert** («insertar o actualizar»): si la fila ya existe, actualizarla en lugar de dar error:\n\n```sql\nINSERT INTO productos (id, nombre, categoria, precio) VALUES (2, 'Mouse', 'Accesorios', 60)\nON CONFLICT(id) DO UPDATE SET precio = excluded.precio\n```\n\n`excluded` representa la fila que se intentaba insertar. Esta sintaxis existe en SQLite (desde 3.24) y PostgreSQL. Otros motores lo hacen distinto: `MERGE` en SQL Server, Oracle y PostgreSQL 15+, o `ON DUPLICATE KEY UPDATE` en MySQL.",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.execute(\"INSERT INTO clientes (id, nombre, ciudad, plan) VALUES (7, 'Laura', 'Cali', 'Basico')\")\nprint(conn.execute(\"SELECT COUNT(*) FROM clientes\").fetchone()[0])",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nnuevos = [(7, 'Laura', 'Cali', 'Basico'), (8, 'Omar', 'Cali', 'Estandar')]\nconn.executemany(\"INSERT INTO clientes VALUES (?, ?, ?, ?)\", nuevos)\n\ncur = conn.execute(\"UPDATE clientes SET plan = 'Premium' WHERE ciudad = 'Cali'\")\nprint(\"filas actualizadas:\", cur.rowcount)\nconn.commit()          # los cambios anteriores quedan guardados\n\nconn.execute(\"DELETE FROM pedidos\")\nprint(\"pedidos tras DELETE:\", conn.execute(\"SELECT COUNT(*) FROM pedidos\").fetchone()[0])\nconn.rollback()        # deshace el DELETE\nprint(\"pedidos tras rollback:\", conn.execute(\"SELECT COUNT(*) FROM pedidos\").fetchone()[0])",
    errorFrecuente: {
      codigo: "UPDATE productos SET precio = 0      -- sin WHERE: cambia los 5 productos\nUPDATE productos SET precio = 0 WHERE id = 2",
      explicacion:
        "Sin `WHERE`, `UPDATE` y `DELETE` afectan a todas las filas. En una base real eso puede significar horas de recuperación de copias de seguridad. Antes de modificar, ejecuta un `SELECT` con el mismo `WHERE` y revisa cuántas filas devuelve; y en el trabajo real, haz los cambios dentro de una transacción para poder deshacerlos.",
    },
    practicaGuiada: {
      id: "m41-l1-practica",
      enunciado: "Sube un **10 %** el precio de los productos de la categoría `Accesorios` con un `UPDATE` (redondea a 2 decimales con `ROUND(precio * 1.1, 2)`). Escribe la sentencia en `sql`; el programa imprime los precios resultantes.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu UPDATE\nif sql:\n    conn.execute(sql)\nprint(conn.execute(\"SELECT nombre, precio FROM productos ORDER BY id\").fetchall())",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"UPDATE productos SET precio = ROUND(precio * 1.1, 2) WHERE categoria = 'Accesorios'\"\nif sql:\n    conn.execute(sql)\nprint(conn.execute(\"SELECT nombre, precio FROM productos ORDER BY id\").fetchall())",
      pistas: ["`UPDATE productos SET precio = ROUND(precio * 1.1, 2) WHERE categoria = ...`", "No olvides el `WHERE`: solo deben cambiar los `Accesorios`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Laptop', 2500.0), ('Mouse', 55.0), ('Teclado', 132.0), ('Monitor', 800.0), ('Audifonos', 165.0)]\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: [('Laptop', 2500.0), ('Mouse', 55.0), ('Teclado', 132.0), ('Monitor', 800.0), ('Audifonos', 165.0)]" }
      },
    },
    reto: {
      id: "m41-l1-reto",
      enunciado: "Escribe dos **upserts** sobre `productos`: (1) en `sql_mouse`, el producto `2` (`Mouse`, `Accesorios`) con precio `60`, que ya existe y debe actualizar su precio; (2) en `sql_nuevo`, el producto nuevo `6` (`Webcam`, `Accesorios`, precio `200`). Ambos con `INSERT ... ON CONFLICT(id) DO UPDATE SET precio = excluded.precio`.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql_mouse = \"\"   # upsert del Mouse (id 2) con precio 60\nsql_nuevo = \"\"   # upsert de la Webcam (id 6) con precio 200\nfor sql in (sql_mouse, sql_nuevo):\n    if sql:\n        conn.execute(sql)\nprint(conn.execute(\"SELECT id, nombre, precio FROM productos WHERE id IN (2, 6) ORDER BY id\").fetchall())",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql_mouse = \"\"\"INSERT INTO productos (id, nombre, categoria, precio) VALUES (2, 'Mouse', 'Accesorios', 60)\nON CONFLICT(id) DO UPDATE SET precio = excluded.precio\"\"\"\nsql_nuevo = \"\"\"INSERT INTO productos (id, nombre, categoria, precio) VALUES (6, 'Webcam', 'Accesorios', 200)\nON CONFLICT(id) DO UPDATE SET precio = excluded.precio\"\"\"\nfor sql in (sql_mouse, sql_nuevo):\n    if sql:\n        conn.execute(sql)\nprint(conn.execute(\"SELECT id, nombre, precio FROM productos WHERE id IN (2, 6) ORDER BY id\").fetchall())",
      pistas: ["`INSERT INTO productos (id, nombre, categoria, precio) VALUES (2, 'Mouse', 'Accesorios', 60)`", "Añade `ON CONFLICT(id) DO UPDATE SET precio = excluded.precio`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[(2, 'Mouse', 60.0), (6, 'Webcam', 200.0)]\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: [(2, 'Mouse', 60.0), (6, 'Webcam', 200.0)]" }
      },
    },
    verificacion: [
      {
        id: "m41-l1-q1",
        pregunta: "¿Qué pasa si ejecutas `DELETE FROM clientes` sin `WHERE`?",
        opciones: ["No borra nada", "Borra todas las filas de la tabla", "Da un error", "Borra solo la primera fila"],
        respuestaCorrecta: 1,
        explicacion: "Sin condición la sentencia afecta a todas las filas. Prueba siempre el `WHERE` con un `SELECT` antes.",
      },
      {
        id: "m41-l1-q2",
        pregunta: "¿Para qué sirve `conn.rollback()`?",
        opciones: ["Para guardar los cambios", "Para deshacer los cambios de la transacción actual", "Para cerrar la conexión", "Para ordenar los datos"],
        respuestaCorrecta: 1,
        explicacion: "`commit()` confirma y `rollback()` descarta los cambios pendientes de la transacción.",
      },
      {
        id: "m41-l1-q3",
        pregunta: "¿Por qué conviene usar parámetros `?` en lugar de f-strings en las consultas?",
        opciones: ["Es más rápido de escribir", "Evita errores de comillas y la inyección SQL", "Porque SQL no admite texto", "No hay ninguna razón"],
        respuestaCorrecta: 1,
        explicacion: "Los parámetros envían los valores por separado del texto de la consulta: el motor nunca interpreta el dato como código.",
      },
    ],
    resumen: ["Escribe el `WHERE` como `SELECT` antes de convertirlo en `UPDATE` o `DELETE`.", "`commit` guarda y `rollback` deshace una transacción.", "`ON CONFLICT ... DO UPDATE` (upsert) evita errores por claves repetidas; otros motores usan `MERGE` o `ON DUPLICATE KEY`."],
    proximoPaso: "Veremos cómo guardar consultas como vistas y cómo los índices aceleran las búsquedas.",
    conceptos: ["insert-update-delete", "transacciones", "upsert"],
  },
  {
    id: "m41-l2",
    moduloId: "modulo-41",
    titulo: "Vistas, tablas derivadas e índices",
    objetivo: "Guardar consultas como vistas, materializar resultados con CREATE TABLE AS y entender cuándo un índice acelera una consulta usando EXPLAIN QUERY PLAN.",
    porQueImporta:
      "Una consulta compleja que usas todos los días merece un nombre. Y cuando las tablas crecen a millones de filas, la diferencia entre una consulta que usa un índice y una que recorre toda la tabla es la diferencia entre milisegundos y minutos.",
    concepto: "**Vista** (`CREATE VIEW nombre AS SELECT ...`): una consulta guardada con nombre que se usa como si fuera una tabla. No almacena datos: cada vez que la consultas, se ejecuta el `SELECT` y refleja el estado actual de las tablas. Sirve para simplificar consultas repetidas y para dar a otros acceso a una versión limpia de los datos. Para reemplazarla en SQLite: `DROP VIEW IF EXISTS nombre` y volver a crearla (`CREATE OR REPLACE VIEW` existe en PostgreSQL y MySQL, no en SQLite).\n\n**Tabla derivada** (`CREATE TABLE nombre AS SELECT ...`): guarda el *resultado* de una consulta como una tabla nueva. A diferencia de una vista, es una foto: no se actualiza sola. Útil para resúmenes costosos que se consultan muchas veces.\n\n**Índice** (`CREATE INDEX nombre ON tabla(columna)`): una estructura auxiliar, ordenada, que permite encontrar filas por esa columna sin recorrer toda la tabla (como el índice de un libro).\n\n- **Acelera** los filtros (`WHERE col = ...`), los `JOIN` y los `ORDER BY` por la columna indexada.\n- **Cuesta**: ocupa espacio y hace más lentas las escrituras (`INSERT`, `UPDATE`), porque hay que mantenerlo al día. No indexes todo.\n- No siempre se usa: si aplicas una función a la columna (`WHERE strftime('%m', fecha) = '02'`) o buscas con comodín al inicio (`LIKE '%texto'`), el motor no puede aprovechar el índice.\n\nPara ver cómo ejecuta el motor una consulta, usa el plan de ejecución: `EXPLAIN QUERY PLAN` en SQLite (en PostgreSQL y MySQL se escribe `EXPLAIN`). Verás `SCAN tabla` (recorre todo) o `SEARCH tabla USING INDEX ...` (usa el índice). Con 10 filas no hay diferencia perceptible; el efecto aparece con volúmenes grandes.",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.execute(\"\"\"\nCREATE VIEW ingreso_pedido AS\nSELECT p.id AS pedido, p.fecha, p.cantidad * pr.precio AS importe\nFROM pedidos p JOIN productos pr ON pr.id = p.producto_id\n\"\"\")\nprint(conn.execute(\"SELECT * FROM ingreso_pedido ORDER BY importe DESC LIMIT 3\").fetchall())",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\ndef plan(sql):\n    return [fila[3] for fila in conn.execute(\"EXPLAIN QUERY PLAN \" + sql)]\n\nconsulta = \"SELECT * FROM pedidos WHERE cliente_id = 1\"\nprint(\"antes:  \", plan(consulta))\n\nconn.execute(\"CREATE INDEX idx_pedidos_cliente ON pedidos(cliente_id)\")\nprint(\"después:\", plan(consulta))",
    errorFrecuente: {
      codigo: "CREATE INDEX idx_fecha ON pedidos(fecha)\nSELECT * FROM pedidos WHERE strftime('%m', fecha) = '02'   -- el plan sigue siendo SCAN: no puede usar el índice\nSELECT * FROM pedidos WHERE fecha >= '2024-02-01' AND fecha < '2024-03-01'   -- SEARCH: sí lo usa",
      explicacion:
        "Si aplicas una función a la columna dentro del `WHERE` (`strftime(...)`, `UPPER(...)`, `YEAR(...)`), el motor debe calcularla fila por fila y no puede usar el índice de esa columna. Reescribe el filtro como un rango sobre la columna sin transformar.",
    },
    practicaGuiada: {
      id: "m41-l2-practica",
      enunciado: "Crea una **vista** llamada `ingreso_cliente` con las columnas `nombre` (del cliente) e `ingreso` (suma de `cantidad * precio` de sus pedidos). Escribe el `CREATE VIEW` en `sql`; el programa consulta la vista ordenada por ingreso.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu CREATE VIEW\nif sql:\n    conn.execute(sql)\n    print(conn.execute(\"SELECT nombre, ingreso FROM ingreso_cliente ORDER BY ingreso DESC, nombre\").fetchall())",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nCREATE VIEW ingreso_cliente AS\nSELECT c.nombre AS nombre, SUM(p.cantidad * pr.precio) AS ingreso\nFROM pedidos p\nJOIN clientes c ON c.id = p.cliente_id\nJOIN productos pr ON pr.id = p.producto_id\nGROUP BY c.id, c.nombre\n\"\"\"\nif sql:\n    conn.execute(sql)\n    print(conn.execute(\"SELECT nombre, ingreso FROM ingreso_cliente ORDER BY ingreso DESC, nombre\").fetchall())",
      pistas: ["`CREATE VIEW ingreso_cliente AS SELECT ...`", "Une `pedidos`, `clientes` y `productos` y agrupa por cliente."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Ana', 2750.0), ('Pedro', 2500.0), ('Marta', 1850.0), ('Sofia', 1250.0), ('Luis', 320.0)]\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: [('Ana', 2750.0), ('Pedro', 2500.0), ('Marta', 1850.0), ('Sofia', 1250.0), ('Luis', 320.0)]" }
      },
    },
    reto: {
      id: "m41-l2-reto",
      enunciado: "Crea un **índice** llamado `idx_pedidos_producto` sobre `pedidos(producto_id)` y comprueba con `EXPLAIN QUERY PLAN` que la consulta `WHERE producto_id = 2` lo usa. El programa imprime `True` cuando el plan menciona tu índice.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu CREATE INDEX\nif sql:\n    conn.execute(sql)\n\nplan = \" \".join(fila[3] for fila in conn.execute(\"EXPLAIN QUERY PLAN SELECT * FROM pedidos WHERE producto_id = 2\"))\nprint(\"idx_pedidos_producto\" in plan)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"CREATE INDEX idx_pedidos_producto ON pedidos(producto_id)\"\nif sql:\n    conn.execute(sql)\n\nplan = \" \".join(fila[3] for fila in conn.execute(\"EXPLAIN QUERY PLAN SELECT * FROM pedidos WHERE producto_id = 2\"))\nprint(\"idx_pedidos_producto\" in plan)",
      pistas: ["`CREATE INDEX idx_pedidos_producto ON pedidos(producto_id)`"],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"True\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: True" }
      },
    },
    verificacion: [
      {
        id: "m41-l2-q1",
        pregunta: "¿Cuál es la diferencia entre una vista y `CREATE TABLE AS`?",
        opciones: ["Ninguna", "La vista se recalcula en cada consulta; la tabla guarda una copia fija del resultado", "La tabla se recalcula sola", "La vista no admite `JOIN`"],
        respuestaCorrecta: 1,
        explicacion: "La vista guarda la consulta; la tabla creada con `AS` guarda los datos del momento en que se creó.",
      },
      {
        id: "m41-l2-q2",
        pregunta: "¿Qué inconveniente tiene crear muchos índices?",
        opciones: ["Hacen más lentas las consultas", "Ocupan espacio y ralentizan `INSERT` y `UPDATE`", "No se pueden borrar", "Cambian los datos"],
        respuestaCorrecta: 1,
        explicacion: "El índice debe mantenerse actualizado con cada escritura. Indexa las columnas que realmente filtras o unes.",
      },
      {
        id: "m41-l2-q3",
        pregunta: "¿Por qué `WHERE strftime('%m', fecha) = '02'` no aprovecha un índice sobre `fecha`?",
        opciones: ["Porque `fecha` es texto", "Porque aplica una función a la columna", "Porque usa `=`", "Porque el índice es ascendente"],
        respuestaCorrecta: 1,
        explicacion: "El índice ordena los valores originales; con una función, el motor tiene que calcular cada fila. Usa un rango: `fecha >= ... AND fecha < ...`.",
      },
    ],
    resumen: ["Una vista guarda una consulta; `CREATE TABLE AS` guarda su resultado.", "Un índice acelera búsquedas, uniones y ordenamientos, pero cuesta espacio y escrituras.", "`EXPLAIN QUERY PLAN` muestra si el motor recorre la tabla (`SCAN`) o usa el índice (`SEARCH`)."],
    proximoPaso: "Cerraremos el módulo con un mapa de qué cambia entre SQLite, PostgreSQL, SQL Server y MySQL.",
    conceptos: ["vistas", "indices", "explain"],
  },
  {
    id: "m41-l3",
    moduloId: "modulo-41",
    titulo: "De SQLite a tu motor: qué cambia entre PostgreSQL, SQL Server y MySQL",
    objetivo: "Saber qué parte del SQL es estándar y portable, qué cambia de nombre entre motores y cómo reproducir en SQLite funciones como DATE_TRUNC, PIVOT, ROLLUP o QUALIFY.",
    porQueImporta:
      "El SQL que aprendes aquí es portable en su mayoría, pero en una empresa trabajarás con PostgreSQL, SQL Server, MySQL, BigQuery o Snowflake, y cada uno tiene sus propias funciones y su sintaxis. Saber qué es estándar y qué es específico te ahorra confusiones y te permite adaptarte rápido.",
    concepto: "**Lo que funciona igual casi en todas partes** (y que ya practicaste): `SELECT`, `WHERE`, `GROUP BY`, `HAVING`, `ORDER BY`, todos los `JOIN`, `UNION`/`INTERSECT`/`EXCEPT`, subconsultas, `CASE`, `COALESCE`, `NULLIF`, `CAST`, CTE (`WITH`), funciones de ventana (`ROW_NUMBER`, `RANK`, `LAG`, `SUM() OVER`…) y `INSERT`/`UPDATE`/`DELETE`.\n\n**Lo que cambia de nombre o de sintaxis** (y su equivalente en SQLite):\n\n- Limitar filas: `LIMIT n` (SQLite, PostgreSQL, MySQL); `TOP n` o `OFFSET … FETCH` (SQL Server); `FETCH FIRST n ROWS ONLY` (Oracle y estándar).\n- Búsqueda sin distinguir mayúsculas: `ILIKE` (PostgreSQL). En SQLite: `LOWER(col) LIKE '...'` o el propio `LIKE`.\n- Unir texto de un grupo: `STRING_AGG` (PostgreSQL, SQL Server), `GROUP_CONCAT` (MySQL), `group_concat` (SQLite).\n- Fechas: `DATE_TRUNC('month', f)` y `EXTRACT(...)` (PostgreSQL), `DATEPART`/`DATEDIFF` (SQL Server), `DATE_FORMAT` (MySQL). En SQLite: `date(f, 'start of month')` y `strftime`.\n- Concatenar: `||` (estándar, SQLite, PostgreSQL), `+` (SQL Server), `CONCAT()` (MySQL, SQL Server).\n- Menor y mayor de varios valores: `GREATEST`/`LEAST` (PostgreSQL, MySQL). En SQLite: `MAX(a, b)` y `MIN(a, b)`.\n\n**Lo que SQLite no trae** (y cómo se reproduce):\n\n- `ROLLUP`, `CUBE`, `GROUPING SETS` (subtotales): `UNION ALL` de varias agregaciones.\n- `PIVOT` / `UNPIVOT` (SQL Server, Oracle, Snowflake): `SUM(CASE WHEN ...)` y `UNION ALL`.\n- `QUALIFY` (Snowflake, BigQuery, DuckDB, Teradata): una CTE con la función de ventana y un `WHERE` fuera.\n- `MERGE` (SQL Server, Oracle, PostgreSQL 15+): `INSERT ... ON CONFLICT`.\n- `PERCENTILE_CONT` / `PERCENTILE_DISC` (PostgreSQL, SQL Server, Oracle): `NTILE` o cálculo en pandas.\n- Procedimientos almacenados, usuarios y permisos: son parte del servidor de base de datos.\n\n**Recomendación de estudio**: cuando cambies de motor, no empieces de cero; busca en su documentación «cómo hago X» para cada cosa de esta lista. Y para todo lo que sea T-SQL (SQL Server) o PL/pgSQL, hace falta practicar en un servidor real, algo que este curso en el navegador no puede ofrecer.",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT nombre FROM clientes WHERE LOWER(nombre) LIKE 'a%' OR LOWER(nombre) LIKE 's%' ORDER BY nombre\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\n-- QUALIFY pos <= 2, escrito con una CTE\nWITH r AS (\n    SELECT pr.categoria, pr.nombre, SUM(p.cantidad * pr.precio) AS ingreso,\n           RANK() OVER (PARTITION BY pr.categoria ORDER BY SUM(p.cantidad * pr.precio) DESC) AS pos\n    FROM pedidos p JOIN productos pr ON pr.id = p.producto_id\n    GROUP BY pr.categoria, pr.nombre\n)\nSELECT categoria, nombre, ingreso, pos FROM r WHERE pos <= 2 ORDER BY categoria, pos\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "SELECT TOP 3 nombre FROM clientes           -- sintaxis de SQL Server: en SQLite es un error\nSELECT nombre FROM clientes LIMIT 3          -- SQLite, PostgreSQL y MySQL\nSELECT nombre FROM clientes ILIKE 'a%'       -- solo PostgreSQL",
      explicacion:
        "Copiar una consulta de internet sin saber para qué motor está escrita es la causa más común de errores de sintaxis. Antes de pegarla, identifica el motor y comprueba las partes que cambian: límite de filas, fechas, concatenación y funciones de texto.",
    },
    practicaGuiada: {
      id: "m41-l3-practica",
      enunciado: "Reproduce `DATE_TRUNC('month', fecha)` de PostgreSQL: cuenta los pedidos por mes usando `date(fecha, 'start of month')` (devuelve el primer día de cada mes). Columnas: `mes` y `pedidos`, ordenadas por mes.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT date(fecha, 'start of month') AS mes, COUNT(*) AS pedidos FROM pedidos GROUP BY mes ORDER BY mes\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["`date(fecha, 'start of month')` da `2024-01-01`, `2024-02-01`…", "Agrupa por ese alias."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('2024-01-01', 3), ('2024-02-01', 4), ('2024-03-01', 3)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('2024-01-01', 3), ('2024-02-01', 4), ('2024-03-01', 3)]" }
      },
    },
    reto: {
      id: "m41-l3-reto",
      enunciado: "Reproduce un `PIVOT` con `SUM(CASE WHEN ...)`: para cada ciudad, calcula las **unidades** (`cantidad`) compradas de `Accesorios` y de `Electronica` en dos columnas (`accesorios` y `electronica`), ordenadas por ciudad.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT c.ciudad,\n       SUM(CASE WHEN pr.categoria = 'Accesorios' THEN p.cantidad ELSE 0 END) AS accesorios,\n       SUM(CASE WHEN pr.categoria = 'Electronica' THEN p.cantidad ELSE 0 END) AS electronica\nFROM pedidos p\nJOIN clientes c ON c.id = p.cliente_id\nJOIN productos pr ON pr.id = p.producto_id\nGROUP BY c.ciudad\nORDER BY c.ciudad\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Une `pedidos`, `clientes` y `productos`.", "Una columna `SUM(CASE ...)` por categoría."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Bogota', 8, 3), ('Cali', 0, 1), ('Medellin', 8, 1)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Bogota', 8, 3), ('Cali', 0, 1), ('Medellin', 8, 1)]" }
      },
    },
    verificacion: [
      {
        id: "m41-l3-q1",
        pregunta: "¿Qué cláusula de otros motores se reproduce en SQLite con una CTE y un `WHERE` fuera?",
        opciones: ["`LIMIT`", "`QUALIFY`", "`HAVING`", "`ORDER BY`"],
        respuestaCorrecta: 1,
        explicacion: "`QUALIFY` filtra por funciones de ventana; en SQLite se calcula la función en una CTE y se filtra en la consulta externa.",
      },
      {
        id: "m41-l3-q2",
        pregunta: "¿Cómo se limitan las filas en SQL Server?",
        opciones: ["`LIMIT 3`", "`TOP 3` o `OFFSET ... FETCH`", "`FETCH 3`", "`ROWNUM`"],
        respuestaCorrecta: 1,
        explicacion: "SQL Server usa `SELECT TOP 3 ...` o `OFFSET n ROWS FETCH NEXT m ROWS ONLY`; `LIMIT` es de SQLite, PostgreSQL y MySQL.",
      },
      {
        id: "m41-l3-q3",
        pregunta: "¿Qué se usa en SQLite para reproducir un `PIVOT`?",
        opciones: ["`GROUP_CONCAT`", "`SUM(CASE WHEN ...)` por cada columna", "`UNION`", "`CROSS JOIN`"],
        respuestaCorrecta: 1,
        explicacion: "Una agregación condicional por cada categoría convierte filas en columnas, en cualquier motor.",
      },
    ],
    resumen: ["El núcleo de SQL (consultas, JOIN, CTE, ventanas) es portable; lo que cambia son funciones de fecha, texto, límite de filas y extras.", "Lo que SQLite no trae (`ROLLUP`, `PIVOT`, `QUALIFY`, `MERGE`, percentiles) se reproduce con `UNION ALL`, `CASE`, CTE y `ON CONFLICT`.", "Antes de pegar una consulta ajena, identifica para qué motor está escrita."],
    proximoPaso: "Pasamos al proyecto integrador, donde combinaremos todo lo aprendido.",
    conceptos: ["dialectos-sql", "portabilidad"],
  },
]
