import type { Lesson } from '../../types'

export const module38Lessons: Lesson[] = [
  {
    id: "m38-l1",
    moduloId: "modulo-38",
    titulo: "Filtros precisos, NULL y valores únicos",
    objetivo: "Filtrar con IN, BETWEEN y LIKE, eliminar duplicados con DISTINCT y tratar los valores ausentes (NULL) con IS NULL, COALESCE y NULLIF.",
    porQueImporta:
      "Los datos reales tienen huecos: correos sin registrar, fechas pendientes, precios sin cargar. Si no sabes cómo se comporta NULL, tus conteos y tus filtros te darán resultados equivocados sin avisarte.",
    concepto: "Además de `=`, `<` y `>`, SQL tiene operadores para filtrar con más precisión:\n\n- `col IN ('a', 'b')`: coincide con cualquiera de la lista. `NOT IN` es lo contrario.\n- `col BETWEEN 10 AND 20`: incluye ambos extremos (equivale a `>= 10 AND <= 20`).\n- `col LIKE 'M%'`: `%` representa cualquier cantidad de caracteres y `_` exactamente uno. En SQLite `LIKE` no distingue mayúsculas de minúsculas para letras ASCII; en otros motores depende de la configuración (en PostgreSQL sí distingue y existe `ILIKE`).\n- `SELECT DISTINCT col`: elimina filas repetidas del resultado.\n\n**NULL** significa «dato desconocido o ausente». No es cero ni texto vacío, y por eso se comporta distinto:\n\n- Cualquier comparación con NULL (`= NULL`, `<> NULL`, `> 5`) no da verdadero ni falso, sino *desconocido*, y `WHERE` descarta esas filas. Para detectarlo se usa `IS NULL` / `IS NOT NULL`.\n- `COUNT(*)` cuenta filas; `COUNT(col)` cuenta solo las filas donde `col` **no** es NULL. `SUM`, `AVG`, `MIN` y `MAX` también ignoran los NULL.\n- `COALESCE(a, b, c)` devuelve el primer valor que no sea NULL: sirve para poner un valor por defecto.\n- `NULLIF(a, b)` devuelve NULL si `a = b` (muy útil para evitar divisiones entre cero: `x / NULLIF(y, 0)`).\n\nEn esta lección usamos además la tabla `contactos` (`cliente_id`, `email`, `telefono`), donde algunos datos faltan.\n\n```python\nconn.execute(\"SELECT * FROM contactos\").fetchall()\n```",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT DISTINCT ciudad FROM clientes WHERE plan IN ('Premium', 'Estandar') ORDER BY ciudad\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.executescript(\"\"\"\nCREATE TABLE contactos (cliente_id INTEGER, email TEXT, telefono TEXT);\nINSERT INTO contactos VALUES\n  (1, 'ana@mail.com', NULL), (2, NULL, '3001112222'), (3, 'marta@mail.com', '3003334444'),\n  (4, NULL, NULL), (5, 'sofia@mail.com', NULL);\n\"\"\")\n\nsql = \"\"\"\nSELECT c.nombre, COALESCE(k.email, 'sin correo') AS correo\nFROM clientes c\nLEFT JOIN contactos k ON k.cliente_id = c.id\nORDER BY c.id\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "SELECT COUNT(*) FROM contactos WHERE email = NULL     -- 0 filas: la comparación nunca es verdadera\nSELECT COUNT(*) FROM contactos WHERE email IS NULL    -- 2 filas: así sí se detectan los NULL",
      explicacion:
        "Comparar con `= NULL` nunca es verdadero, ni siquiera para las filas que sí son NULL. Hay que usar `IS NULL` o `IS NOT NULL`. Lo mismo ocurre con `NOT IN`: si la lista contiene un NULL, `x NOT IN (1, NULL)` nunca es verdadero y la consulta no devuelve nada.",
    },
    practicaGuiada: {
      id: "m38-l1-practica",
      enunciado: "Escribe una consulta que devuelva el `cliente_id` de los contactos que **no tienen correo** (`email` es NULL), ordenados por `cliente_id`.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.executescript(\"\"\"\nCREATE TABLE contactos (cliente_id INTEGER, email TEXT, telefono TEXT);\nINSERT INTO contactos VALUES\n  (1, 'ana@mail.com', NULL), (2, NULL, '3001112222'), (3, 'marta@mail.com', '3003334444'),\n  (4, NULL, NULL), (5, 'sofia@mail.com', NULL);\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.executescript(\"\"\"\nCREATE TABLE contactos (cliente_id INTEGER, email TEXT, telefono TEXT);\nINSERT INTO contactos VALUES\n  (1, 'ana@mail.com', NULL), (2, NULL, '3001112222'), (3, 'marta@mail.com', '3003334444'),\n  (4, NULL, NULL), (5, 'sofia@mail.com', NULL);\n\"\"\")\n\nsql = \"\"\"\nSELECT cliente_id FROM contactos WHERE email IS NULL ORDER BY cliente_id\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Usa `WHERE email IS NULL`.", "`SELECT cliente_id FROM contactos WHERE email IS NULL ORDER BY cliente_id`"],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[(2,), (4,)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [(2,), (4,)]" }
      },
    },
    reto: {
      id: "m38-l1-reto",
      enunciado: "Para **todos** los clientes (ordenados por `id`) devuelve su `nombre` y un dato de contacto: el correo si existe; si no, el teléfono; y si no hay ninguno, el texto `sin contacto`. Recuerda que Diego no tiene fila en `contactos`.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.executescript(\"\"\"\nCREATE TABLE contactos (cliente_id INTEGER, email TEXT, telefono TEXT);\nINSERT INTO contactos VALUES\n  (1, 'ana@mail.com', NULL), (2, NULL, '3001112222'), (3, 'marta@mail.com', '3003334444'),\n  (4, NULL, NULL), (5, 'sofia@mail.com', NULL);\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.executescript(\"\"\"\nCREATE TABLE contactos (cliente_id INTEGER, email TEXT, telefono TEXT);\nINSERT INTO contactos VALUES\n  (1, 'ana@mail.com', NULL), (2, NULL, '3001112222'), (3, 'marta@mail.com', '3003334444'),\n  (4, NULL, NULL), (5, 'sofia@mail.com', NULL);\n\"\"\")\n\nsql = \"\"\"\nSELECT c.nombre, COALESCE(k.email, k.telefono, 'sin contacto')\nFROM clientes c\nLEFT JOIN contactos k ON k.cliente_id = c.id\nORDER BY c.id\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Necesitas un `LEFT JOIN` para no perder a los clientes sin fila en `contactos`.", "`COALESCE(k.email, k.telefono, 'sin contacto')` devuelve el primer valor no NULL."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Ana', 'ana@mail.com'), ('Luis', '3001112222'), ('Marta', 'marta@mail.com'), ('Pedro', 'sin contacto'), ('Sofia', 'sofia@mail.com'), ('Diego', 'sin contacto')]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Ana', 'ana@mail.com'), ('Luis', '3001112222'), ('Marta', 'marta@mail.com'), ('Pedro', 'sin contacto'), ('Sofia', 'sofia@mail.com'), ('Diego', 'sin contacto')]" }
      },
    },
    verificacion: [
      {
        id: "m38-l1-q1",
        pregunta: "¿Qué devuelve `SELECT COUNT(email) FROM contactos` si la tabla tiene 5 filas y 2 correos son NULL?",
        opciones: ["5", "3", "2", "0"],
        respuestaCorrecta: 1,
        explicacion: "`COUNT(col)` ignora los NULL: solo cuenta los 3 correos presentes. `COUNT(*)` habría devuelto 5.",
      },
      {
        id: "m38-l1-q2",
        pregunta: "¿Cómo se buscan las filas sin correo?",
        opciones: ["WHERE email = NULL", "WHERE email = ''", "WHERE email IS NULL", "WHERE NOT email"],
        respuestaCorrecta: 2,
        explicacion: "NULL solo se detecta con `IS NULL`; cualquier comparación con `=` da «desconocido».",
      },
      {
        id: "m38-l1-q3",
        pregunta: "¿Para qué sirve `COALESCE(a, b)`?",
        opciones: ["Para unir dos textos", "Para devolver el primer valor que no sea NULL", "Para contar valores", "Para convertir a número"],
        respuestaCorrecta: 1,
        explicacion: "Recorre sus argumentos y devuelve el primero que no es NULL; se usa para valores por defecto.",
      },
    ],
    resumen: ["`IN`, `BETWEEN`, `LIKE` y `DISTINCT` afinan el filtro y quitan repetidos.", "NULL es «desconocido»: se detecta con `IS NULL`, nunca con `= NULL`.", "`COUNT(col)` y las demás agregaciones ignoran los NULL; `COALESCE` y `NULLIF` los manejan."],
    proximoPaso: "Veremos funciones para manipular texto y números dentro de la consulta.",
    conceptos: ["null", "distinct", "coalesce"],
  },
  {
    id: "m38-l2",
    moduloId: "modulo-38",
    titulo: "Funciones de texto y de números",
    objetivo: "Transformar texto (UPPER, SUBSTR, REPLACE, concatenación) y números (ROUND, CAST) dentro de la consulta, y evitar el error de la división entera.",
    porQueImporta:
      "Los datos llegan sucios o en un formato distinto del que necesitas: nombres en minúsculas, códigos con prefijos, precios sin impuesto. Transformarlos en la propia consulta evita pasos extra y mantiene el análisis reproducible.",
    concepto: "**Texto** (funciones disponibles en SQLite; la mayoría existen con el mismo nombre o uno muy parecido en otros motores):\n\n- `UPPER(t)`, `LOWER(t)`: mayúsculas y minúsculas.\n- `LENGTH(t)`: número de caracteres.\n- `TRIM(t)`: quita espacios al inicio y al final.\n- `SUBSTR(t, inicio, largo)`: extrae una parte (la posición empieza en **1**).\n- `REPLACE(t, buscar, nuevo)`: sustituye texto.\n- `INSTR(t, buscar)`: posición de la primera aparición (0 si no está). Es el equivalente de `POSITION` en otros motores.\n- `a || b`: concatena. Es el estándar SQL y funciona en SQLite, PostgreSQL y Oracle; en SQL Server se usa `+` o `CONCAT()`, y en MySQL `CONCAT()`.\n\n**Números**:\n\n- `ROUND(x, n)`: redondea a `n` decimales (devuelve decimal, por ejemplo `3.0`).\n- `ABS(x)`, `x % y` (resto), `MAX(a, b)` y `MIN(a, b)` con varios argumentos (en SQLite eligen entre columnas de la misma fila).\n- `CAST(x AS REAL)` o `CAST(x AS INTEGER)`: cambia el tipo.\n\n**Cuidado con la división entera**: si ambos números son enteros, SQLite (y PostgreSQL) devuelven un entero: `7 / 2` da `3`. Para obtener `3.5` hay que convertir uno de los operandos: `7 / 2.0` o `CAST(7 AS REAL) / 2`.\n\nY recuerda dar nombre a las columnas calculadas con `AS`.",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT UPPER(nombre) AS nombre_mayus, LENGTH(nombre) AS letras FROM clientes ORDER BY id\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT nombre || ' (' || categoria || ')' AS etiqueta,\n       precio,\n       ROUND(precio * 1.19, 1) AS con_iva\nFROM productos\nORDER BY precio DESC\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "SELECT SUM(cantidad) / COUNT(*) FROM pedidos        -- 25 / 10 = 2  (entero: pierde los decimales)\nSELECT SUM(cantidad) * 1.0 / COUNT(*) FROM pedidos  -- 2.5",
      explicacion:
        "Al dividir dos enteros SQLite devuelve un entero y descarta la parte decimal (25 / 10 = 2). Multiplica por `1.0` o usa `CAST(... AS REAL)` para obtener el promedio real. Es un error silencioso: la consulta funciona, pero el resultado es incorrecto.",
    },
    practicaGuiada: {
      id: "m38-l2-practica",
      enunciado: "Devuelve el `nombre` de cada producto en **mayúsculas** y su precio con IVA (19 %), redondeado a **1 decimal** (`ROUND(precio * 1.19, 1)`), ordenados por `id`.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT UPPER(nombre), ROUND(precio * 1.19, 1) FROM productos ORDER BY id\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["`UPPER(nombre)` y `ROUND(precio * 1.19, 1)`.", "Ordena con `ORDER BY id`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('LAPTOP', 2975.0), ('MOUSE', 59.5), ('TECLADO', 142.8), ('MONITOR', 952.0), ('AUDIFONOS', 178.5)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('LAPTOP', 2975.0), ('MOUSE', 59.5), ('TECLADO', 142.8), ('MONITOR', 952.0), ('AUDIFONOS', 178.5)]" }
      },
    },
    reto: {
      id: "m38-l2-reto",
      enunciado: "Construye para cada cliente (ordenados por `id`) un código con las **3 primeras letras del nombre**, un guion y las **3 primeras letras de la ciudad en mayúsculas**. Por ejemplo, Ana de Bogota → `Ana-BOG`.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT SUBSTR(nombre, 1, 3) || '-' || UPPER(SUBSTR(ciudad, 1, 3)) FROM clientes ORDER BY id\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["`SUBSTR(nombre, 1, 3)` toma 3 caracteres desde la posición 1.", "Une las partes con `||`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Ana-BOG',), ('Lui-MED',), ('Mar-BOG',), ('Ped-CAL',), ('Sof-MED',), ('Die-BOG',)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Ana-BOG',), ('Lui-MED',), ('Mar-BOG',), ('Ped-CAL',), ('Sof-MED',), ('Die-BOG',)]" }
      },
    },
    verificacion: [
      {
        id: "m38-l2-q1",
        pregunta: "¿Qué devuelve `SELECT 7 / 2` en SQLite?",
        opciones: ["3.5", "3", "4", "1"],
        respuestaCorrecta: 1,
        explicacion: "Ambos operandos son enteros, así que la división es entera y descarta los decimales.",
      },
      {
        id: "m38-l2-q2",
        pregunta: "¿Cuál es la posición del primer carácter en `SUBSTR`?",
        opciones: ["0", "1", "-1", "Depende de la tabla"],
        respuestaCorrecta: 1,
        explicacion: "En SQL las posiciones de texto empiezan en 1, no en 0 como en Python.",
      },
      {
        id: "m38-l2-q3",
        pregunta: "¿Qué operador estándar concatena texto?",
        opciones: ["+", "&", "||", "."],
        respuestaCorrecta: 2,
        explicacion: "`||` es el operador estándar; SQL Server usa `+` o `CONCAT()` y MySQL usa `CONCAT()`.",
      },
    ],
    resumen: ["`UPPER`, `LOWER`, `TRIM`, `SUBSTR`, `REPLACE` y `||` transforman texto dentro de la consulta.", "`ROUND` y `CAST` controlan decimales y tipos.", "Entero ÷ entero = entero: multiplica por `1.0` para obtener decimales."],
    proximoPaso: "Ahora trabajaremos con fechas, que SQLite guarda como texto.",
    conceptos: ["funciones-texto", "division-entera"],
  },
  {
    id: "m38-l3",
    moduloId: "modulo-38",
    titulo: "Fechas: strftime, date y diferencias entre días",
    objetivo: "Extraer partes de una fecha, agrupar por mes y calcular días transcurridos con las funciones de fecha de SQLite, y conocer sus equivalentes en otros motores.",
    porQueImporta:
      "Casi todo análisis de negocio es temporal: ventas por mes, tiempo entre dos eventos, clientes nuevos por trimestre. Las funciones de fecha cambian bastante entre motores, así que conviene entender la idea y no solo la sintaxis.",
    concepto: "SQLite no tiene un tipo de dato «fecha»: guarda las fechas como **texto** en formato ISO `AAAA-MM-DD` (o `AAAA-MM-DD HH:MM:SS`). Mientras uses ese formato, el texto se ordena y se compara correctamente y las funciones de fecha funcionan.\n\n- `date(f)`: valida y normaliza una fecha. `date(f, '+7 days')`, `date(f, 'start of month')`, `date(f, '-1 month')`: la desplazan o la ajustan.\n- `strftime('%Y', f)` año, `strftime('%m', f)` mes (`'01'`…`'12'`), `strftime('%Y-%m', f)` año-mes, `strftime('%w', f)` día de la semana (0 = domingo). El resultado es **texto**.\n- `julianday(f)`: número de días desde una fecha de referencia. La diferencia `julianday(b) - julianday(a)` son los días entre `b` y `a`.\n- `date('now')`: la fecha de hoy (no la usaremos en ejercicios porque cambia cada día).\n\nEquivalencias aproximadas en otros motores:\n\n- Extraer el año: `EXTRACT(YEAR FROM f)` (PostgreSQL, MySQL, Oracle), `YEAR(f)` (MySQL, SQL Server).\n- Truncar al mes: `DATE_TRUNC('month', f)` (PostgreSQL); en SQLite se usa `date(f, 'start of month')`.\n- Diferencia de días: `f2 - f1` (PostgreSQL), `DATEDIFF(day, f1, f2)` (SQL Server), `DATEDIFF(f2, f1)` (MySQL).\n\nAgrupar por mes es el patrón más frecuente:\n\n```sql\nSELECT strftime('%Y-%m', fecha) AS mes, COUNT(*) FROM pedidos GROUP BY mes ORDER BY mes\n```",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT fecha, strftime('%m', fecha) AS mes, strftime('%Y', fecha) AS anio FROM pedidos ORDER BY id LIMIT 3\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT strftime('%Y-%m', p.fecha) AS mes,\n       COUNT(*) AS pedidos,\n       SUM(p.cantidad * pr.precio) AS ingreso\nFROM pedidos p\nJOIN productos pr ON pr.id = p.producto_id\nGROUP BY mes\nORDER BY mes\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "SELECT strftime('%Y', '15/01/2024')   -- NULL: el formato DD/MM/AAAA no es válido para SQLite\nSELECT strftime('%Y', '2024-01-15')   -- '2024'",
      explicacion:
        "SQLite solo entiende fechas en formato ISO (`AAAA-MM-DD`). Con otro formato, como `15/01/2024`, las funciones devuelven **NULL** sin avisar, y además el texto no se ordena cronológicamente. Guarda siempre las fechas en ISO o conviértelas al cargar los datos.",
    },
    practicaGuiada: {
      id: "m38-l3-practica",
      enunciado: "Cuenta cuántos pedidos se hicieron en **febrero** de 2024 (mes `'02'`). Devuelve una sola fila con el conteo.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT COUNT(*) FROM pedidos WHERE strftime('%m', fecha) = '02'\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Filtra con `strftime('%m', fecha) = '02'` (el mes es texto).", "`SELECT COUNT(*) FROM pedidos WHERE ...`"],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[(4,)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [(4,)]" }
      },
    },
    reto: {
      id: "m38-l3-reto",
      enunciado: "Calcula cuántos **días** pasaron entre el primer y el último pedido (`MIN(fecha)` y `MAX(fecha)`). Devuelve un entero con `CAST(... AS INTEGER)`.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT CAST(julianday(MAX(fecha)) - julianday(MIN(fecha)) AS INTEGER) FROM pedidos\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Resta `julianday(MIN(fecha))` a `julianday(MAX(fecha))`.", "Envuelve el resultado en `CAST(... AS INTEGER)`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[(59,)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [(59,)]" }
      },
    },
    verificacion: [
      {
        id: "m38-l3-q1",
        pregunta: "¿En qué formato debe guardarse una fecha para que SQLite la entienda?",
        opciones: ["DD/MM/AAAA", "MM-DD-AAAA", "AAAA-MM-DD", "Cualquiera"],
        respuestaCorrecta: 2,
        explicacion: "El formato ISO `AAAA-MM-DD` es el único que las funciones de fecha de SQLite reconocen y, además, se ordena bien como texto.",
      },
      {
        id: "m38-l3-q2",
        pregunta: "¿Qué hace `strftime('%Y-%m', fecha)` en un `GROUP BY`?",
        opciones: ["Ordena por día", "Agrupa por año y mes", "Calcula la diferencia entre fechas", "Convierte a número"],
        respuestaCorrecta: 1,
        explicacion: "Devuelve el año y el mes como texto (`2024-02`), perfecto para agrupar por mes.",
      },
      {
        id: "m38-l3-q3",
        pregunta: "¿Cómo se calculan los días entre dos fechas en SQLite?",
        opciones: ["f2 - f1", "julianday(f2) - julianday(f1)", "DATEDIFF(f1, f2)", "strftime(f2) - strftime(f1)"],
        respuestaCorrecta: 1,
        explicacion: "`julianday` convierte cada fecha en un número de días; la resta da la diferencia. `DATEDIFF` es de otros motores.",
      },
    ],
    resumen: ["SQLite guarda fechas como texto ISO (`AAAA-MM-DD`).", "`strftime`, `date` y `julianday` extraen partes, desplazan fechas y calculan diferencias.", "Las funciones de fecha cambian entre motores: aprende el concepto, consulta la sintaxis."],
    proximoPaso: "Combinaremos todo lo anterior en agregaciones condicionales, el equivalente SQL de una tabla dinámica.",
    conceptos: ["fechas-sql", "strftime"],
  },
  {
    id: "m38-l4",
    moduloId: "modulo-38",
    titulo: "Agregación condicional: una tabla dinámica en SQL",
    objetivo: "Combinar SUM/COUNT con CASE para crear columnas condicionales (pivotar), usar COUNT(DISTINCT) y filtrar grupos con HAVING.",
    porQueImporta:
      "Un reporte rara vez pide «el total»: pide el total por categoría y por mes, lado a lado. La agregación condicional es la forma portátil de construir ese tipo de tabla en cualquier motor, sin depender de funciones especiales.",
    concepto: "Ya conoces `GROUP BY` y `HAVING`. Tres herramientas más:\n\n**`COUNT(DISTINCT col)`** cuenta valores distintos (clientes únicos, no pedidos).\n\n**Agregación condicional**: meter un `CASE` dentro de la agregación para sumar o contar solo las filas que cumplen una condición:\n\n```sql\nSUM(CASE WHEN plan = 'Premium' THEN monto ELSE 0 END) AS premium,\nCOUNT(CASE WHEN plan = 'Premium' THEN 1 END)          AS n_premium\n```\n\n(`COUNT` ignora los NULL, por eso el `CASE` sin `ELSE` devuelve NULL en las filas que no cumplen.) Con una columna así por cada categoría obtienes una **tabla dinámica** (pivot): las categorías pasan de filas a columnas. SQL Server, Oracle y otros motores tienen una cláusula `PIVOT` propia, pero la versión con `CASE` funciona en todos.\n\n**`group_concat(col, ', ')`** une los valores de cada grupo en un solo texto (en PostgreSQL y SQL Server se llama `STRING_AGG`, en MySQL `GROUP_CONCAT`). El orden dentro del texto no está garantizado.\n\n**`HAVING`** filtra grupos *después* de agregar (como `WHERE`, pero sobre el resultado de `SUM`, `COUNT`…). Usa `WHERE` para filtrar filas antes de agrupar y `HAVING` para filtrar grupos.\n\nUn detalle de SQLite: permite seleccionar columnas que no están en el `GROUP BY` ni dentro de una agregación y devuelve un valor cualquiera del grupo. Otros motores lo rechazan con error: no te acostumbres a hacerlo.",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT COUNT(*) AS pedidos, COUNT(DISTINCT cliente_id) AS clientes_distintos FROM pedidos\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT pr.categoria,\n       SUM(CASE WHEN strftime('%m', p.fecha) = '01' THEN p.cantidad * pr.precio ELSE 0 END) AS enero,\n       SUM(CASE WHEN strftime('%m', p.fecha) = '02' THEN p.cantidad * pr.precio ELSE 0 END) AS febrero,\n       SUM(CASE WHEN strftime('%m', p.fecha) = '03' THEN p.cantidad * pr.precio ELSE 0 END) AS marzo\nFROM pedidos p\nJOIN productos pr ON pr.id = p.producto_id\nGROUP BY pr.categoria\nORDER BY pr.categoria\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "SELECT categoria, nombre, SUM(precio) FROM productos GROUP BY categoria\n-- SQLite lo acepta y muestra un 'nombre' cualquiera de cada grupo; PostgreSQL y SQL Server dan error",
      explicacion:
        "La columna `nombre` no está en el `GROUP BY` ni dentro de una agregación: el resultado es ambiguo (¿qué nombre del grupo?). SQLite no protesta y devuelve uno cualquiera, lo que puede ocultar errores. Selecciona solo columnas agrupadas o agregadas.",
    },
    practicaGuiada: {
      id: "m38-l4-practica",
      enunciado: "Calcula el **ingreso** (`cantidad * precio`) que generaron los clientes del plan `Premium`, usando `SUM(CASE WHEN c.plan = 'Premium' THEN ... ELSE 0 END)`. Devuelve una sola fila con un número.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT SUM(CASE WHEN c.plan = 'Premium' THEN p.cantidad * pr.precio ELSE 0 END)\nFROM pedidos p\nJOIN clientes c ON c.id = p.cliente_id\nJOIN productos pr ON pr.id = p.producto_id\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Une `pedidos` con `clientes` y con `productos`.", "Dentro del `SUM`, el `CASE` deja `0` para los demás planes."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[(5250.0,)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [(5250.0,)]" }
      },
    },
    reto: {
      id: "m38-l4-reto",
      enunciado: "Lista los clientes que compraron **al menos 2 productos distintos**: devuelve `nombre` y el número de productos distintos, ordenados de mayor a menor y, si empatan, por nombre.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT c.nombre, COUNT(DISTINCT p.producto_id) AS productos\nFROM pedidos p\nJOIN clientes c ON c.id = p.cliente_id\nGROUP BY c.id, c.nombre\nHAVING COUNT(DISTINCT p.producto_id) >= 2\nORDER BY productos DESC, c.nombre\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Agrupa por cliente y cuenta `DISTINCT producto_id`.", "Filtra los grupos con `HAVING`, no con `WHERE`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Ana', 3), ('Luis', 2), ('Marta', 2), ('Sofia', 2)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Ana', 3), ('Luis', 2), ('Marta', 2), ('Sofia', 2)]" }
      },
    },
    verificacion: [
      {
        id: "m38-l4-q1",
        pregunta: "¿Para qué sirve `SUM(CASE WHEN ... THEN x ELSE 0 END)`?",
        opciones: ["Para ordenar", "Para sumar solo las filas que cumplen una condición", "Para eliminar duplicados", "Para unir tablas"],
        respuestaCorrecta: 1,
        explicacion: "El `CASE` decide qué valor aporta cada fila; con `ELSE 0` las que no cumplen no suman. Así se arman columnas condicionales y tablas dinámicas.",
      },
      {
        id: "m38-l4-q2",
        pregunta: "¿Cuál es la diferencia entre `WHERE` y `HAVING`?",
        opciones: ["Ninguna", "`WHERE` filtra filas antes de agrupar; `HAVING` filtra grupos después de agregar", "`HAVING` solo sirve con texto", "`WHERE` es más lento"],
        respuestaCorrecta: 1,
        explicacion: "Para condiciones sobre `SUM`, `COUNT`… hay que usar `HAVING`, porque esos valores no existen aún cuando se evalúa `WHERE`.",
      },
      {
        id: "m38-l4-q3",
        pregunta: "¿Qué cuenta `COUNT(DISTINCT cliente_id)` en `pedidos`?",
        opciones: ["Pedidos", "Clientes distintos que hicieron pedidos", "Productos", "Filas con NULL"],
        respuestaCorrecta: 1,
        explicacion: "Cuenta cada cliente una sola vez, sin importar cuántos pedidos tenga.",
      },
    ],
    resumen: ["`SUM`/`COUNT` con `CASE` dan agregaciones condicionales y tablas dinámicas portátiles.", "`COUNT(DISTINCT ...)` cuenta valores únicos; `group_concat` junta textos por grupo.", "`WHERE` filtra filas; `HAVING` filtra grupos."],
    proximoPaso: "Pasamos al siguiente módulo: combinar tablas de formas más avanzadas.",
    conceptos: ["agregacion-condicional", "pivot-sql"],
  },
]
