import type { Lesson } from '../../types'

export const module39Lessons: Lesson[] = [
  {
    id: "m39-l1",
    moduloId: "modulo-39",
    titulo: "JOIN de varias tablas y búsqueda de lo que falta (anti-join)",
    objetivo: "Unir tres o más tablas, usar LEFT JOIN para conservar filas sin pareja y encontrar registros que no tienen coincidencia (clientes sin pedidos).",
    porQueImporta:
      "Dos de las preguntas más valiosas de negocio son «¿qué tenemos que no está funcionando?»: clientes que nunca compraron, productos que no se venden, tickets sin respuesta. Se responden con un LEFT JOIN y una condición sobre NULL.",
    concepto: "Un `JOIN` une filas de dos tablas cuando se cumple la condición del `ON`. Puedes encadenar tantos como necesites; cada uno une la tabla nueva con lo que ya tienes:\n\n```sql\nFROM pedidos p\nJOIN clientes c  ON c.id  = p.cliente_id\nJOIN productos pr ON pr.id = p.producto_id\n```\n\n- `JOIN` (o `INNER JOIN`) deja solo las filas que tienen pareja en ambas tablas.\n- `LEFT JOIN` conserva **todas** las filas de la tabla de la izquierda; si no hay pareja, las columnas de la derecha salen NULL.\n\n**Anti-join**: para encontrar las filas de la izquierda que *no* tienen pareja, haz un `LEFT JOIN` y filtra las filas donde la clave de la derecha es NULL:\n\n```sql\nSELECT c.nombre\nFROM clientes c\nLEFT JOIN pedidos p ON p.cliente_id = c.id\nWHERE p.id IS NULL\n```\n\n**Cuidado con dónde pones los filtros** en un `LEFT JOIN`: una condición sobre la tabla derecha en el `WHERE` elimina las filas NULL y convierte el `LEFT JOIN` en un `JOIN` normal. Si quieres filtrar la tabla derecha *sin* perder filas de la izquierda, pon la condición en el `ON`.\n\nPara contar con un `LEFT JOIN` usa `COUNT(p.id)` (no `COUNT(*)`): el primero da 0 para quien no tiene pedidos; el segundo daría 1 por la fila vacía.",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT p.id, c.nombre, pr.nombre AS producto, p.cantidad\nFROM pedidos p\nJOIN clientes c ON c.id = p.cliente_id\nJOIN productos pr ON pr.id = p.producto_id\nORDER BY p.id\nLIMIT 4\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT c.nombre,\n       COUNT(p.id) AS pedidos,\n       COALESCE(SUM(p.cantidad * pr.precio), 0) AS ingreso\nFROM clientes c\nLEFT JOIN pedidos p ON p.cliente_id = c.id\nLEFT JOIN productos pr ON pr.id = p.producto_id\nGROUP BY c.id, c.nombre\nORDER BY ingreso DESC, c.nombre\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "-- Quiero TODOS los clientes, con sus pedidos de febrero en adelante\nSELECT c.nombre, p.fecha\nFROM clientes c\nLEFT JOIN pedidos p ON p.cliente_id = c.id\nWHERE p.fecha >= '2024-02-01'      -- elimina a los clientes sin pedidos: el LEFT JOIN se volvió un JOIN\n\n-- Correcto: la condición va en el ON\nLEFT JOIN pedidos p ON p.cliente_id = c.id AND p.fecha >= '2024-02-01'",
      explicacion:
        "Un filtro sobre la tabla derecha en el `WHERE` descarta las filas donde esa tabla es NULL, es decir, justo las que el `LEFT JOIN` quería conservar. Si el filtro debe aplicarse solo a los pedidos, ponlo en el `ON`.",
    },
    practicaGuiada: {
      id: "m39-l1-practica",
      enunciado: "Encuentra los clientes que **nunca han hecho un pedido** con un `LEFT JOIN` y `WHERE p.id IS NULL`. Devuelve sus nombres.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT c.nombre\nFROM clientes c\nLEFT JOIN pedidos p ON p.cliente_id = c.id\nWHERE p.id IS NULL\nORDER BY c.nombre\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["`FROM clientes c LEFT JOIN pedidos p ON p.cliente_id = c.id`", "Filtra con `WHERE p.id IS NULL`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Diego',)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Diego',)]" }
      },
    },
    reto: {
      id: "m39-l1-reto",
      enunciado: "Devuelve, para cada cliente (incluidos los que no compraron), su `nombre` y el **número de pedidos** (`COUNT(p.id)`), ordenados de más a menos pedidos y, en empate, por nombre.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT c.nombre, COUNT(p.id) AS pedidos\nFROM clientes c\nLEFT JOIN pedidos p ON p.cliente_id = c.id\nGROUP BY c.id, c.nombre\nORDER BY pedidos DESC, c.nombre\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["`LEFT JOIN` para no perder a los clientes sin pedidos.", "Usa `COUNT(p.id)`, no `COUNT(*)`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Ana', 3), ('Luis', 2), ('Marta', 2), ('Sofia', 2), ('Pedro', 1), ('Diego', 0)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Ana', 3), ('Luis', 2), ('Marta', 2), ('Sofia', 2), ('Pedro', 1), ('Diego', 0)]" }
      },
    },
    verificacion: [
      {
        id: "m39-l1-q1",
        pregunta: "¿Cómo se encuentran los clientes sin pedidos?",
        opciones: ["JOIN y WHERE p.id IS NULL", "LEFT JOIN y WHERE p.id IS NULL", "GROUP BY con HAVING", "ORDER BY p.id"],
        respuestaCorrecta: 1,
        explicacion: "El `LEFT JOIN` conserva a todos los clientes; los que no tienen pedido quedan con `p.id` NULL.",
      },
      {
        id: "m39-l1-q2",
        pregunta: "¿Por qué `COUNT(*)` da 1 para un cliente sin pedidos tras un `LEFT JOIN`?",
        opciones: ["Es un error de SQLite", "Porque la fila del cliente existe aunque no tenga pedido", "Porque cuenta NULL como cero", "Porque ignora el GROUP BY"],
        respuestaCorrecta: 1,
        explicacion: "`COUNT(*)` cuenta filas, y la fila del cliente (con columnas de pedido NULL) existe. `COUNT(p.id)` ignora el NULL y da 0.",
      },
      {
        id: "m39-l1-q3",
        pregunta: "En un `LEFT JOIN`, ¿dónde va un filtro que solo debe aplicar a la tabla derecha sin perder filas de la izquierda?",
        opciones: ["En el WHERE", "En el ON", "En el HAVING", "En el ORDER BY"],
        respuestaCorrecta: 1,
        explicacion: "En el `ON` la condición decide qué parejas se forman; en el `WHERE` elimina filas ya formadas, incluidas las NULL.",
      },
    ],
    resumen: ["Se pueden encadenar varios `JOIN`, cada uno con su `ON`.", "`LEFT JOIN` + `IS NULL` encuentra lo que no tiene pareja.", "Filtros de la tabla derecha: en el `ON`; y cuenta con `COUNT(col)`."],
    proximoPaso: "Veremos los demás tipos de unión: RIGHT, FULL, CROSS y la unión de una tabla consigo misma.",
    conceptos: ["anti-join", "left-join"],
  },
  {
    id: "m39-l2",
    moduloId: "modulo-39",
    titulo: "RIGHT, FULL, CROSS y SELF JOIN",
    objetivo: "Distinguir los tipos de JOIN restantes y usar CROSS JOIN y la unión de una tabla consigo misma para generar combinaciones y relacionar jerarquías.",
    porQueImporta:
      "Detectar huecos (combinaciones sin ventas), comparar filas de una misma tabla (empleado y jefe) o cruzar dos conjuntos completos son tareas habituales que el JOIN básico no resuelve solo.",
    concepto: "Los tipos de unión, vistos como conjuntos de filas:\n\n- `INNER JOIN`: solo las filas con pareja en ambos lados.\n- `LEFT JOIN`: todas las de la izquierda, con o sin pareja.\n- `RIGHT JOIN`: todas las de la derecha. Es lo mismo que un `LEFT JOIN` con las tablas intercambiadas, por eso casi nunca se usa.\n- `FULL OUTER JOIN`: todas las filas de ambos lados, con o sin pareja.\n- `CROSS JOIN`: **todas las combinaciones** posibles (producto cartesiano): 3 ciudades × 2 categorías = 6 filas. No lleva `ON`.\n\n`RIGHT` y `FULL JOIN` existen en SQLite desde la versión 3.39 (2022); MySQL no tiene `FULL OUTER JOIN`. Una forma que funciona en cualquier motor es emularlo con un `LEFT JOIN` más un `UNION` (lo veremos en la próxima lección).\n\n**CROSS JOIN para encontrar huecos**: genera todas las combinaciones esperadas (por ejemplo, ciudad × categoría) y haz un `LEFT JOIN` con lo que ocurrió realmente; las combinaciones sin datos aparecen con 0.\n\n**SELF JOIN**: unir una tabla consigo misma, usando dos alias distintos. Es la forma de relacionar una fila con otra de la misma tabla, por ejemplo cada empleado con su jefe (`jefe_id` apunta al `id` de otro empleado):\n\n```sql\nFROM empleados e LEFT JOIN empleados j ON j.id = e.jefe_id\n```\n\nEn esta lección usamos la tabla `empleados` (`id`, `nombre`, `depto`, `salario`, `jefe_id`, `ingreso`).",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.executescript(\"\"\"\nCREATE TABLE empleados (id INTEGER PRIMARY KEY, nombre TEXT, depto TEXT, salario INTEGER, jefe_id INTEGER, ingreso TEXT);\nINSERT INTO empleados VALUES\n  (1, 'Carla', 'Direccion', 9000, NULL, '2019-03-01'), (2, 'Andres', 'Ventas', 5200, 1, '2020-07-15'),\n  (3, 'Lucia', 'Ventas', 4800, 2, '2021-02-01'), (4, 'Mateo', 'Ventas', 4800, 2, '2022-09-12'),\n  (5, 'Paula', 'Datos', 6500, 1, '2020-01-20'), (6, 'Hugo', 'Datos', 5800, 5, '2021-11-03'),\n  (7, 'Elena', 'Datos', 5800, 5, '2023-04-17'), (8, 'Raul', 'Soporte', 3500, 1, '2022-05-30'),\n  (9, 'Nora', 'Soporte', 3900, 8, '2023-01-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT e.nombre AS empleado, j.nombre AS jefe\nFROM empleados e\nLEFT JOIN empleados j ON j.id = e.jefe_id\nORDER BY e.id\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nWITH rejilla AS (\n    SELECT DISTINCT c.ciudad, pr.categoria\n    FROM clientes c CROSS JOIN productos pr\n),\nreal AS (\n    SELECT c.ciudad, pr.categoria, COUNT(*) AS pedidos\n    FROM pedidos p\n    JOIN clientes c ON c.id = p.cliente_id\n    JOIN productos pr ON pr.id = p.producto_id\n    GROUP BY c.ciudad, pr.categoria\n)\nSELECT g.ciudad, g.categoria, COALESCE(r.pedidos, 0) AS pedidos\nFROM rejilla g\nLEFT JOIN real r ON r.ciudad = g.ciudad AND r.categoria = g.categoria\nORDER BY g.ciudad, g.categoria\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "SELECT COUNT(*) FROM clientes, pedidos             -- 60 filas (6 × 10): se olvidó la condición de unión\nSELECT COUNT(*) FROM clientes c JOIN pedidos p ON p.cliente_id = c.id   -- 10 filas",
      explicacion:
        "Si une dos tablas sin condición (con una coma o con `CROSS JOIN`) obtienes todas las combinaciones: 6 clientes × 10 pedidos = 60 filas. Es el origen de los totales inflados, porque cada pedido se repite para todos los clientes. Si el número de filas crece de golpe tras un `JOIN`, revisa el `ON`.",
    },
    practicaGuiada: {
      id: "m39-l2-practica",
      enunciado: "Usa un **self join** para listar todas las **parejas de empleados del mismo departamento**. Devuelve `a.nombre` y `b.nombre` con la condición `a.id < b.id` (para no repetir parejas ni emparejar a alguien consigo mismo), ordenadas por `a.id` y luego `b.id`.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.executescript(\"\"\"\nCREATE TABLE empleados (id INTEGER PRIMARY KEY, nombre TEXT, depto TEXT, salario INTEGER, jefe_id INTEGER, ingreso TEXT);\nINSERT INTO empleados VALUES\n  (1, 'Carla', 'Direccion', 9000, NULL, '2019-03-01'), (2, 'Andres', 'Ventas', 5200, 1, '2020-07-15'),\n  (3, 'Lucia', 'Ventas', 4800, 2, '2021-02-01'), (4, 'Mateo', 'Ventas', 4800, 2, '2022-09-12'),\n  (5, 'Paula', 'Datos', 6500, 1, '2020-01-20'), (6, 'Hugo', 'Datos', 5800, 5, '2021-11-03'),\n  (7, 'Elena', 'Datos', 5800, 5, '2023-04-17'), (8, 'Raul', 'Soporte', 3500, 1, '2022-05-30'),\n  (9, 'Nora', 'Soporte', 3900, 8, '2023-01-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.executescript(\"\"\"\nCREATE TABLE empleados (id INTEGER PRIMARY KEY, nombre TEXT, depto TEXT, salario INTEGER, jefe_id INTEGER, ingreso TEXT);\nINSERT INTO empleados VALUES\n  (1, 'Carla', 'Direccion', 9000, NULL, '2019-03-01'), (2, 'Andres', 'Ventas', 5200, 1, '2020-07-15'),\n  (3, 'Lucia', 'Ventas', 4800, 2, '2021-02-01'), (4, 'Mateo', 'Ventas', 4800, 2, '2022-09-12'),\n  (5, 'Paula', 'Datos', 6500, 1, '2020-01-20'), (6, 'Hugo', 'Datos', 5800, 5, '2021-11-03'),\n  (7, 'Elena', 'Datos', 5800, 5, '2023-04-17'), (8, 'Raul', 'Soporte', 3500, 1, '2022-05-30'),\n  (9, 'Nora', 'Soporte', 3900, 8, '2023-01-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT a.nombre, b.nombre\nFROM empleados a\nJOIN empleados b ON a.depto = b.depto AND a.id < b.id\nORDER BY a.id, b.id\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Une `empleados a` con `empleados b` por `depto`.", "La condición `a.id < b.id` evita duplicados."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Andres', 'Lucia'), ('Andres', 'Mateo'), ('Lucia', 'Mateo'), ('Paula', 'Hugo'), ('Paula', 'Elena'), ('Hugo', 'Elena'), ('Raul', 'Nora')]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Andres', 'Lucia'), ('Andres', 'Mateo'), ('Lucia', 'Mateo'), ('Paula', 'Hugo'), ('Paula', 'Elena'), ('Hugo', 'Elena'), ('Raul', 'Nora')]" }
      },
    },
    reto: {
      id: "m39-l2-reto",
      enunciado: "Encuentra a los empleados que **ganan más que su jefe**. Devuelve `nombre`, su `salario` y el `salario` de su jefe.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.executescript(\"\"\"\nCREATE TABLE empleados (id INTEGER PRIMARY KEY, nombre TEXT, depto TEXT, salario INTEGER, jefe_id INTEGER, ingreso TEXT);\nINSERT INTO empleados VALUES\n  (1, 'Carla', 'Direccion', 9000, NULL, '2019-03-01'), (2, 'Andres', 'Ventas', 5200, 1, '2020-07-15'),\n  (3, 'Lucia', 'Ventas', 4800, 2, '2021-02-01'), (4, 'Mateo', 'Ventas', 4800, 2, '2022-09-12'),\n  (5, 'Paula', 'Datos', 6500, 1, '2020-01-20'), (6, 'Hugo', 'Datos', 5800, 5, '2021-11-03'),\n  (7, 'Elena', 'Datos', 5800, 5, '2023-04-17'), (8, 'Raul', 'Soporte', 3500, 1, '2022-05-30'),\n  (9, 'Nora', 'Soporte', 3900, 8, '2023-01-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nconn.executescript(\"\"\"\nCREATE TABLE empleados (id INTEGER PRIMARY KEY, nombre TEXT, depto TEXT, salario INTEGER, jefe_id INTEGER, ingreso TEXT);\nINSERT INTO empleados VALUES\n  (1, 'Carla', 'Direccion', 9000, NULL, '2019-03-01'), (2, 'Andres', 'Ventas', 5200, 1, '2020-07-15'),\n  (3, 'Lucia', 'Ventas', 4800, 2, '2021-02-01'), (4, 'Mateo', 'Ventas', 4800, 2, '2022-09-12'),\n  (5, 'Paula', 'Datos', 6500, 1, '2020-01-20'), (6, 'Hugo', 'Datos', 5800, 5, '2021-11-03'),\n  (7, 'Elena', 'Datos', 5800, 5, '2023-04-17'), (8, 'Raul', 'Soporte', 3500, 1, '2022-05-30'),\n  (9, 'Nora', 'Soporte', 3900, 8, '2023-01-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT e.nombre, e.salario, j.salario\nFROM empleados e\nJOIN empleados j ON j.id = e.jefe_id\nWHERE e.salario > j.salario\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Une `empleados e` con `empleados j` donde `j.id = e.jefe_id`.", "Filtra `e.salario > j.salario`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Nora', 3900, 3500)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Nora', 3900, 3500)]" }
      },
    },
    verificacion: [
      {
        id: "m39-l2-q1",
        pregunta: "¿Cuántas filas produce `CROSS JOIN` entre una tabla de 3 filas y otra de 4?",
        opciones: ["3", "4", "7", "12"],
        respuestaCorrecta: 3,
        explicacion: "Combina cada fila de una con cada fila de la otra: 3 × 4 = 12.",
      },
      {
        id: "m39-l2-q2",
        pregunta: "¿Para qué sirve un self join?",
        opciones: ["Para borrar duplicados", "Para relacionar filas de una tabla con otras filas de la misma tabla", "Para unir con una vista", "Para ordenar"],
        respuestaCorrecta: 1,
        explicacion: "Con dos alias de la misma tabla puedes comparar o relacionar filas entre sí (empleado y jefe, parejas, etc.).",
      },
      {
        id: "m39-l2-q3",
        pregunta: "Un `RIGHT JOIN` equivale a:",
        opciones: ["Un `LEFT JOIN` con las tablas intercambiadas", "Un `CROSS JOIN`", "Un `INNER JOIN`", "Un `UNION`"],
        respuestaCorrecta: 0,
        explicacion: "Conserva todas las filas de la tabla derecha; basta con cambiar el orden de las tablas y usar `LEFT JOIN`.",
      },
    ],
    resumen: ["`INNER`, `LEFT`, `RIGHT` y `FULL` difieren en qué filas sin pareja se conservan.", "`CROSS JOIN` genera todas las combinaciones: útil para detectar huecos.", "El self join relaciona una tabla consigo misma usando dos alias."],
    proximoPaso: "Seguiremos con otra forma de combinar resultados: UNION, INTERSECT y EXCEPT.",
    conceptos: ["cross-join", "self-join"],
  },
  {
    id: "m39-l3",
    moduloId: "modulo-39",
    titulo: "UNION, INTERSECT y EXCEPT",
    objetivo: "Combinar los resultados de varias consultas con UNION, UNION ALL, INTERSECT y EXCEPT, y usar UNION ALL para agregar una fila de totales.",
    porQueImporta:
      "A veces no necesitas unir columnas de tablas distintas sino apilar o comparar resultados: «clientes que compraron A y B», «clientes que compraron A pero no B», o un reporte con una fila de total al final.",
    concepto: "Las operaciones de conjuntos combinan los resultados de dos consultas **que tienen el mismo número de columnas** (y tipos compatibles):\n\n- `UNION ALL`: apila todos los resultados, sin quitar repetidos. Es rápido.\n- `UNION`: apila y **elimina duplicados** (más costoso porque debe comparar filas).\n- `INTERSECT`: solo las filas que aparecen en **ambos** resultados.\n- `EXCEPT`: las filas del primer resultado que **no** aparecen en el segundo (en Oracle se llama `MINUS`).\n\nReglas útiles:\n\n- Los nombres de columna del resultado son los de la **primera** consulta.\n- `ORDER BY` va una sola vez, al final, y se aplica a todo el resultado.\n- Usa `UNION ALL` salvo que realmente necesites quitar duplicados.\n- `INTERSECT` y `EXCEPT` también existen en PostgreSQL, SQL Server y Oracle (como `MINUS`); MySQL los incorpora desde la versión 8.0.31.\n\n**Fila de totales con `UNION ALL`**: SQLite no tiene `ROLLUP` (que otros motores usan para subtotales y totales). Se obtiene el mismo efecto apilando el detalle y el total, y añadiendo una columna auxiliar para controlar el orden:\n\n```sql\nSELECT categoria, SUM(importe), 1 AS orden FROM ... GROUP BY categoria\nUNION ALL\nSELECT 'TOTAL', SUM(importe), 2 FROM ...\nORDER BY orden\n```",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT COUNT(*) AS con_union_all FROM (SELECT ciudad FROM clientes UNION ALL SELECT ciudad FROM clientes)\nUNION ALL\nSELECT COUNT(*) FROM (SELECT ciudad FROM clientes UNION SELECT ciudad FROM clientes)\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT categoria, ingreso FROM (\n    SELECT pr.categoria AS categoria, SUM(p.cantidad * pr.precio) AS ingreso, 1 AS orden\n    FROM pedidos p JOIN productos pr ON pr.id = p.producto_id\n    GROUP BY pr.categoria\n    UNION ALL\n    SELECT 'TOTAL', SUM(p.cantidad * pr.precio), 2\n    FROM pedidos p JOIN productos pr ON pr.id = p.producto_id\n)\nORDER BY orden, categoria\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "SELECT nombre, ciudad FROM clientes\nUNION\nSELECT nombre FROM productos          -- error: SELECTs to the 1st and 2nd have a different number of columns",
      explicacion:
        "Todas las consultas combinadas deben devolver el mismo número de columnas, en el mismo orden y con tipos compatibles. Además, si pones `ORDER BY` en medio de una combinación, no funcionará: el orden se aplica una sola vez, al final.",
    },
    practicaGuiada: {
      id: "m39-l3-practica",
      enunciado: "Obtén los clientes que compraron productos de la categoría `Electronica` **y no** compraron de la categoría `Accesorios`, usando `EXCEPT`. Devuelve sus nombres.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT c.nombre\nFROM pedidos p\nJOIN clientes c ON c.id = p.cliente_id\nJOIN productos pr ON pr.id = p.producto_id\nWHERE pr.categoria = 'Electronica'\nEXCEPT\nSELECT c.nombre\nFROM pedidos p\nJOIN clientes c ON c.id = p.cliente_id\nJOIN productos pr ON pr.id = p.producto_id\nWHERE pr.categoria = 'Accesorios'\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Escribe la misma consulta dos veces, cambiando la categoría.", "Sepárelas con `EXCEPT`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Pedro',)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Pedro',)]" }
      },
    },
    reto: {
      id: "m39-l3-reto",
      enunciado: "Obtén los clientes que compraron de **ambas** categorías (`Electronica` e `Accesorios`) con `INTERSECT`. Devuelve sus nombres ordenados alfabéticamente.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT c.nombre AS nombre\nFROM pedidos p\nJOIN clientes c ON c.id = p.cliente_id\nJOIN productos pr ON pr.id = p.producto_id\nWHERE pr.categoria = 'Electronica'\nINTERSECT\nSELECT c.nombre\nFROM pedidos p\nJOIN clientes c ON c.id = p.cliente_id\nJOIN productos pr ON pr.id = p.producto_id\nWHERE pr.categoria = 'Accesorios'\nORDER BY nombre\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Dos consultas, una por categoría, unidas con `INTERSECT`.", "El `ORDER BY nombre` va una sola vez, al final (la primera consulta debe llamar `nombre` a la columna: `c.nombre AS nombre`)."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Ana',), ('Marta',), ('Sofia',)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Ana',), ('Marta',), ('Sofia',)]" }
      },
    },
    verificacion: [
      {
        id: "m39-l3-q1",
        pregunta: "¿Cuál es la diferencia entre `UNION` y `UNION ALL`?",
        opciones: ["`UNION` es más rápido", "`UNION` elimina duplicados y `UNION ALL` los conserva", "`UNION ALL` solo funciona con números", "Ninguna"],
        respuestaCorrecta: 1,
        explicacion: "`UNION` compara y quita filas repetidas (más costoso); `UNION ALL` apila sin revisar.",
      },
      {
        id: "m39-l3-q2",
        pregunta: "¿Qué devuelve `A EXCEPT B`?",
        opciones: ["Las filas que están en ambos", "Las filas de A que no están en B", "Todas las filas de A y B", "Las filas de B que no están en A"],
        respuestaCorrecta: 1,
        explicacion: "`EXCEPT` resta: conserva solo lo que está en el primer resultado y no en el segundo.",
      },
      {
        id: "m39-l3-q3",
        pregunta: "¿Cómo se simula una fila de total (como `ROLLUP`) en SQLite?",
        opciones: ["No es posible", "Con `UNION ALL` entre el detalle y el total", "Con `HAVING`", "Con `DISTINCT`"],
        respuestaCorrecta: 1,
        explicacion: "Se apilan las filas de detalle y una fila `TOTAL`, con una columna auxiliar para ordenar.",
      },
    ],
    resumen: ["`UNION ALL` apila; `UNION` apila y quita duplicados.", "`INTERSECT` da lo común y `EXCEPT` lo que solo está en el primer resultado.", "Las consultas combinadas deben tener las mismas columnas; `ORDER BY` va al final."],
    proximoPaso: "Cerraremos el módulo con las subconsultas: consultas dentro de consultas.",
    conceptos: ["union", "intersect-except"],
  },
  {
    id: "m39-l4",
    moduloId: "modulo-39",
    titulo: "Subconsultas: IN, EXISTS y correlacionadas",
    objetivo: "Usar subconsultas escalares, con IN y con EXISTS, entender las correlacionadas y evitar la trampa de NOT IN con NULL.",
    porQueImporta:
      "Muchas preguntas se formulan en dos pasos: «productos que cuestan más que el promedio», «pedidos del último día de cada cliente». La subconsulta resuelve el primer paso para que la consulta externa use su resultado.",
    concepto: "Una **subconsulta** es un `SELECT` dentro de otro, entre paréntesis. Según lo que devuelve y dónde se usa:\n\n- **Escalar** (una fila, una columna): se usa como un valor: `WHERE precio > (SELECT AVG(precio) FROM productos)`.\n- **Lista** con `IN`: `WHERE cliente_id IN (SELECT id FROM clientes WHERE ciudad = 'Bogota')`.\n- **Existencia** con `EXISTS`: es verdadera si la subconsulta devuelve al menos una fila; solo importa si hay filas, no qué columnas. `NOT EXISTS` es la negación.\n- **Tabla derivada**: en el `FROM`, con un alias: `FROM (SELECT ...) AS t`.\n\nUna subconsulta es **correlacionada** cuando usa columnas de la consulta externa, y por eso se evalúa para cada fila:\n\n```sql\nSELECT * FROM pedidos p\nWHERE p.fecha = (SELECT MAX(fecha) FROM pedidos WHERE cliente_id = p.cliente_id)\n```\n\nElige entre `JOIN`, `IN` y `EXISTS` según la claridad: casi siempre dan el mismo resultado. `NOT EXISTS` es la opción más segura para «los que no tienen…», porque `NOT IN` falla si la lista contiene algún NULL (`x NOT IN (1, NULL)` nunca es verdadero).\n\nLas subconsultas escalares deben devolver **una sola fila**. Los motores como PostgreSQL dan error si devuelve más; SQLite, en cambio, toma silenciosamente la primera.",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT nombre, precio FROM productos WHERE precio > (SELECT AVG(precio) FROM productos) ORDER BY precio\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT p.id, p.cliente_id, p.fecha\nFROM pedidos p\nWHERE p.fecha = (SELECT MAX(fecha) FROM pedidos WHERE cliente_id = p.cliente_id)\nORDER BY p.cliente_id\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "SELECT nombre FROM productos\nWHERE precio > (SELECT precio FROM productos WHERE categoria = 'Accesorios')\n-- La subconsulta devuelve 3 filas. PostgreSQL da error; SQLite usa la primera (Mouse, 50) sin avisar.",
      explicacion:
        "Una subconsulta escalar debe devolver una sola fila. Aquí devuelve tres precios, y SQLite elige uno (el primero) sin protestar, así que la consulta «funciona» pero responde otra pregunta. Usa una agregación (`MAX`, `AVG`) o `IN`/`EXISTS` para dejar clara la intención.",
    },
    practicaGuiada: {
      id: "m39-l4-practica",
      enunciado: "Lista los productos cuyo precio es **mayor que el precio promedio** de todos los productos, usando una subconsulta escalar. Devuelve el `nombre`, ordenado alfabéticamente.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT nombre FROM productos WHERE precio > (SELECT AVG(precio) FROM productos) ORDER BY nombre\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["`(SELECT AVG(precio) FROM productos)` es el promedio.", "Compara `precio > (...)`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Laptop',), ('Monitor',)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Laptop',), ('Monitor',)]" }
      },
    },
    reto: {
      id: "m39-l4-reto",
      enunciado: "Encuentra los pedidos cuya `cantidad` es **mayor que la cantidad promedio de ese mismo producto** (subconsulta correlacionada). Devuelve `id` y `cantidad`, ordenados por `id`.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT p.id, p.cantidad\nFROM pedidos p\nWHERE p.cantidad > (SELECT AVG(cantidad) FROM pedidos WHERE producto_id = p.producto_id)\nORDER BY p.id\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["La subconsulta filtra `WHERE producto_id = p.producto_id`.", "Compara `p.cantidad` con el promedio que devuelve."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[(4, 2), (6, 3), (7, 4), (9, 5)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [(4, 2), (6, 3), (7, 4), (9, 5)]" }
      },
    },
    verificacion: [
      {
        id: "m39-l4-q1",
        pregunta: "¿Cuándo es verdadera una condición `EXISTS (subconsulta)`?",
        opciones: ["Cuando devuelve al menos una fila", "Cuando devuelve exactamente un valor", "Cuando devuelve NULL", "Siempre"],
        respuestaCorrecta: 0,
        explicacion: "`EXISTS` solo comprueba si hay alguna fila; no importan sus columnas.",
      },
      {
        id: "m39-l4-q2",
        pregunta: "¿Por qué es más seguro `NOT EXISTS` que `NOT IN` para «los que no tienen…»?",
        opciones: ["Es más corto", "`NOT IN` no devuelve nada si la lista contiene un NULL", "Porque `NOT IN` no existe en SQL", "Porque `NOT EXISTS` es más rápido siempre"],
        respuestaCorrecta: 1,
        explicacion: "Con un NULL en la lista, `x NOT IN (...)` es desconocido para todos los valores y no devuelve filas. `NOT EXISTS` no tiene ese problema.",
      },
      {
        id: "m39-l4-q3",
        pregunta: "¿Qué hace que una subconsulta sea «correlacionada»?",
        opciones: ["Usa `JOIN`", "Referencia columnas de la consulta externa", "Devuelve varias columnas", "Está en el `FROM`"],
        respuestaCorrecta: 1,
        explicacion: "Al depender de la fila externa, se evalúa para cada una de ellas.",
      },
    ],
    resumen: ["Las subconsultas pueden devolver un valor, una lista, o decidir con `EXISTS`.", "Las correlacionadas usan columnas de la consulta externa.", "`NOT EXISTS` es más seguro que `NOT IN` cuando puede haber NULL."],
    proximoPaso: "En el siguiente módulo: CTE avanzadas y funciones de ventana.",
    conceptos: ["subconsultas", "exists"],
  },
]
