import type { Lesson } from '../../types'

export const module45Lessons: Lesson[] = [
  {
    id: "m45-l1",
    moduloId: "modulo-45",
    titulo: "DAX: medidas, columnas calculadas y contexto de filtro",
    objetivo: "Distinguir una medida de una columna calculada y entender que el resultado de una medida depende del contexto de filtro de cada celda del informe.",
    porQueImporta:
      "Este es el concepto que más cuesta y más importa en DAX: una medida no tiene «un valor», tiene uno distinto en cada celda de cada visual, según los filtros activos. Quien lo entiende, entiende DAX.",
    concepto: "> **Nota**: DAX no se ejecuta en el navegador de este curso. Cada lección muestra la fórmula DAX y te pide reproducir **la misma lógica con pandas**, que se corrige automáticamente. Para ver las medidas funcionando de verdad, créalas en Power BI Desktop (gratuito, solo Windows) con los datos de [`ventas-aurora.csv`](/datos/ventas-aurora.csv).\n\n**Columna calculada** vs **medida**:\n\n- Una **columna calculada** se calcula **fila por fila** al cargar o actualizar los datos y se **almacena** en el modelo (ocupa memoria). Sirve para atributos que quieres usar en filtros, ejes o segmentaciones. `Línea = Ventas[unidades] * Ventas[precio_unitario]`.\n- Una **medida** se calcula **al momento de mostrar** cada celda del informe, según los filtros activos. No ocupa espacio en las filas. Es lo que se usa para totales, promedios, porcentajes, KPI.\n\nMedidas básicas:\n\n```dax\nUnidades = SUM(Ventas[unidades])\nIngreso = SUMX(Ventas, Ventas[unidades] * Ventas[precio_unitario])\nProductos vendidos = DISTINCTCOUNT(Ventas[producto])\nPrecio medio = DIVIDE([Ingreso], [Unidades])\n```\n\n`SUMX` (y las demás funciones que terminan en X) **itera** fila por fila, evalúa una expresión y suma el resultado. `DIVIDE` divide y devuelve BLANK (o un valor alternativo) si el denominador es 0, en lugar de un error.\n\n**Contexto de filtro**: el conjunto de filtros que afectan a una celda: la fila y la columna del visual (por ejemplo, «región = Norte» y «categoría = Tecnología»), las segmentaciones, los filtros del informe y los filtros que llegan a través de las relaciones. Una misma medida, `[Ingreso]`, da un resultado distinto en cada celda de una matriz porque en cada una el contexto es distinto. Y el total de la matriz es la medida evaluada **sin** el filtro de esa fila o columna (no la suma de las celdas, aunque casi siempre coincida).\n\nEn pandas el contexto de filtro equivale a **filtrar el DataFrame** antes de agregar.",
    ejemploMinimo: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\n# Ingreso = SUMX(Ventas, Ventas[unidades] * Ventas[precio_unitario])\nprint(\"Ingreso total:\", (ventas[\"unidades\"] * ventas[\"precio_unitario\"]).sum())\n\n# Contexto de filtro: región = Norte\nnorte = ventas[ventas[\"region\"] == \"Norte\"]\nprint(\"Ingreso en Norte:\", (norte[\"unidades\"] * norte[\"precio_unitario\"]).sum())",
    ejemploAplicado: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\ndef ingreso(df, **filtros):\n    \"\"\"Equivale a la medida [Ingreso] bajo un contexto de filtro de igualdades.\"\"\"\n    for columna, valor in filtros.items():\n        df = df[df[columna] == valor]\n    return (df[\"unidades\"] * df[\"precio_unitario\"]).sum()\n\nprint(\"Sin filtros:\", ingreso(ventas))\nprint(\"Región Norte:\", ingreso(ventas, region=\"Norte\"))\nprint(\"Norte y Tecnologia:\", ingreso(ventas, region=\"Norte\", categoria=\"Tecnologia\"))",
    errorFrecuente: {
      codigo: "Columna calculada:  Porcentaje = Ventas[unidades] / SUM(Ventas[unidades])\n→ en cada fila divide entre el total de TODA la tabla, y se guarda; no cambia con los filtros del informe",
      explicacion:
        "Un porcentaje o un total que debe reaccionar a los filtros del informe **tiene que ser una medida**, no una columna calculada: la columna se calcula una vez al cargar los datos y no conoce el contexto de cada visual. Regla práctica: si el resultado debe cambiar cuando el usuario filtra, es una medida.",
    },
    practicaGuiada: {
      id: "m45-l1-practica",
      enunciado: "Completa `ingreso(df, **filtros)` para que devuelva la suma de `unidades * precio_unitario` de las filas que cumplan todos los filtros de igualdad (el «contexto de filtro»). El programa evalúa tres contextos.",
      codigoInicial: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\ndef ingreso(df, **filtros):\n    return None\n\nprint(ingreso(ventas))\nprint(ingreso(ventas, region=\"Norte\"))\nprint(ingreso(ventas, region=\"Norte\", categoria=\"Tecnologia\"))",
      solucion: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\ndef ingreso(df, **filtros):\n    for columna, valor in filtros.items():\n        df = df[df[columna] == valor]\n    return int((df[\"unidades\"] * df[\"precio_unitario\"]).sum())\n\nprint(ingreso(ventas))\nprint(ingreso(ventas, region=\"Norte\"))\nprint(ingreso(ventas, region=\"Norte\", categoria=\"Tecnologia\"))",
      pistas: ["Recorre `filtros.items()` y filtra el DataFrame con `df[df[columna] == valor]`.", "Al final suma `unidades * precio_unitario`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"3895790\",\"963870\",\"843700\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: 3895790\n963870\n843700" }
      },
    },
    reto: {
      id: "m45-l1-reto",
      enunciado: "Simula una **matriz** de Power BI: ingreso por región (filas) y categoría (columnas). Para cada región (`Norte`, `Sur`, `Este`, `Oeste`) imprime una línea `region accesorios oficina tecnologia total`, donde cada valor es el ingreso con ese contexto de filtro y `total` es el ingreso de la región sin filtrar categoría. Las categorías en orden alfabético.",
      codigoInicial: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\nREGIONES_ORDEN = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\nCATEGORIAS = [\"Accesorios\", \"Oficina\", \"Tecnologia\"]\n\nfor region in REGIONES_ORDEN:\n    print(region)",
      solucion: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\nREGIONES_ORDEN = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\nCATEGORIAS = [\"Accesorios\", \"Oficina\", \"Tecnologia\"]\n\ndef ingreso(df):\n    return int((df[\"unidades\"] * df[\"precio_unitario\"]).sum())\n\nfor region in REGIONES_ORDEN:\n    de_region = ventas[ventas[\"region\"] == region]\n    celdas = [ingreso(de_region[de_region[\"categoria\"] == c]) for c in CATEGORIAS]\n    print(region, *celdas, ingreso(de_region))",
      pistas: ["Filtra primero la región y, dentro de ella, cada categoría.", "El total de la fila es la medida con solo el filtro de región."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"Norte 35870 84300 843700 963870\",\"Sur 35740 80700 859300 975740\",\"Este 35610 83700 863900 983210\",\"Oeste 36470 83400 853100 972970\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: Norte 35870 84300 843700 963870\nSur 35740 80700 859300 975740\nEste 35610 83700 863900 983210\nOeste 36470 83400 853100 972970" }
      },
    },
    verificacion: [
      {
        id: "m45-l1-q1",
        pregunta: "¿Cuál es la diferencia principal entre una medida y una columna calculada?",
        opciones: ["No hay ninguna", "La medida se calcula al mostrar cada celda según los filtros; la columna se calcula fila por fila y se almacena", "La columna reacciona a las segmentaciones y la medida no", "La medida solo suma"],
        respuestaCorrecta: 1,
        explicacion: "La medida depende del contexto de filtro de cada celda; la columna se evalúa una vez al cargar los datos.",
      },
      {
        id: "m45-l1-q2",
        pregunta: "¿Qué hace `SUMX(Ventas, Ventas[unidades] * Ventas[precio_unitario])`?",
        opciones: ["Suma una columna ya calculada", "Recorre las filas, evalúa la expresión en cada una y suma los resultados", "Cuenta filas", "Multiplica dos totales"],
        respuestaCorrecta: 1,
        explicacion: "Las funciones con X iteran fila por fila y después agregan.",
      },
      {
        id: "m45-l1-q3",
        pregunta: "¿Por qué un porcentaje que debe cambiar con las segmentaciones debe ser una medida?",
        opciones: ["Porque las columnas no admiten división", "Porque la medida se recalcula con el contexto de filtro de cada visual", "Porque Power BI lo exige por licencia", "Porque es más rápido de escribir"],
        respuestaCorrecta: 1,
        explicacion: "Solo las medidas se reevalúan en cada contexto.",
      },
    ],
    resumen: ["Columna calculada: fila por fila, almacenada. Medida: al mostrar, según el contexto.", "El contexto de filtro son los filtros que afectan a cada celda; la misma medida da valores distintos.", "Si el resultado debe reaccionar a los filtros, usa una medida."],
    proximoPaso: "CALCULATE: la función que modifica el contexto de filtro.",
    conceptos: ["dax", "medida", "contexto-de-filtro"],
  },
  {
    id: "m45-l2",
    moduloId: "modulo-45",
    titulo: "CALCULATE: modificar el contexto de filtro",
    objetivo: "Usar CALCULATE para cambiar o quitar filtros y construir porcentajes del total y del grupo, y reproducir su lógica con pandas.",
    porQueImporta:
      "CALCULATE es la función más importante de DAX: casi todas las medidas de negocio útiles (porcentaje del total, comparación con el año anterior, acumulados) son variaciones de ella.",
    concepto: "> **Nota**: DAX no se ejecuta en el navegador de este curso. Cada lección muestra la fórmula DAX y te pide reproducir **la misma lógica con pandas**, que se corrige automáticamente. Para ver las medidas funcionando de verdad, créalas en Power BI Desktop (gratuito, solo Windows) con los datos de [`ventas-aurora.csv`](/datos/ventas-aurora.csv).\n\n`CALCULATE(<expresión>, <filtro1>, <filtro2>, …)` **evalúa la expresión en un contexto de filtro modificado** por los filtros que le pasas:\n\n```dax\nIngreso Norte = CALCULATE([Ingreso], Ventas[region] = \"Norte\")\n```\n\nAquí la medida siempre calcula el ingreso de Norte, sin importar qué región muestre la fila del visual: el filtro de CALCULATE **reemplaza** el filtro existente sobre `Ventas[region]`.\n\n**Quitar filtros** con `REMOVEFILTERS` (o `ALL`) para obtener totales de referencia:\n\n```dax\nIngreso total = CALCULATE([Ingreso], REMOVEFILTERS(Ventas[region]))\n% del total   = DIVIDE([Ingreso], CALCULATE([Ingreso], REMOVEFILTERS(Ventas[region])))\n```\n\nEl denominador ignora el filtro de región, de modo que cada región se compara con el total general.\n\n**Quitar todos los filtros excepto algunos**, con `ALLEXCEPT`: el porcentaje de cada región **dentro de su categoría**:\n\n```dax\n% dentro de categoría =\nDIVIDE([Ingreso], CALCULATE([Ingreso], ALLEXCEPT(Ventas, Ventas[categoria])))\n```\n\nIdea clave: **CALCULATE cambia el contexto de filtro; el resto es agregación normal**. En pandas esto equivale a calcular el numerador con el filtro de la celda y el denominador con otro filtro (o sin filtro).\n\nUna advertencia: el filtro booleano simple (`Ventas[region] = \"Norte\"`) funciona sobre una sola columna; para condiciones entre varias columnas se usa `FILTER`, que es más costoso, así que conviene usar los filtros simples siempre que sea posible.",
    ejemploMinimo: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\ntotal = ventas[\"ingreso\"].sum()\nnorte = ventas[ventas[\"region\"] == \"Norte\"][\"ingreso\"].sum()\nprint(\"% de Norte sobre el total:\", round(norte / total * 100, 1), \"%\")",
    ejemploAplicado: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\npor_region = ventas.groupby(\"region\")[\"ingreso\"].sum()\nporcentaje = (por_region / por_region.sum() * 100).round(1)   # DIVIDE([Ingreso], CALCULATE([Ingreso], REMOVEFILTERS(region)))\nprint(porcentaje)",
    errorFrecuente: {
      codigo: "% = DIVIDE(SUM(Ventas[ingreso]), SUM(Ventas[ingreso]))      -- siempre 100 %: numerador y denominador tienen el mismo contexto\n% = DIVIDE([Ingreso], CALCULATE([Ingreso], REMOVEFILTERS(Ventas[region])))   -- correcto",
      explicacion:
        "Un porcentaje del total necesita que el denominador **ignore** el filtro de la fila. Si ambos usan el mismo contexto, el resultado es siempre 100 %. Quitar el filtro con `REMOVEFILTERS`/`ALL` en el denominador es el patrón estándar.",
    },
    practicaGuiada: {
      id: "m45-l2-practica",
      enunciado: "Calcula el **% del total** de cada región (numerador: ingreso de la región; denominador: ingreso total sin filtrar). Imprime una línea por región en el orden `Norte`, `Sur`, `Este`, `Oeste` con el formato `region porcentaje` (1 decimal).",
      codigoInicial: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\ntotal = None\nfor region in [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]:\n    print(region, total)",
      solucion: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\ntotal = ventas[\"ingreso\"].sum()\nfor region in [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]:\n    de_region = ventas[ventas[\"region\"] == region][\"ingreso\"].sum()\n    print(region, round(de_region / total * 100, 1))",
      pistas: ["El denominador es `ventas[\"ingreso\"].sum()` sin filtro.", "El numerador filtra por región."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"Norte 24.7\",\"Sur 25.0\",\"Este 25.2\",\"Oeste 25.0\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: Norte 24.7\nSur 25.0\nEste 25.2\nOeste 25.0" }
      },
    },
    reto: {
      id: "m45-l2-reto",
      enunciado: "Calcula el equivalente de **`ALLEXCEPT(Ventas, Ventas[categoria])`**: el porcentaje que representa cada región **dentro de la categoría `Accesorios`**. Imprime `region porcentaje` (1 decimal) en el orden `Norte`, `Sur`, `Este`, `Oeste`.",
      codigoInicial: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\naccesorios = ventas[ventas[\"categoria\"] == \"Accesorios\"]\nresultado = None\nprint(resultado)",
      solucion: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\naccesorios = ventas[ventas[\"categoria\"] == \"Accesorios\"]\ntotal_categoria = accesorios[\"ingreso\"].sum()\nfor region in [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]:\n    parte = accesorios[accesorios[\"region\"] == region][\"ingreso\"].sum()\n    print(region, round(parte / total_categoria * 100, 1))",
      pistas: ["El denominador es el ingreso total de la categoría Accesorios (con filtro de categoría, sin filtro de región).", "El numerador añade el filtro de región."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"Norte 25.0\",\"Sur 24.9\",\"Este 24.8\",\"Oeste 25.4\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: Norte 25.0\nSur 24.9\nEste 24.8\nOeste 25.4" }
      },
    },
    verificacion: [
      {
        id: "m45-l2-q1",
        pregunta: "¿Qué hace `CALCULATE([Ingreso], Ventas[region] = \"Norte\")`?",
        opciones: ["Suma las regiones", "Evalúa [Ingreso] con el filtro de región reemplazado por Norte", "Ordena por región", "Cuenta regiones"],
        respuestaCorrecta: 1,
        explicacion: "CALCULATE evalúa su primer argumento en un contexto de filtro modificado por los demás.",
      },
      {
        id: "m45-l2-q2",
        pregunta: "¿Para qué sirve `REMOVEFILTERS` dentro de CALCULATE?",
        opciones: ["Para borrar datos", "Para ignorar filtros y obtener un total de referencia", "Para quitar columnas", "Para eliminar relaciones"],
        respuestaCorrecta: 1,
        explicacion: "Quita los filtros indicados del contexto: típico del denominador de un porcentaje.",
      },
      {
        id: "m45-l2-q3",
        pregunta: "¿Por qué un % del total con el mismo contexto en numerador y denominador da siempre 100 %?",
        opciones: ["Es un error de Power BI", "Porque ambos valores son iguales en cada celda", "Porque DIVIDE redondea", "Porque la medida no está formateada"],
        respuestaCorrecta: 1,
        explicacion: "Si no se quita el filtro en el denominador, ambos valen lo mismo.",
      },
    ],
    resumen: ["CALCULATE evalúa una expresión en un contexto de filtro modificado.", "`REMOVEFILTERS`/`ALL` y `ALLEXCEPT` dan los denominadores de los porcentajes.", "Los filtros booleanos simples sobre una columna son más eficientes que `FILTER`."],
    proximoPaso: "Con CALCULATE y la tabla de fechas, el siguiente paso es la inteligencia de tiempo.",
    conceptos: ["calculate", "porcentaje-del-total"],
  },
  {
    id: "m45-l3",
    moduloId: "modulo-45",
    titulo: "Inteligencia de tiempo: acumulado del año y año anterior",
    objetivo: "Calcular el acumulado del año (YTD) y la comparación con el mismo periodo del año anterior, y reproducir su lógica con pandas.",
    porQueImporta:
      "«¿Cuánto llevamos en el año?» y «¿cómo vamos frente al año pasado?» son las dos preguntas que más se repiten en cualquier reunión de resultados.",
    concepto: "> **Nota**: DAX no se ejecuta en el navegador de este curso. Cada lección muestra la fórmula DAX y te pide reproducir **la misma lógica con pandas**, que se corrige automáticamente. Para ver las medidas funcionando de verdad, créalas en Power BI Desktop (gratuito, solo Windows) con los datos de [`ventas-aurora.csv`](/datos/ventas-aurora.csv).\n\nLas funciones de inteligencia de tiempo requieren una **tabla de fechas** continua, relacionada con los hechos y marcada como tabla de fechas (lección anterior). Las más usadas:\n\n```dax\nIngreso YTD = TOTALYTD([Ingreso], Calendario[Fecha])\n\nIngreso año anterior =\nCALCULATE([Ingreso], SAMEPERIODLASTYEAR(Calendario[Fecha]))\n\nVar % año anterior =\nDIVIDE([Ingreso] - [Ingreso año anterior], [Ingreso año anterior])\n\nIngreso últimos 3 meses =\nCALCULATE([Ingreso], DATESINPERIOD(Calendario[Fecha], MAX(Calendario[Fecha]), -3, MONTH))\n```\n\n- `TOTALYTD` (*year to date*) acumula desde el 1 de enero hasta la fecha del contexto. Admite un tercer argumento para años fiscales que no empiezan en enero.\n- `SAMEPERIODLASTYEAR` devuelve las mismas fechas, desplazadas un año atrás: al envolverla en `CALCULATE`, la medida mira el periodo equivalente del año anterior. `DATEADD` generaliza la idea a otros desplazamientos (meses, trimestres).\n- `DATESINPERIOD` define ventanas móviles.\n\nCuidado con los **totales** y los **periodos incompletos**: si el año en curso solo tiene datos hasta octubre, comparar el total del año con el año anterior completo es engañoso; compara contra el mismo periodo (YTD contra YTD).\n\nLos datos de ventas de Aurora cubren 24 meses completos (2023 y 2024), así que la comparación año contra año es válida para los 12 meses de 2024.",
    ejemploMinimo: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\npor_mes = ventas.groupby(\"fecha\")[\"ingreso\"].sum()\nytd_2024 = por_mes[\"2024-01-01\":\"2024-12-01\"].cumsum()\nprint(ytd_2024.head(3))",
    ejemploAplicado: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\npor_mes = ventas.groupby(\"fecha\")[\"ingreso\"].sum()\nactual = por_mes[\"2024-01-01\":]\nanterior = por_mes[:\"2023-12-01\"]\nanterior.index = actual.index          # SAMEPERIODLASTYEAR: mismo mes, año anterior\n\nvariacion = ((actual - anterior) / anterior * 100).round(1)\nprint(variacion.head(4))",
    errorFrecuente: {
      codigo: "Var % = DIVIDE([Ingreso 2024 acumulado hasta octubre], [Ingreso 2023 completo]) - 1\n→ compara 10 meses contra 12: la caída aparente no es real",
      explicacion:
        "Comparar un periodo incompleto con uno completo da una conclusión falsa. Usa siempre el mismo periodo en ambos lados (por ejemplo, enero-octubre de ambos años), que es lo que hace `SAMEPERIODLASTYEAR` junto con un acumulado.",
    },
    practicaGuiada: {
      id: "m45-l3-practica",
      enunciado: "Calcula el **ingreso acumulado del año (YTD)** de 2024 mes a mes. Imprime una línea por mes con el formato `AAAA-MM acumulado` (usa `fecha[:7]`).",
      codigoInicial: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\npor_mes = ventas.groupby(\"fecha\")[\"ingreso\"].sum()\nytd = None\nprint(ytd)",
      solucion: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\npor_mes = ventas.groupby(\"fecha\")[\"ingreso\"].sum()\nytd = por_mes[\"2024-01-01\":\"2024-12-01\"].cumsum()\nfor fecha, valor in ytd.items():\n    print(fecha[:7], valor)",
      pistas: ["Filtra los meses de 2024 y aplica `cumsum()`.", "El índice de `por_mes` son textos `AAAA-MM-01`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"2024-01 174170\",\"2024-02 341310\",\"2024-03 521550\",\"2024-04 668910\",\"2024-05 848510\",\"2024-06 1002930\",\"2024-07 1203710\",\"2024-08 1378870\",\"2024-09 1575710\",\"2024-10 1756940\",\"2024-11 1934440\",\"2024-12 2122730\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: 2024-01 174170\n2024-02 341310\n2024-03 521550\n2024-04 668910\n2024-05 848510\n2024-06 1002930\n2024-07 1203710\n2024-08 1378870\n2024-09 1575710\n2024-10 1756940\n2024-11 1934440\n2024-12 2122730" }
      },
    },
    reto: {
      id: "m45-l3-reto",
      enunciado: "Calcula la **variación porcentual frente al mismo mes del año anterior** (como `SAMEPERIODLASTYEAR`) para cada mes de 2024. Imprime `AAAA-MM variacion` con 1 decimal.",
      codigoInicial: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\npor_mes = ventas.groupby(\"fecha\")[\"ingreso\"].sum()\nresultado = None\nprint(resultado)",
      solucion: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\npor_mes = ventas.groupby(\"fecha\")[\"ingreso\"].sum()\nactual = por_mes[\"2024-01-01\":]\nanterior = por_mes[:\"2023-12-01\"]\nfor (fecha, valor), previo in zip(actual.items(), anterior.values):\n    print(fecha[:7], round((valor - previo) / previo * 100, 1))",
      pistas: ["Cada mes de 2024 se empareja con el mismo mes de 2023 (12 posiciones atrás).", "Variación = (actual - anterior) / anterior × 100."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"2024-01 28.9\",\"2024-02 14.5\",\"2024-03 29.8\",\"2024-04 -3.1\",\"2024-05 50.8\",\"2024-06 2.0\",\"2024-07 43.1\",\"2024-08 1.5\",\"2024-09 34.0\",\"2024-10 7.5\",\"2024-11 16.0\",\"2024-12 26.1\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: 2024-01 28.9\n2024-02 14.5\n2024-03 29.8\n2024-04 -3.1\n2024-05 50.8\n2024-06 2.0\n2024-07 43.1\n2024-08 1.5\n2024-09 34.0\n2024-10 7.5\n2024-11 16.0\n2024-12 26.1" }
      },
    },
    verificacion: [
      {
        id: "m45-l3-q1",
        pregunta: "¿Qué necesitan las funciones de inteligencia de tiempo para funcionar bien?",
        opciones: ["Una tabla de fechas continua y relacionada con los hechos", "Una columna de texto", "Un gráfico de líneas", "Un filtro de página"],
        respuestaCorrecta: 0,
        explicacion: "Sin fechas completas y contiguas, los cálculos de periodos dan resultados incorrectos.",
      },
      {
        id: "m45-l3-q2",
        pregunta: "¿Qué hace `TOTALYTD`?",
        opciones: ["Acumula desde el inicio del año hasta la fecha del contexto", "Calcula el total de todos los años", "Resta dos años", "Ordena por año"],
        respuestaCorrecta: 0,
        explicacion: "YTD significa *year to date*: el acumulado del año hasta la fecha.",
      },
      {
        id: "m45-l3-q3",
        pregunta: "¿Por qué es engañoso comparar el año actual (10 meses) con el año anterior completo?",
        opciones: ["Porque son años distintos", "Porque se comparan periodos de distinta longitud", "Porque DAX no lo permite", "No es engañoso"],
        respuestaCorrecta: 1,
        explicacion: "La comparación válida usa el mismo periodo en ambos lados.",
      },
    ],
    resumen: ["`TOTALYTD` acumula el año; `SAMEPERIODLASTYEAR` mira el mismo periodo del año anterior.", "Requieren una tabla de fechas continua y marcada.", "Compara siempre periodos equivalentes."],
    proximoPaso: "Cerraremos DAX con variables, condicionales y rankings.",
    conceptos: ["inteligencia-de-tiempo", "ytd"],
  },
  {
    id: "m45-l4",
    moduloId: "modulo-45",
    titulo: "Variables, condicionales y rankings en DAX",
    objetivo: "Escribir medidas legibles con VAR/RETURN y SWITCH, calcular rankings con RANKX y clasificar elementos (por ejemplo, análisis ABC).",
    porQueImporta:
      "Las medidas reales se vuelven largas. Las variables las hacen legibles y más eficientes, y los rankings y clasificaciones («los productos que generan el 80 % del ingreso») son de las preguntas de negocio más frecuentes.",
    concepto: "> **Nota**: DAX no se ejecuta en el navegador de este curso. Cada lección muestra la fórmula DAX y te pide reproducir **la misma lógica con pandas**, que se corrige automáticamente. Para ver las medidas funcionando de verdad, créalas en Power BI Desktop (gratuito, solo Windows) con los datos de [`ventas-aurora.csv`](/datos/ventas-aurora.csv).\n\n**Variables** con `VAR` … `RETURN`: guardan un valor para usarlo después; evitan repetir cálculos y mejoran la lectura.\n\n```dax\nVar % año anterior =\nVAR Actual   = [Ingreso]\nVAR Anterior = [Ingreso año anterior]\nRETURN\n    DIVIDE(Actual - Anterior, Anterior)\n```\n\n**Condicionales**: `IF(condición, si_verdadero, si_falso)` y, para varios casos, `SWITCH(TRUE(), condición1, valor1, condición2, valor2, …, valor_por_defecto)`. Las condiciones se evalúan **en orden** y gana la primera que se cumple.\n\n```dax\nEstado =\nSWITCH(TRUE(),\n    [Ingreso] >= [Meta], \"Verde\",\n    [Ingreso] >= 0.9 * [Meta], \"Amarillo\",\n    \"Rojo\")\n```\n\n**Ranking** con `RANKX(<tabla>, <expresión>, [valor], [orden], [empates])`. El orden por defecto es descendente (el mayor es el puesto 1) y `empates` puede ser `Skip` (por defecto: 1, 1, 3) o `Dense` (1, 1, 2). `TOPN(n, tabla, expresión)` devuelve las `n` filas con mayor valor.\n\n```dax\nRanking producto = RANKX(ALL(Producto[producto]), [Ingreso], , DESC, Dense)\n```\n\n**Análisis ABC (Pareto)**: ordena los elementos de mayor a menor, calcula el **porcentaje acumulado** del total y clasifica. Una convención común: A hasta el 80 % acumulado, B hasta el 95 % y C el resto. Como todo umbral, se acuerda con el negocio.\n\n**Buenas prácticas**: nombres claros y sin abreviaturas crípticas, medidas en una tabla propia, formato (miles, porcentaje) definido en la medida, comentarios con `//`, y evitar columnas calculadas cuando una medida resuelve el problema.",
    ejemploMinimo: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\nv24 = ventas[ventas[\"fecha\"] >= \"2024-01-01\"]\npor_producto = v24.groupby(\"producto\")[\"ingreso\"].sum().sort_values(ascending=False)\nranking = por_producto.rank(ascending=False, method=\"min\").astype(int)   # RANKX con empates \"Skip\"\nprint(ranking)",
    ejemploAplicado: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\nv24 = ventas[ventas[\"fecha\"] >= \"2024-01-01\"]\npor_producto = v24.groupby(\"producto\")[\"ingreso\"].sum().sort_values(ascending=False)\nacumulado = (por_producto.cumsum() / por_producto.sum() * 100).round(1)\nprint(acumulado)",
    errorFrecuente: {
      codigo: "SWITCH(TRUE(),\n    [% acumulado] <= 0.95, \"B\",      -- el primer caso ya captura todo lo que debería ser A\n    [% acumulado] <= 0.80, \"A\",\n    \"C\")",
      explicacion:
        "En `SWITCH` y en `CASE`, las condiciones se evalúan en orden y gana la primera que se cumple. Si pones primero la condición más amplia, las demás no se alcanzan nunca. Ordena siempre de la más restrictiva a la más general.",
    },
    practicaGuiada: {
      id: "m45-l4-practica",
      enunciado: "Calcula el ranking de productos por ingreso en 2024, del mayor (puesto 1) al menor. Imprime una línea por producto con el formato `puesto producto`. (Equivale a `RANKX(ALL(Producto), [Ingreso])`.)",
      codigoInicial: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\nv24 = ventas[ventas[\"fecha\"] >= \"2024-01-01\"]\npor_producto = v24.groupby(\"producto\")[\"ingreso\"].sum()\nresultado = None\nprint(resultado)",
      solucion: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\nv24 = ventas[ventas[\"fecha\"] >= \"2024-01-01\"]\npor_producto = v24.groupby(\"producto\")[\"ingreso\"].sum().sort_values(ascending=False)\nfor puesto, producto in enumerate(por_producto.index, start=1):\n    print(puesto, producto)",
      pistas: ["Ordena el ingreso de mayor a menor con `sort_values(ascending=False)`.", "`enumerate(..., start=1)` da el puesto."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"1 Laptop\",\"2 Monitor\",\"3 Silla\",\"4 Teclado\",\"5 Mouse\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: 1 Laptop\n2 Monitor\n3 Silla\n4 Teclado\n5 Mouse" }
      },
    },
    reto: {
      id: "m45-l4-reto",
      enunciado: "Haz el **análisis ABC** de 2024: ordena los productos por ingreso de mayor a menor, calcula el porcentaje acumulado de cada uno (sobre el total) y asigna la clase `A` si ese acumulado es **menor o igual a 80**, `B` si es menor o igual a 95 y `C` en otro caso. Imprime `producto acumulado clase` (acumulado con 1 decimal).",
      codigoInicial: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\nv24 = ventas[ventas[\"fecha\"] >= \"2024-01-01\"]\npor_producto = v24.groupby(\"producto\")[\"ingreso\"].sum().sort_values(ascending=False)\nresultado = None\nprint(resultado)",
      solucion: "import pandas as pd\n\nPRODUCTOS = [(\"Laptop\", \"Tecnologia\", 2400), (\"Monitor\", \"Tecnologia\", 700), (\"Teclado\", \"Accesorios\", 90),\n             (\"Mouse\", \"Accesorios\", 40), (\"Silla\", \"Oficina\", 300)]\nREGIONES = [\"Norte\", \"Sur\", \"Este\", \"Oeste\"]\n\ndef generar_ventas(meses=24):\n    \"\"\"Ventas sintéticas de la tienda Aurora: un registro por mes, producto y región (desde 2023-01).\"\"\"\n    filas = []\n    for m in range(meses):\n        fecha = f\"{2023 + m // 12}-{m % 12 + 1:02d}-01\"\n        for i, (producto, categoria, precio) in enumerate(PRODUCTOS):\n            for j, region in enumerate(REGIONES):\n                unidades = 5 + (m * 3 + i * 7 + j * 5) % 11 + m // 6\n                filas.append((fecha, producto, categoria, region, unidades, precio))\n    return pd.DataFrame(filas, columns=[\"fecha\", \"producto\", \"categoria\", \"region\", \"unidades\", \"precio_unitario\"])\n\nventas = generar_ventas()\nventas[\"ingreso\"] = ventas[\"unidades\"] * ventas[\"precio_unitario\"]\n\nv24 = ventas[ventas[\"fecha\"] >= \"2024-01-01\"]\npor_producto = v24.groupby(\"producto\")[\"ingreso\"].sum().sort_values(ascending=False)\nacumulado = (por_producto.cumsum() / por_producto.sum() * 100).round(1)\n\ndef clase(pct):\n    if pct <= 80:\n        return \"A\"\n    if pct <= 95:\n        return \"B\"\n    return \"C\"\n\nfor producto, pct in acumulado.items():\n    print(producto, pct, clase(pct))",
      pistas: ["`por_producto.cumsum() / por_producto.sum() * 100` da el acumulado.", "Evalúa primero el umbral más bajo (80)."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"Laptop 67.8 A\",\"Monitor 87.8 B\",\"Silla 96.3 C\",\"Teclado 98.9 C\",\"Mouse 100.0 C\"]"
        return { ok, mensaje: ok ? "Correcto." : "El resultado no coincide. Debería ser: Laptop 67.8 A\nMonitor 87.8 B\nSilla 96.3 C\nTeclado 98.9 C\nMouse 100.0 C" }
      },
    },
    verificacion: [
      {
        id: "m45-l4-q1",
        pregunta: "¿Qué ventaja tienen las variables (`VAR`) en DAX?",
        opciones: ["Hacen la medida más lenta", "Evitan repetir cálculos y mejoran la legibilidad", "Permiten modificar datos", "Sustituyen a las relaciones"],
        respuestaCorrecta: 1,
        explicacion: "Una variable se evalúa una vez y se reutiliza; la medida se lee de arriba abajo.",
      },
      {
        id: "m45-l4-q2",
        pregunta: "En `SWITCH(TRUE(), ...)`, ¿qué ocurre si dos condiciones se cumplen?",
        opciones: ["Se aplican ambas", "Gana la primera que se cumple", "Da error", "Gana la última"],
        respuestaCorrecta: 1,
        explicacion: "Las condiciones se evalúan en orden; por eso se ordenan de la más restrictiva a la más general.",
      },
      {
        id: "m45-l4-q3",
        pregunta: "¿Qué diferencia hay entre empates `Skip` y `Dense` en `RANKX`?",
        opciones: ["Ninguna", "Con `Skip` tras un empate se salta una posición (1, 1, 3); con `Dense` no (1, 1, 2)", "`Dense` ordena al revés", "`Skip` elimina los empatados"],
        respuestaCorrecta: 1,
        explicacion: "Es la misma distinción entre `RANK` y `DENSE_RANK` en SQL.",
      },
    ],
    resumen: ["`VAR`/`RETURN` hacen las medidas legibles; `SWITCH(TRUE(), …)` resuelve varios casos en orden.", "`RANKX` y `TOPN` calculan rankings; el análisis ABC usa el porcentaje acumulado.", "Nombres claros, formato en la medida y comentarios."],
    proximoPaso: "En el último módulo diseñaremos el informe, lo publicaremos con seguridad por filas y haremos el proyecto.",
    conceptos: ["variables-dax", "rankx", "analisis-abc"],
  },
]
