import type { Lesson } from '../../types'

export const module42Lessons: Lesson[] = [
  {
    id: "m42-l1",
    moduloId: "modulo-42",
    titulo: "Proyecto, parte 1: calidad de datos y KPIs",
    objetivo: "Verificar la calidad de los datos con consultas de control y calcular los indicadores principales de la tienda.",
    porQueImporta:
      "Un analista profesional no empieza calculando: empieza comprobando que los datos son confiables. Un KPI correcto sobre datos duplicados o con referencias rotas es un error que se presenta con mucha seguridad.",
    concepto: "**El caso**: eres el analista de una tienda en línea que vende tecnología. La dirección pide un informe para decidir en qué enfocar el próximo trimestre. Tienes tres tablas: `clientes`, `productos` y `pedidos` (la misma base de práctica de todo el curso). El *ingreso* de un pedido es `cantidad * precio` del producto.\n\nEs un conjunto de datos muy pequeño (10 pedidos): sirve para practicar la técnica y comprobar cada resultado a mano, pero no para sacar conclusiones de negocio reales. En la vida real aplicarías exactamente las mismas consultas sobre miles o millones de filas.\n\n**Paso 1 · Controles de calidad**. Antes de medir, revisa:\n\n- **Claves repetidas**: que `COUNT(*)` y `COUNT(DISTINCT id)` coincidan.\n- **Referencias rotas**: pedidos que apuntan a un cliente o producto que no existe (se detectan con `LEFT JOIN ... WHERE c.id IS NULL`).\n- **Valores faltantes o absurdos**: cantidades nulas, negativas o cero; precios no positivos.\n\n**Paso 2 · KPIs**. Define cada indicador de forma explícita, porque dos personas pueden calcular «ticket promedio» de maneras distintas:\n\n- **Pedidos**: número de filas de `pedidos`.\n- **Clientes activos**: clientes distintos con al menos un pedido.\n- **Ingreso total**: suma de `cantidad * precio`.\n- **Ticket promedio**: ingreso total ÷ número de pedidos.\n\nRecuerda multiplicar por `1.0` o usar `AVG` sobre el importe para evitar la división entera.",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT COUNT(*) AS filas,\n       COUNT(DISTINCT id) AS ids_distintos,\n       SUM(CASE WHEN cantidad IS NULL OR cantidad <= 0 THEN 1 ELSE 0 END) AS cantidades_invalidas\nFROM pedidos\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT COUNT(*) AS pedidos_huerfanos\nFROM pedidos p\nLEFT JOIN clientes c ON c.id = p.cliente_id\nLEFT JOIN productos pr ON pr.id = p.producto_id\nWHERE c.id IS NULL OR pr.id IS NULL\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "SELECT SUM(p.cantidad * pr.precio) / COUNT(*) FROM pedidos p JOIN productos pr ON pr.id = p.producto_id\n-- Con precios decimales funciona, pero si ambos fueran enteros daría un entero truncado.\n-- Más seguro: AVG(p.cantidad * pr.precio), que siempre devuelve decimal.",
      explicacion:
        "Un KPI debe definirse antes de calcularse y expresarse de forma que no dependa de un detalle técnico (como la división entera). `AVG` sobre el importe de cada pedido da directamente el ticket promedio. Documenta siempre la fórmula junto al número.",
    },
    practicaGuiada: {
      id: "m42-l1-practica",
      enunciado: "Calcula los KPIs en una sola fila, con estas columnas y en este orden: `pedidos` (número de pedidos), `clientes_activos` (clientes distintos con pedidos), `ingreso_total` (suma de `cantidad * precio`) y `ticket_promedio` (ingreso total ÷ pedidos, redondeado a 1 decimal).",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT COUNT(*) AS pedidos,\n       COUNT(DISTINCT p.cliente_id) AS clientes_activos,\n       SUM(p.cantidad * pr.precio) AS ingreso_total,\n       ROUND(AVG(p.cantidad * pr.precio), 1) AS ticket_promedio\nFROM pedidos p\nJOIN productos pr ON pr.id = p.producto_id\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Une `pedidos` con `productos` para tener el precio.", "`ROUND(AVG(p.cantidad * pr.precio), 1)` es el ticket promedio."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[(10, 5, 8670.0, 867.0)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [(10, 5, 8670.0, 867.0)]" }
      },
    },
    reto: {
      id: "m42-l1-reto",
      enunciado: "Calcula el **ingreso por ciudad** de los clientes y su participación sobre el total (en %, 1 decimal), de mayor a menor. Columnas: `ciudad`, `ingreso`, `participacion`. Pista: `SUM(SUM(...)) OVER ()` da el total general sobre las filas agrupadas.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT c.ciudad,\n       SUM(p.cantidad * pr.precio) AS ingreso,\n       ROUND(100.0 * SUM(p.cantidad * pr.precio) / SUM(SUM(p.cantidad * pr.precio)) OVER (), 1) AS participacion\nFROM pedidos p\nJOIN clientes c ON c.id = p.cliente_id\nJOIN productos pr ON pr.id = p.producto_id\nGROUP BY c.ciudad\nORDER BY ingreso DESC\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Agrupa por `c.ciudad` y suma `cantidad * precio`.", "Una función de ventana puede envolver una agregación: `SUM(SUM(x)) OVER ()`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Bogota', 4600.0, 53.1), ('Cali', 2500.0, 28.8), ('Medellin', 1570.0, 18.1)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Bogota', 4600.0, 53.1), ('Cali', 2500.0, 28.8), ('Medellin', 1570.0, 18.1)]" }
      },
    },
    verificacion: [
      {
        id: "m42-l1-q1",
        pregunta: "¿Para qué sirve un control de calidad antes de calcular KPIs?",
        opciones: ["Para hacer la consulta más rápida", "Para detectar duplicados, referencias rotas y valores absurdos que falsean los resultados", "Para ordenar los datos", "No es necesario"],
        respuestaCorrecta: 1,
        explicacion: "Un cálculo correcto sobre datos defectuosos produce un resultado incorrecto presentado con seguridad.",
      },
      {
        id: "m42-l1-q2",
        pregunta: "¿Cómo se detectan pedidos que apuntan a un cliente inexistente?",
        opciones: ["`JOIN` y `HAVING`", "`LEFT JOIN` y `WHERE c.id IS NULL`", "`UNION`", "`DISTINCT`"],
        respuestaCorrecta: 1,
        explicacion: "Es un anti-join: los pedidos sin pareja en `clientes` quedan con `c.id` NULL.",
      },
      {
        id: "m42-l1-q3",
        pregunta: "¿Por qué conviene documentar la fórmula de cada KPI?",
        opciones: ["Por estética", "Porque dos personas pueden calcular el mismo nombre de forma distinta", "Porque SQL lo exige", "Para ahorrar memoria"],
        respuestaCorrecta: 1,
        explicacion: "Una definición explícita (qué cuenta y qué no) evita discusiones y errores al comparar cifras.",
      },
    ],
    resumen: ["Comprueba claves, referencias y valores antes de calcular nada.", "Define cada KPI de forma explícita: qué se cuenta y cómo.", "Una función de ventana puede calcular la participación sobre el total de filas agrupadas."],
    proximoPaso: "En la parte 2 analizaremos la evolución mensual y los rankings.",
    conceptos: ["calidad-de-datos", "kpi-sql"],
  },
  {
    id: "m42-l2",
    moduloId: "modulo-42",
    titulo: "Proyecto, parte 2: evolución mensual y rankings",
    objetivo: "Medir la evolución mensual del ingreso con LAG y obtener el producto líder de cada mes con funciones de ventana.",
    porQueImporta:
      "La dirección no solo quiere saber cuánto se vendió, sino cómo evoluciona y qué lo impulsa. Responder esas dos preguntas con SQL (sin exportar a Excel) es lo que demuestra dominio de las funciones de ventana.",
    concepto: "Continuamos con el caso de la tienda en línea. Dos preguntas para esta parte:\n\n1. **¿Cómo evoluciona el ingreso mes a mes?** Agrega el ingreso por mes (`strftime('%Y-%m', fecha)`) en una CTE y, en la consulta externa, usa `LAG` para comparar cada mes con el anterior.\n2. **¿Qué producto lidera cada mes?** Agrega por mes y producto, asigna una posición con `RANK() OVER (PARTITION BY mes ORDER BY ingreso DESC)` y filtra la primera.\n\nPlantilla de trabajo (patrón de «dos pasos»):\n\n```sql\nWITH mensual AS (\n    SELECT strftime('%Y-%m', fecha) AS mes, SUM(...) AS ingreso\n    FROM ... GROUP BY mes\n)\nSELECT mes, ingreso, LAG(ingreso) OVER (ORDER BY mes) AS anterior\nFROM mensual\n```\n\nPrimero agregas, y después aplicas la función de ventana sobre el resultado agregado. Ese orden (agregar → ventana → filtrar) se repite en casi todos los análisis de este tipo.\n\nCon tres meses de datos, la variación porcentual del primer mes no existe (no hay mes anterior): el resultado es NULL y debe mostrarse como «sin dato», no como 0.",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT strftime('%Y-%m', p.fecha) AS mes, SUM(p.cantidad * pr.precio) AS ingreso\nFROM pedidos p JOIN productos pr ON pr.id = p.producto_id\nGROUP BY mes ORDER BY mes\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nWITH mensual AS (\n    SELECT strftime('%Y-%m', p.fecha) AS mes, SUM(p.cantidad * pr.precio) AS ingreso\n    FROM pedidos p JOIN productos pr ON pr.id = p.producto_id\n    GROUP BY mes\n)\nSELECT mes, ingreso, SUM(ingreso) OVER (ORDER BY mes) AS acumulado\nFROM mensual\nORDER BY mes\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "SELECT strftime('%Y-%m', fecha) AS mes,\n       LAG(SUM(cantidad)) OVER (ORDER BY mes)     -- confuso: ventana sobre agregación en una sola capa\nFROM pedidos GROUP BY mes\n-- Más claro y más fácil de depurar: agregar en una CTE y aplicar LAG en la consulta externa",
      explicacion:
        "Se puede combinar agregación y ventana en la misma consulta, pero es difícil de leer y de depurar. El patrón en dos capas (CTE que agrega, consulta externa que aplica la ventana) es más claro, y cada paso se puede ejecutar por separado para comprobarlo.",
    },
    practicaGuiada: {
      id: "m42-l2-practica",
      enunciado: "Calcula el ingreso mensual y su **variación porcentual** respecto al mes anterior. Columnas: `mes`, `ingreso` y `variacion_pct` (`ROUND(100.0 * (ingreso - anterior) / anterior, 1)`), ordenadas por mes. El primer mes quedará en NULL.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nWITH mensual AS (\n    SELECT strftime('%Y-%m', p.fecha) AS mes, SUM(p.cantidad * pr.precio) AS ingreso\n    FROM pedidos p JOIN productos pr ON pr.id = p.producto_id\n    GROUP BY mes\n),\ncon_anterior AS (\n    SELECT mes, ingreso, LAG(ingreso) OVER (ORDER BY mes) AS anterior FROM mensual\n)\nSELECT mes, ingreso, ROUND(100.0 * (ingreso - anterior) / anterior, 1) AS variacion_pct\nFROM con_anterior\nORDER BY mes\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Primero la CTE `mensual`; después otra con `LAG(ingreso) OVER (ORDER BY mes)`.", "La variación es `(ingreso - anterior) / anterior`, por 100."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('2024-01', 2720.0, None), ('2024-02', 4750.0, 74.6), ('2024-03', 1200.0, -74.7)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('2024-01', 2720.0, None), ('2024-02', 4750.0, 74.6), ('2024-03', 1200.0, -74.7)]" }
      },
    },
    reto: {
      id: "m42-l2-reto",
      enunciado: "Obtén el **producto líder de cada mes por ingreso**. Columnas: `mes` y `producto`, ordenadas por mes. Agrega por mes y producto, rankea con `RANK() OVER (PARTITION BY mes ORDER BY ingreso DESC)` y filtra la posición 1.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nWITH m AS (\n    SELECT strftime('%Y-%m', p.fecha) AS mes, pr.nombre AS producto, SUM(p.cantidad * pr.precio) AS ingreso\n    FROM pedidos p JOIN productos pr ON pr.id = p.producto_id\n    GROUP BY mes, pr.nombre\n),\nr AS (\n    SELECT mes, producto, RANK() OVER (PARTITION BY mes ORDER BY ingreso DESC) AS pos FROM m\n)\nSELECT mes, producto FROM r WHERE pos = 1 ORDER BY mes\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Agrupa por `mes` y por producto en la primera CTE.", "Filtra `pos = 1` en la consulta final."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('2024-01', 'Laptop'), ('2024-02', 'Laptop'), ('2024-03', 'Monitor')]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('2024-01', 'Laptop'), ('2024-02', 'Laptop'), ('2024-03', 'Monitor')]" }
      },
    },
    verificacion: [
      {
        id: "m42-l2-q1",
        pregunta: "¿Cuál es el patrón recomendado para combinar agregación y funciones de ventana?",
        opciones: ["Todo en una sola consulta sin CTE", "Agregar en una CTE, aplicar la ventana después y filtrar fuera", "Usar solo subconsultas escalares", "Evitar las ventanas"],
        respuestaCorrecta: 1,
        explicacion: "Cada capa se puede probar por separado y la consulta final se lee de arriba abajo.",
      },
      {
        id: "m42-l2-q2",
        pregunta: "¿Qué valor tiene `LAG(ingreso)` en el primer mes?",
        opciones: ["0", "El ingreso del mismo mes", "NULL", "El promedio"],
        respuestaCorrecta: 2,
        explicacion: "No hay mes anterior, así que devuelve NULL; el análisis debe tratarlo como «sin dato».",
      },
      {
        id: "m42-l2-q3",
        pregunta: "¿Para qué sirve `RANK() OVER (PARTITION BY mes ORDER BY ingreso DESC)`?",
        opciones: ["Para sumar por mes", "Para posicionar los productos de cada mes de mayor a menor ingreso", "Para unir tablas", "Para filtrar fechas"],
        respuestaCorrecta: 1,
        explicacion: "Reinicia el ranking en cada mes; la posición 1 es el producto líder.",
      },
    ],
    resumen: ["El patrón «agregar → ventana → filtrar» ordena casi cualquier análisis temporal.", "La primera fila de una serie no tiene variación: queda en NULL.", "`RANK` con `PARTITION BY` da el líder de cada grupo."],
    proximoPaso: "En la parte final segmentaremos a los clientes y armaremos el reporte.",
    conceptos: ["analisis-temporal", "rank-por-grupo"],
  },
  {
    id: "m42-l3",
    moduloId: "modulo-42",
    titulo: "Proyecto, parte 3: segmentación de clientes y reporte final",
    objetivo: "Construir una tabla de clientes con recencia, frecuencia y valor, segmentarlos con CASE y redactar los hallazgos del informe.",
    porQueImporta:
      "Un reporte útil termina en decisiones: a quién retener, a quién reactivar, dónde invertir. La segmentación por recencia, frecuencia y valor (RFM) es una técnica clásica que se calcula íntegramente con SQL.",
    concepto: "Último paso del proyecto: pasar de los números al **mensaje**.\n\n**Segmentación RFM simplificada**. Para cada cliente calcula:\n\n- **Recencia**: días desde su última compra hasta una fecha de referencia (`julianday('2024-03-31') - julianday(MAX(fecha))`). Menos días = más reciente.\n- **Frecuencia**: número de pedidos.\n- **Valor monetario**: ingreso total.\n\nDespués, `CASE` define segmentos con reglas claras y documentadas. Por ejemplo, con el valor monetario: `VIP` (2 500 o más), `Regular` (1 000 o más), `Ocasional` (menos de 1 000) y `Sin compras` para quien no ha comprado. Usa un `LEFT JOIN` desde `clientes` para no perder a los que nunca compraron.\n\n**El reporte**. Un buen informe de analista tiene esta estructura:\n\n1. **Resumen ejecutivo**: tres frases con lo más importante (ingreso total, concentración, tendencia).\n2. **Evidencia**: las tablas y gráficos que lo respaldan, con la definición de cada KPI.\n3. **Recomendaciones**: acciones concretas y priorizadas (por ejemplo, un plan de reactivación para el segmento de clientes con compras antiguas).\n4. **Límites**: qué no puede concluirse. Aquí, por ejemplo, con 10 pedidos y 3 meses no hay base para hablar de estacionalidad ni de tendencias estables.\n\nEse último punto es el que distingue a un analista confiable: señalar con honestidad hasta dónde llegan los datos.",
    ejemploMinimo: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT c.nombre, MAX(p.fecha) AS ultima_compra, COUNT(p.id) AS pedidos\nFROM clientes c\nLEFT JOIN pedidos p ON p.cliente_id = c.id\nGROUP BY c.id, c.nombre\nORDER BY c.id\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    ejemploAplicado: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT c.nombre,\n       CAST(julianday('2024-03-31') - julianday(MAX(p.fecha)) AS INTEGER) AS dias_desde_ultima_compra\nFROM clientes c\nJOIN pedidos p ON p.cliente_id = c.id\nGROUP BY c.id, c.nombre\nORDER BY dias_desde_ultima_compra DESC\n\"\"\"\nfor fila in conn.execute(sql).fetchall():\n    print(fila)",
    errorFrecuente: {
      codigo: "SELECT CASE WHEN monto >= 1000 THEN 'Regular'\n            WHEN monto >= 2500 THEN 'VIP'      -- nunca se alcanza: el primer WHEN ya capturó esos casos\n            ELSE 'Ocasional' END\nFROM ...",
      explicacion:
        "`CASE` evalúa las condiciones **en orden** y se queda con la primera que se cumple. Si pones primero la condición más amplia (`>= 1000`), los clientes de 2 500 o más caen en ella y la condición de VIP no se alcanza nunca. Ordena siempre de la condición más restrictiva a la más general.",
    },
    practicaGuiada: {
      id: "m42-l3-practica",
      enunciado: "Construye la tabla RFM: para cada cliente que haya comprado devuelve `nombre`, `recencia` (días desde su última compra hasta `2024-03-31`, como entero), `frecuencia` (pedidos) y `monto` (ingreso). Ordena por `monto` descendente y luego por nombre.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nSELECT c.nombre,\n       CAST(julianday('2024-03-31') - julianday(MAX(p.fecha)) AS INTEGER) AS recencia,\n       COUNT(p.id) AS frecuencia,\n       SUM(p.cantidad * pr.precio) AS monto\nFROM clientes c\nJOIN pedidos p ON p.cliente_id = c.id\nJOIN productos pr ON pr.id = p.producto_id\nGROUP BY c.id, c.nombre\nORDER BY monto DESC, c.nombre\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Agrupa por cliente: `MAX(p.fecha)`, `COUNT(p.id)`, `SUM(cantidad * precio)`.", "La recencia es `julianday('2024-03-31') - julianday(MAX(p.fecha))`."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Ana', 30, 3, 2750.0), ('Pedro', 55, 1, 2500.0), ('Marta', 28, 2, 1850.0), ('Sofia', 22, 2, 1250.0), ('Luis', 46, 2, 320.0)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Ana', 30, 3, 2750.0), ('Pedro', 55, 1, 2500.0), ('Marta', 28, 2, 1850.0), ('Sofia', 22, 2, 1250.0), ('Luis', 46, 2, 320.0)]" }
      },
    },
    reto: {
      id: "m42-l3-reto",
      enunciado: "Segmenta a **todos** los clientes por su ingreso total (`VIP` si es 2500 o más, `Regular` si es 1000 o más, `Ocasional` si es mayor que 0 y menor que 1000, y `Sin compras` si no han comprado) y devuelve cuántos clientes hay en cada segmento: columnas `segmento` y `clientes`, ordenadas por `clientes` descendente y por segmento.",
      codigoInicial: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"   # escribe aquí tu consulta\nfilas = conn.execute(sql).fetchall() if sql else []\nprint(filas)",
      solucion: "import sqlite3\n\nconn = sqlite3.connect(\":memory:\")\nconn.executescript(\"\"\"\nCREATE TABLE clientes (id INTEGER PRIMARY KEY, nombre TEXT, ciudad TEXT, plan TEXT);\nCREATE TABLE productos (id INTEGER PRIMARY KEY, nombre TEXT, categoria TEXT, precio REAL);\nCREATE TABLE pedidos (id INTEGER PRIMARY KEY, cliente_id INTEGER, producto_id INTEGER, cantidad INTEGER, fecha TEXT);\n\nINSERT INTO clientes VALUES\n  (1, 'Ana', 'Bogota', 'Premium'), (2, 'Luis', 'Medellin', 'Basico'), (3, 'Marta', 'Bogota', 'Basico'),\n  (4, 'Pedro', 'Cali', 'Premium'), (5, 'Sofia', 'Medellin', 'Estandar'), (6, 'Diego', 'Bogota', 'Estandar');\nINSERT INTO productos VALUES\n  (1, 'Laptop', 'Electronica', 2500), (2, 'Mouse', 'Accesorios', 50), (3, 'Teclado', 'Accesorios', 120),\n  (4, 'Monitor', 'Electronica', 800), (5, 'Audifonos', 'Accesorios', 150);\nINSERT INTO pedidos VALUES\n  (1, 1, 1, 1, '2024-01-10'), (2, 1, 2, 2, '2024-01-12'), (3, 2, 3, 1, '2024-01-15'),\n  (4, 3, 4, 2, '2024-02-01'), (5, 4, 1, 1, '2024-02-05'), (6, 5, 5, 3, '2024-02-10'),\n  (7, 2, 2, 4, '2024-02-14'), (8, 1, 5, 1, '2024-03-01'), (9, 3, 2, 5, '2024-03-03'),\n  (10, 5, 4, 1, '2024-03-09');\n\"\"\")\n\nsql = \"\"\"\nWITH t AS (\n    SELECT c.id, COALESCE(SUM(p.cantidad * pr.precio), 0) AS monto\n    FROM clientes c\n    LEFT JOIN pedidos p ON p.cliente_id = c.id\n    LEFT JOIN productos pr ON pr.id = p.producto_id\n    GROUP BY c.id\n)\nSELECT CASE WHEN monto >= 2500 THEN 'VIP'\n            WHEN monto >= 1000 THEN 'Regular'\n            WHEN monto > 0 THEN 'Ocasional'\n            ELSE 'Sin compras' END AS segmento,\n       COUNT(*) AS clientes\nFROM t\nGROUP BY segmento\nORDER BY clientes DESC, segmento\n\"\"\"\nfilas = conn.execute(sql).fetchall()\nprint(filas)",
      pistas: ["Una CTE con el `monto` de cada cliente (con `LEFT JOIN` y `COALESCE`).", "El `CASE` va de la condición más restrictiva a la más general."],
      validar: (stdout) => {
        const l = stdout.trim().split('\n').map((x) => x.trim())
        const ok = JSON.stringify(l) === "[\"[('Regular', 2), ('VIP', 2), ('Ocasional', 1), ('Sin compras', 1)]\"]"
        return { ok, mensaje: ok ? "Correcto: la consulta devuelve el resultado esperado." : "El resultado no coincide. Debería ser: [('Regular', 2), ('VIP', 2), ('Ocasional', 1), ('Sin compras', 1)]" }
      },
    },
    verificacion: [
      {
        id: "m42-l3-q1",
        pregunta: "¿Qué mide la recencia en un análisis RFM?",
        opciones: ["El dinero gastado", "Cuántas veces compró", "Cuánto tiempo hace de su última compra", "Su ciudad"],
        respuestaCorrecta: 2,
        explicacion: "R = recencia (cuándo), F = frecuencia (cuántas veces), M = valor monetario (cuánto).",
      },
      {
        id: "m42-l3-q2",
        pregunta: "En un `CASE`, ¿qué ocurre si dos condiciones se cumplen a la vez?",
        opciones: ["Se aplican ambas", "Se aplica la primera que se cumple", "Da error", "Se aplica la última"],
        respuestaCorrecta: 1,
        explicacion: "`CASE` se detiene en la primera condición verdadera; el orden de las condiciones importa.",
      },
      {
        id: "m42-l3-q3",
        pregunta: "¿Por qué un informe debe incluir una sección de «límites»?",
        opciones: ["Por cumplir un formato", "Porque indica hasta dónde pueden llegar las conclusiones con esos datos", "Para alargar el informe", "Porque lo exige SQL"],
        respuestaCorrecta: 1,
        explicacion: "Con pocos datos, ciertas conclusiones no son confiables; señalarlo es parte de un análisis honesto.",
      },
    ],
    resumen: ["Recencia, frecuencia y valor se calculan con agregaciones y fechas.", "`CASE` define segmentos; el orden de las condiciones decide el resultado.", "Un reporte útil termina en recomendaciones y en los límites de lo que se puede concluir."],
    proximoPaso: "¡Has completado SQL para analítica! El siguiente paso de la ruta es Visualización y Power BI, para presentar estos resultados en tableros.",
    conceptos: ["rfm", "segmentacion", "informe-analitico"],
  },
]
