// ARCHIVO GENERADO por scripts/generate-lesson-index.mjs — no editar a mano.
// Se regenera con "npm run content:index" (y automáticamente en "npm run dev" y "npm run build").
import type { Lesson, LessonSummary } from '../types'

export const lessonIndex: LessonSummary[] = [
  { id: "m0-l1", moduloId: "modulo-0", titulo: "¿Qué es Python y para qué sirve en datos?" },
  { id: "m0-l2", moduloId: "modulo-0", titulo: "Entornos de trabajo: notebooks vs scripts" },
  { id: "m1-l1", moduloId: "modulo-1", titulo: "Variables y tipos de datos" },
  { id: "m1-l2", moduloId: "modulo-1", titulo: "Strings: creación y métodos esenciales" },
  { id: "m1-l3", moduloId: "modulo-1", titulo: "Operadores y expresiones" },
  { id: "m1-l4", moduloId: "modulo-1", titulo: "Entrada, salida y errores básicos" },
  { id: "m2-l1", moduloId: "modulo-2", titulo: "Condicionales: if, elif, else" },
  { id: "m2-l2", moduloId: "modulo-2", titulo: "Bucle for y range" },
  { id: "m2-l3", moduloId: "modulo-2", titulo: "While, break y continue" },
  { id: "m2-l4", moduloId: "modulo-2", titulo: "Comprensión de listas" },
  { id: "m3-l1", moduloId: "modulo-3", titulo: "Listas: indexación, slicing y métodos" },
  { id: "m3-l2", moduloId: "modulo-3", titulo: "Tuplas y diccionarios" },
  { id: "m3-l3", moduloId: "modulo-3", titulo: "Conjuntos (sets)" },
  { id: "m3-l4", moduloId: "modulo-3", titulo: "Estructuras anidadas" },
  { id: "m4-l1", moduloId: "modulo-4", titulo: "Definir funciones y retornar valores" },
  { id: "m4-l2", moduloId: "modulo-4", titulo: "Parámetros por defecto, *args y **kwargs" },
  { id: "m4-l3", moduloId: "modulo-4", titulo: "Alcance de variables y funciones lambda" },
  { id: "m4-l4", moduloId: "modulo-4", titulo: "Módulos e imports" },
  { id: "m5-l1", moduloId: "modulo-5", titulo: "Manejo de excepciones: try/except" },
  { id: "m5-l2", moduloId: "modulo-5", titulo: "Archivos y pathlib" },
  { id: "m5-l3", moduloId: "modulo-5", titulo: "JSON y CSV" },
  { id: "m5-l4", moduloId: "modulo-5", titulo: "Type hints y dataclasses" },
  { id: "m5-l5", moduloId: "modulo-5", titulo: "Código limpio, debugging y testing básico" },
  { id: "m6-l1", moduloId: "modulo-6", titulo: "NumPy: arrays y operaciones vectorizadas" },
  { id: "m6-l2", moduloId: "modulo-6", titulo: "pandas: Series y DataFrame" },
  { id: "m6-l3", moduloId: "modulo-6", titulo: "Selección y filtrado con loc/iloc" },
  { id: "m6-l4", moduloId: "modulo-6", titulo: "Leer y explorar datos reales con pandas" },
  { id: "m7-l1", moduloId: "modulo-7", titulo: "Detectar y eliminar duplicados" },
  { id: "m7-l2", moduloId: "modulo-7", titulo: "Valores ausentes: detectar, eliminar y rellenar" },
  { id: "m7-l3", moduloId: "modulo-7", titulo: "Tipos de datos y fechas" },
  { id: "m7-l4", moduloId: "modulo-7", titulo: "Combinar datasets: concat y merge" },
  { id: "m8-l1", moduloId: "modulo-8", titulo: "groupby: agrupar y agregar" },
  { id: "m8-l2", moduloId: "modulo-8", titulo: "Múltiples agregaciones con .agg()" },
  { id: "m8-l3", moduloId: "modulo-8", titulo: "Tablas dinámicas con pivot_table" },
  { id: "m8-l4", moduloId: "modulo-8", titulo: "Métricas de negocio: ingresos, margen y crecimiento" },
  { id: "m9-l1", moduloId: "modulo-9", titulo: "matplotlib básico: líneas y barras" },
  { id: "m9-l2", moduloId: "modulo-9", titulo: "Histogramas y boxplots" },
  { id: "m9-l3", moduloId: "modulo-9", titulo: "Scatter plots: relaciones entre variables" },
  { id: "m9-l4", moduloId: "modulo-9", titulo: "Storytelling: elegir el gráfico correcto" },
  { id: "m10-l1", moduloId: "modulo-10", titulo: "Estadística descriptiva: tendencia central y dispersión" },
  { id: "m10-l2", moduloId: "modulo-10", titulo: "Detección de outliers con IQR" },
  { id: "m10-l3", moduloId: "modulo-10", titulo: "Correlación entre variables" },
  { id: "m10-l4", moduloId: "modulo-10", titulo: "Distribuciones y percentiles" },
  { id: "m10-l5", moduloId: "modulo-10", titulo: "Introducción a pruebas de hipótesis" },
  { id: "m11-l1", moduloId: "modulo-11", titulo: "Proyecto: define el problema y carga los datos" },
  { id: "m11-l2", moduloId: "modulo-11", titulo: "Proyecto: limpia el dataset" },
  { id: "m11-l3", moduloId: "modulo-11", titulo: "Proyecto: métricas y visualización" },
  { id: "m11-l4", moduloId: "modulo-11", titulo: "Proyecto: conclusiones y reporte ejecutivo" },
  { id: "m12-l1", moduloId: "modulo-12", titulo: "Train/test split: la base de la generalización" },
  { id: "m12-l2", moduloId: "modulo-12", titulo: "Tu primer modelo: regresión lineal" },
  { id: "m12-l3", moduloId: "modulo-12", titulo: "Evaluar un modelo: overfitting y underfitting" },
  { id: "m12-l4", moduloId: "modulo-12", titulo: "Pipelines: preprocesamiento + modelo en un solo paso" },
  { id: "m13-l1", moduloId: "modulo-13", titulo: "Variables categóricas: One-Hot Encoding" },
  { id: "m13-l2", moduloId: "modulo-13", titulo: "Escalado de variables numéricas" },
  { id: "m13-l3", moduloId: "modulo-13", titulo: "Ingeniería de características temporales" },
  { id: "m13-l4", moduloId: "modulo-13", titulo: "Prevenir el data leakage" },
  { id: "m14-l1", moduloId: "modulo-14", titulo: "Métricas de regresión: MAE, RMSE y R²" },
  { id: "m14-l2", moduloId: "modulo-14", titulo: "Clasificación con regresión logística" },
  { id: "m14-l3", moduloId: "modulo-14", titulo: "Métricas de clasificación: matriz de confusión, precisión, recall y F1" },
  { id: "m14-l4", moduloId: "modulo-14", titulo: "Validación cruzada" },
  { id: "m14-l5", moduloId: "modulo-14", titulo: "Datos desbalanceados: estratificación y class_weight" },
  { id: "m15-l1", moduloId: "modulo-15", titulo: "K-Means: agrupar sin etiquetas" },
  { id: "m15-l2", moduloId: "modulo-15", titulo: "Elegir el número de clusters: inercia y silhouette" },
  { id: "m15-l3", moduloId: "modulo-15", titulo: "Escalar antes de agrupar" },
  { id: "m15-l4", moduloId: "modulo-15", titulo: "DBSCAN: clusters por densidad y detección de ruido" },
  { id: "m15-l5", moduloId: "modulo-15", titulo: "PCA: reducción de dimensionalidad" },
  { id: "m16-l1", moduloId: "modulo-16", titulo: "Series temporales con pandas: índice de fechas, resample y ventanas móviles" },
  { id: "m16-l2", moduloId: "modulo-16", titulo: "Validación temporal: nunca mezcles el futuro con el pasado" },
  { id: "m16-l3", moduloId: "modulo-16", titulo: "Pronóstico con variables de rezago y línea base" },
  { id: "m16-l4", moduloId: "modulo-16", titulo: "NLP básico: convertir texto en números con Bag of Words" },
  { id: "m16-l5", moduloId: "modulo-16", titulo: "TF-IDF y clasificación de texto" },
  { id: "m17-l1", moduloId: "modulo-17", titulo: "La neurona artificial" },
  { id: "m17-l2", moduloId: "modulo-17", titulo: "Capas y forward pass" },
  { id: "m17-l3", moduloId: "modulo-17", titulo: "Cómo aprende una red: pérdida y descenso de gradiente" },
  { id: "m17-l4", moduloId: "modulo-17", titulo: "Tu primera red con MLPClassifier" },
  { id: "m17-l5", moduloId: "modulo-17", titulo: "Arquitectura, sobreajuste y cuándo usar redes neuronales" },
  { id: "m18-l1", moduloId: "modulo-18", titulo: "Proyecto: define el problema y explora los datos" },
  { id: "m18-l2", moduloId: "modulo-18", titulo: "Proyecto: prepara los datos sin filtrar información" },
  { id: "m18-l3", moduloId: "modulo-18", titulo: "Proyecto: línea base y primer modelo" },
  { id: "m18-l4", moduloId: "modulo-18", titulo: "Proyecto: evalúa bien y maneja el desbalance" },
  { id: "m18-l5", moduloId: "modulo-18", titulo: "Proyecto: compara modelos y comunica conclusiones" },
  { id: "m19-l1", moduloId: "modulo-19", titulo: "SQL: SELECT, WHERE, ORDER BY y LIMIT" },
  { id: "m19-l2", moduloId: "modulo-19", titulo: "Agregaciones: COUNT, SUM, AVG, GROUP BY y HAVING" },
  { id: "m19-l3", moduloId: "modulo-19", titulo: "JOIN: combinar tablas" },
  { id: "m19-l4", moduloId: "modulo-19", titulo: "CASE, subconsultas y CTE (WITH)" },
  { id: "m19-l5", moduloId: "modulo-19", titulo: "SQL desde Python: pandas y consultas parametrizadas" },
  { id: "m20-l1", moduloId: "modulo-20", titulo: "La línea de comandos: rutas y navegación" },
  { id: "m20-l2", moduloId: "modulo-20", titulo: "Archivos y texto: mkdir, cp, mv, rm, cat, grep y wc" },
  { id: "m20-l3", moduloId: "modulo-20", titulo: "Anatomía de un comando y scripts con argumentos" },
  { id: "m20-l4", moduloId: "modulo-20", titulo: "Git: commits y el modelo mental" },
  { id: "m20-l5", moduloId: "modulo-20", titulo: "Ramas, .gitignore y trabajo con GitHub" },
  { id: "m21-l1", moduloId: "modulo-21", titulo: "Business Intelligence: KPIs y métricas que importan" },
  { id: "m21-l2", moduloId: "modulo-21", titulo: "Diseño de dashboards: elegir el gráfico correcto" },
  { id: "m21-l3", moduloId: "modulo-21", titulo: "Storytelling con datos: del hallazgo a la recomendación" },
  { id: "m21-l4", moduloId: "modulo-21", titulo: "Tu portafolio de datos en GitHub" },
  { id: "m21-l5", moduloId: "modulo-21", titulo: "Entrevistas técnicas y plan de carrera" },
  { id: "m22-l1", moduloId: "modulo-22", titulo: "Población, muestra y tipos de variables" },
  { id: "m22-l2", moduloId: "modulo-22", titulo: "Escalas de medición: nominal, ordinal, de intervalo y de razón" },
  { id: "m22-l3", moduloId: "modulo-22", titulo: "Tablas de frecuencia" },
  { id: "m22-l4", moduloId: "modulo-22", titulo: "Medidas de tendencia central: media, mediana y moda" },
  { id: "m22-l5", moduloId: "modulo-22", titulo: "Elegir la medida adecuada: simetría y sesgo" },
  { id: "m23-l1", moduloId: "modulo-23", titulo: "Rango, varianza y desviación estándar" },
  { id: "m23-l2", moduloId: "modulo-23", titulo: "Coeficiente de variación: comparar dispersiones" },
  { id: "m23-l3", moduloId: "modulo-23", titulo: "Cuantiles, percentiles y rango intercuartílico" },
  { id: "m23-l4", moduloId: "modulo-23", titulo: "Puntuaciones z: medir qué tan lejos está un dato" },
  { id: "m23-l5", moduloId: "modulo-23", titulo: "Valores atípicos: regla del IQR y boxplot" },
  { id: "m24-l1", moduloId: "modulo-24", titulo: "Forma de la distribución: asimetría y curtosis" },
  { id: "m24-l2", moduloId: "modulo-24", titulo: "Histogramas: agrupar datos en clases" },
  { id: "m24-l3", moduloId: "modulo-24", titulo: "Covarianza y correlación de Pearson" },
  { id: "m24-l4", moduloId: "modulo-24", titulo: "Correlación de Spearman y por qué correlación no es causalidad" },
  { id: "m24-l5", moduloId: "modulo-24", titulo: "Tablas de contingencia: relacionar dos variables categóricas" },
  { id: "m25-l1", moduloId: "modulo-25", titulo: "Proyecto: define la pregunta y revisa los datos" },
  { id: "m25-l2", moduloId: "modulo-25", titulo: "Proyecto: resume las variables numéricas" },
  { id: "m25-l3", moduloId: "modulo-25", titulo: "Proyecto: relaciones entre variables y comparación de grupos" },
  { id: "m25-l4", moduloId: "modulo-25", titulo: "Proyecto: conclusiones y reporte final" },
  { id: "m26-l1", moduloId: "modulo-26", titulo: "Experimentos, espacio muestral y eventos" },
  { id: "m26-l2", moduloId: "modulo-26", titulo: "Reglas de probabilidad: complemento y unión" },
  { id: "m26-l3", moduloId: "modulo-26", titulo: "Probabilidad condicional" },
  { id: "m26-l4", moduloId: "modulo-26", titulo: "Independencia y regla del producto" },
  { id: "m26-l5", moduloId: "modulo-26", titulo: "Teorema de Bayes: actualizar probabilidades con evidencia" },
  { id: "m27-l1", moduloId: "modulo-27", titulo: "Conteo: factoriales, permutaciones y combinaciones" },
  { id: "m27-l2", moduloId: "modulo-27", titulo: "Variables aleatorias discretas: esperanza y varianza" },
  { id: "m27-l3", moduloId: "modulo-27", titulo: "Distribución binomial" },
  { id: "m27-l4", moduloId: "modulo-27", titulo: "Distribución de Poisson" },
  { id: "m27-l5", moduloId: "modulo-27", titulo: "Simulación Monte Carlo y ley de los grandes números" },
  { id: "m28-l1", moduloId: "modulo-28", titulo: "Variables continuas, densidad y distribución uniforme" },
  { id: "m28-l2", moduloId: "modulo-28", titulo: "La distribución normal" },
  { id: "m28-l3", moduloId: "modulo-28", titulo: "Normal estándar, puntuaciones z y percentiles" },
  { id: "m28-l4", moduloId: "modulo-28", titulo: "Distribución exponencial: tiempos de espera" },
  { id: "m28-l5", moduloId: "modulo-28", titulo: "Teorema central del límite" },
  { id: "m29-l1", moduloId: "modulo-29", titulo: "Proyecto: modela la calidad de un lote (binomial)" },
  { id: "m29-l2", moduloId: "modulo-29", titulo: "Proyecto: dimensiona la capacidad (Poisson)" },
  { id: "m29-l3", moduloId: "modulo-29", titulo: "Proyecto: promete un plazo (distribución normal)" },
  { id: "m29-l4", moduloId: "modulo-29", titulo: "Proyecto: valida por simulación y reporta" },
  { id: "m30-l1", moduloId: "modulo-30", titulo: "Muestreo y sesgo de selección" },
  { id: "m30-l2", moduloId: "modulo-30", titulo: "Estimadores: media y varianza muestrales" },
  { id: "m30-l3", moduloId: "modulo-30", titulo: "Error estándar y tamaño de muestra" },
  { id: "m30-l4", moduloId: "modulo-30", titulo: "Intervalo de confianza para la media" },
  { id: "m30-l5", moduloId: "modulo-30", titulo: "Intervalo de confianza para una proporción" },
  { id: "m31-l1", moduloId: "modulo-31", titulo: "La lógica de las pruebas de hipótesis" },
  { id: "m31-l2", moduloId: "modulo-31", titulo: "Prueba t para una media" },
  { id: "m31-l3", moduloId: "modulo-31", titulo: "Comparar dos grupos: t independiente y t pareada" },
  { id: "m31-l4", moduloId: "modulo-31", titulo: "Comparar proporciones y A/B testing" },
  { id: "m31-l5", moduloId: "modulo-31", titulo: "Prueba chi-cuadrado de independencia" },
  { id: "m32-l1", moduloId: "modulo-32", titulo: "Regresión lineal simple" },
  { id: "m32-l2", moduloId: "modulo-32", titulo: "R², residuos y calidad del ajuste" },
  { id: "m32-l3", moduloId: "modulo-32", titulo: "Regresión múltiple con statsmodels" },
  { id: "m32-l4", moduloId: "modulo-32", titulo: "ANOVA: comparar tres o más grupos" },
  { id: "m32-l5", moduloId: "modulo-32", titulo: "Significancia, relevancia práctica y comparaciones múltiples" },
  { id: "m33-l1", moduloId: "modulo-33", titulo: "Proyecto: plantea el experimento y estima la conversión" },
  { id: "m33-l2", moduloId: "modulo-33", titulo: "Proyecto: contrasta la diferencia de conversión" },
  { id: "m33-l3", moduloId: "modulo-33", titulo: "Proyecto: compara los tiempos de pago y mide el efecto" },
  { id: "m33-l4", moduloId: "modulo-33", titulo: "Proyecto: reporte y recomendación" },
  { id: "m34-l1", moduloId: "modulo-34", titulo: "La hoja de cálculo: celdas, rangos y fórmulas" },
  { id: "m34-l2", moduloId: "modulo-34", titulo: "Funciones de resumen: SUMA, PROMEDIO, MIN, MAX y CONTAR" },
  { id: "m34-l3", moduloId: "modulo-34", titulo: "Referencias relativas, absolutas y mixtas" },
  { id: "m34-l4", moduloId: "modulo-34", titulo: "Lógica en las fórmulas: SI, Y, O y SI.ERROR" },
  { id: "m34-l5", moduloId: "modulo-34", titulo: "Texto y fechas: IZQUIERDA, EXTRAE, NOMPROPIO, AÑO y MES" },
  { id: "m35-l1", moduloId: "modulo-35", titulo: "Análisis con condiciones: CONTAR.SI, SUMAR.SI y PROMEDIO.SI" },
  { id: "m35-l2", moduloId: "modulo-35", titulo: "Varios criterios a la vez: SUMAR.SI.CONJUNTO y CONTAR.SI.CONJUNTO" },
  { id: "m35-l3", moduloId: "modulo-35", titulo: "Búsquedas: BUSCARV, INDICE y COINCIDIR" },
  { id: "m35-l4", moduloId: "modulo-35", titulo: "BUSCARX y búsquedas aproximadas por tramos" },
  { id: "m35-l5", moduloId: "modulo-35", titulo: "SUMAPRODUCTO, K.ESIMO.MAYOR y JERARQUIA" },
  { id: "m36-l1", moduloId: "modulo-36", titulo: "Limpieza de datos: texto con espacios y números guardados como texto" },
  { id: "m36-l2", moduloId: "modulo-36", titulo: "Estadística descriptiva en Excel: MEDIANA, DESVEST y cuartiles" },
  { id: "m36-l3", moduloId: "modulo-36", titulo: "Tablas dinámicas: resumir una tabla grande" },
  { id: "m36-l4", moduloId: "modulo-36", titulo: "Gráficos que comunican: elegir el gráfico y preparar los datos" },
  { id: "m36-l5", moduloId: "modulo-36", titulo: "Errores en las fórmulas, validación de datos y buenas prácticas" },
  { id: "m37-l1", moduloId: "modulo-37", titulo: "Proyecto: revisa y prepara los datos de ventas" },
  { id: "m37-l2", moduloId: "modulo-37", titulo: "Proyecto: resume las ventas por región, producto y mes" },
  { id: "m37-l3", moduloId: "modulo-37", titulo: "Proyecto: calcula las comisiones por tramos" },
  { id: "m37-l4", moduloId: "modulo-37", titulo: "Proyecto: reporte final y conclusiones" },
  { id: "m38-l1", moduloId: "modulo-38", titulo: "Filtros precisos, NULL y valores únicos" },
  { id: "m38-l2", moduloId: "modulo-38", titulo: "Funciones de texto y de números" },
  { id: "m38-l3", moduloId: "modulo-38", titulo: "Fechas: strftime, date y diferencias entre días" },
  { id: "m38-l4", moduloId: "modulo-38", titulo: "Agregación condicional: una tabla dinámica en SQL" },
  { id: "m39-l1", moduloId: "modulo-39", titulo: "JOIN de varias tablas y búsqueda de lo que falta (anti-join)" },
  { id: "m39-l2", moduloId: "modulo-39", titulo: "RIGHT, FULL, CROSS y SELF JOIN" },
  { id: "m39-l3", moduloId: "modulo-39", titulo: "UNION, INTERSECT y EXCEPT" },
  { id: "m39-l4", moduloId: "modulo-39", titulo: "Subconsultas: IN, EXISTS y correlacionadas" },
  { id: "m40-l1", moduloId: "modulo-40", titulo: "CTE encadenadas y recursivas" },
  { id: "m40-l2", moduloId: "modulo-40", titulo: "Funciones de ventana: OVER, PARTITION BY y ranking" },
  { id: "m40-l3", moduloId: "modulo-40", titulo: "LAG, LEAD y comparaciones entre filas" },
  { id: "m40-l4", moduloId: "modulo-40", titulo: "Acumulados, medias móviles y cuantiles con ventanas" },
  { id: "m41-l1", moduloId: "modulo-41", titulo: "Modificar datos: INSERT, UPDATE, DELETE, transacciones y upsert" },
  { id: "m41-l2", moduloId: "modulo-41", titulo: "Vistas, tablas derivadas e índices" },
  { id: "m41-l3", moduloId: "modulo-41", titulo: "De SQLite a tu motor: qué cambia entre PostgreSQL, SQL Server y MySQL" },
  { id: "m42-l1", moduloId: "modulo-42", titulo: "Proyecto, parte 1: calidad de datos y KPIs" },
  { id: "m42-l2", moduloId: "modulo-42", titulo: "Proyecto, parte 2: evolución mensual y rankings" },
  { id: "m42-l3", moduloId: "modulo-42", titulo: "Proyecto, parte 3: segmentación de clientes y reporte final" },
  { id: "m43-l1", moduloId: "modulo-43", titulo: "Elegir el gráfico según la pregunta" },
  { id: "m43-l2", moduloId: "modulo-43", titulo: "Diseño que comunica: orden, color y ejes honestos" },
  { id: "m43-l3", moduloId: "modulo-43", titulo: "Tableros: KPI, jerarquía visual y semáforos" },
  { id: "m43-l4", moduloId: "modulo-43", titulo: "Accesibilidad, contraste y storytelling" },
  { id: "m44-l1", moduloId: "modulo-44", titulo: "Power BI: el flujo de trabajo y la calidad de los datos" },
  { id: "m44-l2", moduloId: "modulo-44", titulo: "Power Query: transformaciones y su equivalente en pandas" },
  { id: "m44-l3", moduloId: "modulo-44", titulo: "Modelo en estrella: hechos, dimensiones y relaciones" },
  { id: "m44-l4", moduloId: "modulo-44", titulo: "La tabla de fechas (calendario) y el tiempo en el modelo" },
  { id: "m45-l1", moduloId: "modulo-45", titulo: "DAX: medidas, columnas calculadas y contexto de filtro" },
  { id: "m45-l2", moduloId: "modulo-45", titulo: "CALCULATE: modificar el contexto de filtro" },
  { id: "m45-l3", moduloId: "modulo-45", titulo: "Inteligencia de tiempo: acumulado del año y año anterior" },
  { id: "m45-l4", moduloId: "modulo-45", titulo: "Variables, condicionales y rankings en DAX" },
  { id: "m46-l1", moduloId: "modulo-46", titulo: "Diseñar el informe en Power BI: visuales, interacción y rendimiento" },
  { id: "m46-l2", moduloId: "modulo-46", titulo: "Publicar, actualizar y proteger datos con seguridad por filas (RLS)" },
  { id: "m46-l3", moduloId: "modulo-46", titulo: "Proyecto: tablero de ventas de la tienda Aurora" },
  { id: "m47-l1", moduloId: "modulo-47", titulo: "Qué es un modelo de lenguaje: tokens, contexto y costo" },
  { id: "m47-l2", moduloId: "modulo-47", titulo: "Cómo elige el modelo el siguiente token: probabilidades y temperatura" },
  { id: "m47-l3", moduloId: "modulo-47", titulo: "Límites de los modelos: alucinaciones, fecha de corte y verificación" },
  { id: "m47-l4", moduloId: "modulo-47", titulo: "Embeddings y búsqueda semántica" },
  { id: "m48-l1", moduloId: "modulo-48", titulo: "Anatomía de un buen prompt" },
  { id: "m48-l2", moduloId: "modulo-48", titulo: "Ejemplos (few-shot) y razonamiento paso a paso" },
  { id: "m48-l3", moduloId: "modulo-48", titulo: "Salidas estructuradas (JSON) y validación" },
  { id: "m48-l4", moduloId: "modulo-48", titulo: "Evaluar un prompt: conjunto de pruebas y métricas" },
  { id: "m49-l1", moduloId: "modulo-49", titulo: "RAG: responder con tus propios documentos" },
  { id: "m49-l2", moduloId: "modulo-49", titulo: "Herramientas: que el modelo consulte datos y ejecute funciones" },
  { id: "m49-l3", moduloId: "modulo-49", titulo: "Agentes: el ciclo de decidir, actuar y observar" },
  { id: "m49-l4", moduloId: "modulo-49", titulo: "Automatizar tareas de analista: clasificar, extraer y decidir si vale la pena" },
  { id: "m50-l1", moduloId: "modulo-50", titulo: "Privacidad y seguridad: datos personales e inyección de instrucciones" },
  { id: "m50-l2", moduloId: "modulo-50", titulo: "Sesgo y equidad: medir si el sistema trata distinto a distintos grupos" },
  { id: "m50-l3", moduloId: "modulo-50", titulo: "Gobernanza y regulación de la IA: marcos y buenas prácticas" },
  { id: "m50-l4", moduloId: "modulo-50", titulo: "Proyecto: asistente de preguntas frecuentes responsable" },
]

export const moduleLoaders: Record<string, () => Promise<Lesson[]>> = {
  'modulo-0': () => import('./modules/module0').then((m) => m.module0Lessons),
  'modulo-1': () => import('./modules/module1').then((m) => m.module1Lessons),
  'modulo-2': () => import('./modules/module2').then((m) => m.module2Lessons),
  'modulo-3': () => import('./modules/module3').then((m) => m.module3Lessons),
  'modulo-4': () => import('./modules/module4').then((m) => m.module4Lessons),
  'modulo-5': () => import('./modules/module5').then((m) => m.module5Lessons),
  'modulo-6': () => import('./modules/module6').then((m) => m.module6Lessons),
  'modulo-7': () => import('./modules/module7').then((m) => m.module7Lessons),
  'modulo-8': () => import('./modules/module8').then((m) => m.module8Lessons),
  'modulo-9': () => import('./modules/module9').then((m) => m.module9Lessons),
  'modulo-10': () => import('./modules/module10').then((m) => m.module10Lessons),
  'modulo-11': () => import('./modules/module11').then((m) => m.module11Lessons),
  'modulo-12': () => import('./modules/module12').then((m) => m.module12Lessons),
  'modulo-13': () => import('./modules/module13').then((m) => m.module13Lessons),
  'modulo-14': () => import('./modules/module14').then((m) => m.module14Lessons),
  'modulo-15': () => import('./modules/module15').then((m) => m.module15Lessons),
  'modulo-16': () => import('./modules/module16').then((m) => m.module16Lessons),
  'modulo-17': () => import('./modules/module17').then((m) => m.module17Lessons),
  'modulo-18': () => import('./modules/module18').then((m) => m.module18Lessons),
  'modulo-19': () => import('./modules/module19').then((m) => m.module19Lessons),
  'modulo-20': () => import('./modules/module20').then((m) => m.module20Lessons),
  'modulo-21': () => import('./modules/module21').then((m) => m.module21Lessons),
  'modulo-22': () => import('./modules/module22').then((m) => m.module22Lessons),
  'modulo-23': () => import('./modules/module23').then((m) => m.module23Lessons),
  'modulo-24': () => import('./modules/module24').then((m) => m.module24Lessons),
  'modulo-25': () => import('./modules/module25').then((m) => m.module25Lessons),
  'modulo-26': () => import('./modules/module26').then((m) => m.module26Lessons),
  'modulo-27': () => import('./modules/module27').then((m) => m.module27Lessons),
  'modulo-28': () => import('./modules/module28').then((m) => m.module28Lessons),
  'modulo-29': () => import('./modules/module29').then((m) => m.module29Lessons),
  'modulo-30': () => import('./modules/module30').then((m) => m.module30Lessons),
  'modulo-31': () => import('./modules/module31').then((m) => m.module31Lessons),
  'modulo-32': () => import('./modules/module32').then((m) => m.module32Lessons),
  'modulo-33': () => import('./modules/module33').then((m) => m.module33Lessons),
  'modulo-34': () => import('./modules/module34').then((m) => m.module34Lessons),
  'modulo-35': () => import('./modules/module35').then((m) => m.module35Lessons),
  'modulo-36': () => import('./modules/module36').then((m) => m.module36Lessons),
  'modulo-37': () => import('./modules/module37').then((m) => m.module37Lessons),
  'modulo-38': () => import('./modules/module38').then((m) => m.module38Lessons),
  'modulo-39': () => import('./modules/module39').then((m) => m.module39Lessons),
  'modulo-40': () => import('./modules/module40').then((m) => m.module40Lessons),
  'modulo-41': () => import('./modules/module41').then((m) => m.module41Lessons),
  'modulo-42': () => import('./modules/module42').then((m) => m.module42Lessons),
  'modulo-43': () => import('./modules/module43').then((m) => m.module43Lessons),
  'modulo-44': () => import('./modules/module44').then((m) => m.module44Lessons),
  'modulo-45': () => import('./modules/module45').then((m) => m.module45Lessons),
  'modulo-46': () => import('./modules/module46').then((m) => m.module46Lessons),
  'modulo-47': () => import('./modules/module47').then((m) => m.module47Lessons),
  'modulo-48': () => import('./modules/module48').then((m) => m.module48Lessons),
  'modulo-49': () => import('./modules/module49').then((m) => m.module49Lessons),
  'modulo-50': () => import('./modules/module50').then((m) => m.module50Lessons),
}
